### ISSUE TITLE
Floating point exception when using Trilinos/ML on OSX

### ISSUE THREAD

**Issue by joshua-white** [GEOSX/GEOSX#1092]
**Describe the bug**
We get SIGFPE problems when using Trilinos/ML on mac.  This has been reproduced on multiple machines.

**To Reproduce**
Run Tutorial 7 (elastic beam) with `preconditionerType=amg`.  Output is:

```sh
Received signal 8: Floating point exception: 8
Floating point exception:
** StackTrace of 24 frames **
Frame 1: LvArray::system::stackTraceHandler(int, bool)
Frame 2: _sigtramp
Frame 3: 0x0
Frame 4: ML_get_matrix_row
Frame 5: ML_estimate_avg_nz_per_row
Frame 6: ML_matmat_mult
...
```
**Platform:**
- OSX 10.14.6
- Clang 11.0.0
- Develop @ 9e841f0

**Comment by corbett5** [comment]
Could you try it with develop again? I know that there was some FPE stuff that was merged in the past few months. If that doesn't work you could try adding

``` c++
#if defined(__APPLE__)
LvArray::system::FloatingPointExceptionGuard guard;
#endif
```
Which will disable the floating point exceptions for the remainder of the scope.

**Comment by joshua-white** [comment]
Just re-tested with develop @ 04ef944, OSX 10.15, and clang 12.  Can't reproduce the issue, so hopefully this is fixed.  Will re-open if it emerges again.
