### ISSUE TITLE
Level of difficulty developing in GEOSX

### ISSUE THREAD

**Issue by rrsettgast** [GEOSX/GEOSX#1105]
On multiple occasions @joshua-white has stated that others find that GEOSX is "extremely difficult to develop in", and "not at all intuitive". I would like to build a list of issues that developers have that point to specific things that we may take action on, by either modifying the code, or targeted documentation. Please feel free to share your general experiences in developing new capabilities, but also please do include specifics that can lead to improvements.

I am tagging people because there GitHub only allows 10 assignees. I would specifically like feedback from everyone on this list.
@af1990 @klevzoff @AntoineMazuyer @TotoGaz @castelletto1 @cssherman @CusiniM @juliatcamargo @shabnamjs @joshua-white @andrea-borio @francoishamon @taojinllnl @wrtobin @WuHuiLLNL @huang40

**Comment by TotoGaz** [comment]
Some of the comments have been converted into actions in their own tickets.
Closing this issue as their is no more action awaited on it.
