### ISSUE TITLE
[Cleanup] Move all Proppant related solvers and kernels to a separate folder.

### ISSUE THREAD

**Issue by CusiniM** [GEOSX/GEOSX#1111]
The files related to the `ProppantTransportSolver` are currently either in under `fluidFlow` or in `multiphysics`. Since the `ProppantTransportSolver` cannot be run as a standalone solver and it is not really a fluid flow solver either, I propose to move all the files related to the `proppantTransportSolver` to a separate folder called `proppant` which could also contain the coupled solver `FlowProppantTransportSolver`.

**Comment by francoishamon** [comment]
Resolved a while ago by #1559
