### ISSUE TITLE
Mac build pattern won't work anymore with brew

### ISSUE THREAD

**Issue by TotoGaz** [GEOSX/GEOSX#1149]
As pointed by @af1990 in build https://travis-ci.com/github/GEOSX/GEOSX/jobs/382490297
There is something wrong with brew installing `open-mpi`.

PR https://github.com/Homebrew/brew/pull/8513 has disabled the functionality we were relying on (~installing old versions from an URL).
It's been deprecated since https://github.com/MikeMcQuaid/brew/commit/a35825ff230154fbab37c2ea936af4ebee65f186 (3 months), did not see it coming though.

There seems to be a new `brew extract` way imposed.
I quite don't get what they mean ; I'll give it a shot.
But I am not willing to spend to much time.

So If we cannot make it, I suggest that for the moment we give up this way of maintaining a specific version of `open-mpi`: let's rely on what `homebrew` wants. The result is that like the old days, from time to time we have to recompile the TPLs with the latest open-mpi.

Any comments?

**Comment by af1990** [comment]
I like the idea of always being up-to-date with the latest `open-mpi` version.

**Comment by TotoGaz** [comment]
> I like the idea of always being up-to-date with the latest `open-mpi` version.

Yes, it's nice. But the updates are uncontrolled, breaking the build anytime.
The previous pattern was allowing us to master it: we were at 4.0.2 instead of 4.0.5 (nothing broke), but we could have updated smoothly.

**Comment by TotoGaz** [comment]
Hi there!

I've tried some things here and there (including some dirty black magic I was kinda proud of) but I could not get an old version of `open-mpi` installed yet.
Difficult to debug the situation though (I cannot break my box and I cannot debug in travis anymore ; maybe doing some dummy "empty" private repo so `travis-ci` allows debug by default).

I will push a solution using the rolling release pattern of `homebrew`, we know we may have linking issues for updates, but we need a quick fix and it will give us some time to find a clean solution. And I guess we are not alone here.

**Comment by af1990** [comment]
Hi @TotoGaz,
what about
```
wget https://raw.github.com/Homebrew/homebrew-core/1e1370e0fddf2970695ab2e3b12ed5f24eb71819/Formula/open-mpi.rb
brew install open-mpi.rb  (i.e., the downloaded file)
```
?
