### ISSUE TITLE
Speeding up Kernel compilations 

### ISSUE THREAD

**Issue by rrsettgast** [GEOSX/GEOSX#1151]
The computational kernels take a long time to build. The root of the problem is that we have all of these nested dispatches that are requiring an instantiation for each permutation of the dispatch options. For example, for the solid mechanics kernels we have permutations between the finite element dispatch, and the constitutive dispatch. So if there are 4 finite element formulations, and 8 constitutive models, a single translation unit has to instantiate 32 variations of the kernel. Since this is done in a single translation unit, we cannot take advantage of parallel builds. Typically we are waiting for a long time at the end of the build for a few translation units.

We have discussed manually instantiating the variants in separate source files. Currently all the kernel code is in a header (for example `Kernel.hpp`). 
If we:

1. move the definition into a separate header file (`KernelDeclaration.hpp, KernelDefinition.hpp`), and include the `KernelDeclaration.hpp` in the physics solver source files.
2. Then create a collection of source files that include both `KernelDeclaration.hpp, KernelDefinition.hpp`, and manually instantiate some number of permutations.

I think this will result in faster build times depending on how many ranks we can use and how many translation units we break the permutations into. 

Looking for feedback or alternative proposals.

**Comment by TotoGaz** [comment]
Is it to save time for `travis-ci` or is it a general concern?

**Comment by rrsettgast** [comment]
> Is it to save time for `travis-ci` or is it a general concern?

I think it will...but I don't know how much.

**Comment by TotoGaz** [comment]
if it's for developers, maybe using `ninja` can help parallel compilations at low price.

**Comment by rrsettgast** [comment]
> if it's for developers, maybe using `ninja` can help parallel compilations at low price.

Does ninja break up a single translation unit into multiple compilations for you?

**Comment by corbett5** [comment]
> Does ninja break up a single translation unit into multiple compilations for you?

No, that's not possible.

**Comment by rrsettgast** [comment]
@corbett5 Uses ninja, and has setup the required cmake configuration options. But this requires a custom cmake or something like that?

**Comment by TotoGaz** [comment]
No it does not but it is better at not being blocked by compilation barriers.
So a long compilation may be able to start sooner: we'll wait less.

Of course, it will only be efficient if you have lots of files to build.
If you only have the problematic file, then it won't help.

**Comment by corbett5** [comment]
No you just need to pass an extra argument to cmake.

**Comment by rrsettgast** [comment]
Well...we have 4 cores on our TravisCI VM's now. Perhaps it is time to see if ninja will improve our build times. What is the flag? `CMAKE_MAKE_PROGRAM`?

**Comment by TotoGaz** [comment]
There is some `-G Ninja` when calling `cmake`.
But we need to install `ninja` of course.

**Comment by corbett5** [comment]
With lassen-clang10-release
- `ninja` takes 5m37.468s
- `ninja geosx` takes 4m13.073s
- `make -j` takes 7m29.730s
- `make -j geosx` takes 6m10.150s

We still spend a fair amount of time in linking, also ninja is supposed to shine when doing incremental builds but I haven't tested that here.
