### ISSUE TITLE
[Bug] EventManager and huge timesteps

### ISSUE THREAD

**Issue by joshua-white** [GEOSX/GEOSX#1163]
For a reservoir simulation, we may need to use a solver run with huge initial timesteps to establish hydrostatic and lithostatic equilibrium, and then write a restart to use as initial conditions for a regular timescale simulation.

@juliatcamargo was running into a problem where she wanted to take `1e12 s` timesteps.   We found that for events that do not specify a `forceDt`, the EventManager always tried to take smaller timesteps than expected.  For example, having
```
   <SoloEvent
     name="restarts"
     targetTime="1.0e12"
     target="/Outputs/restartOutput"/>
```
would lead to the following behavior:
```
Running simulation
Time: 0s, dt:2.14748e+09s, Cycle: 0
     Event: 0 (outputs0), dt_request=1e+12, forecast=465
     Event: 1 (restarts), dt_request=2.14748e+09, forecast=465
Time: 2.14748e+09s, dt:9.97853e+11s, Cycle: 1
     Event: 0 (outputs0), dt_request=9.97853e+11, forecast=1
     Event: 1 (restarts), dt_request=9.97853e+11, forecast=1
Time: 1e+12s, dt:2.5e+06s, Cycle: 2
     Event: 0 (outputs0), dt_request=2.5e+06, forecast=0
     Event: 1 (restarts), dt_request=2.14748e+09, forecast=0
Rank 0: Writing out restart file at dontwork_restart_000000002/rank_0000000.hdf5
```
where we see that the restart event has a first `dt_request=2.1e9`.  Adding a `forceDt=1e12` fixes this behavior:
```
   <SoloEvent
     name="restarts"
     targetTime="1.0e12"
     forceDt="1.0e12"
     target="/Outputs/restartOutput"/>
```
```
Running simulation
Time: 0s, dt:1e+12s, Cycle: 0
     Event: 0 (outputs0), dt_request=1e+12, forecast=1
     Event: 1 (restarts), dt_request=1e+12, forecast=1
Time: 1e+12s, dt:2.5e+06s, Cycle: 1
     Event: 0 (outputs0), dt_request=2.5e+06, forecast=0
     Event: 1 (restarts), dt_request=1e+12, forecast=0
Rank 0: Writing out restart file at dontwork_restart_000000001/rank_0000000.hdf5
```
Trying to diagnose what is going on, I noticed in a few places in the EventManager we have lines like:
```
setForecast( static_cast< integer >(std::min( forecast, 1e9 )) );
```
where I am guessing `1e9` was meant to be a huge number.  Could this be the source of the issue?  

We can run the simulation fine with `forceDt`, but the behavior was a bit unexpected (particularly for a SoloEvent where we don't really think about timestep increments).  Any suggestions?

**Comment by klevzoff** [comment]
> 2.14748e+09

![hmmm-looks-familiar-6lvtjs](https://user-images.githubusercontent.com/1550292/93529924-99d68100-f8f1-11ea-854e-17e30f7a7b37.jpg)


Pretty sure it's
https://github.com/GEOSX/GEOSX/blob/ae66ae80e40052ad87f282264310cb07e52b115f/src/coreComponents/managers/Events/EventBase.cpp#L279
and
https://github.com/GEOSX/GEOSX/blob/ae66ae80e40052ad87f282264310cb07e52b115f/src/coreComponents/dataRepository/ExecutableGroup.hpp#L90-L94

**Comment by joshua-white** [comment]
Good eye, @klevzoff .  Should we maybe use `globalIndex`?  Having not written this, I'm not sure why the requests are being done as integers, but I am sure there is a motivation.

**Comment by cssherman** [comment]
@joshua-white - @klevzoff is correct that the issue is in ExecutableGroup::GetTimeStepRequest.  The default max timestep should be based off of the numeric limits of a double, not an integer.  To be safe, we should probably not use the full value:

```
0.5 * std::numeric_limits< real64>::max();
```


In general, I would be a bit concerned with using such a large initial timestep.  If the subsequent timestep requests are comparatively small, then we could run into precision-related issues.

**Comment by cssherman** [comment]
@joshua-white - Also, for reference, the value of forecast can be thought of as the expected number of cycles until the event will execute.  This line is meant to avoid float conversion errors:

```
setForecast( static_cast< integer >(std::min( forecast, 1e9 )) );
```
