### ISSUE TITLE
[Bug] CMAKE error about INTERFACE_INCLUDE_DIRECTORIES

### ISSUE THREAD

**Issue by af1990** [GEOSX/GEOSX#1166]
**Bug description**
Creating the build directory, I have:
```
-- Configuring GEOSX version 0.0.31
-- Configuring done
CMake Error in coreComponents/LvArray/src/CMakeLists.txt:
  Target "lvarray" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/home/franc90/code/geosx/GEOSX/src/../../thirdPartyLibs/install-environment-release/chai/include"

  which is prefixed in the source directory.


-- Generating done
-- Build files have been written to: /home/franc90/code/geosx/GEOSX/build-environment-release
Makefile:95: recipe for target 'rebuild_cache' failed
make: *** [rebuild_cache] Error 1
```

**To Reproduce**
Create a new build directory with the usual python script and `environment` host config.

**Expected behavior**
No errors!

**Platform (please complete the following information):**
- Ubuntu 18.04
- gcc 8.4
- cmake 3.10.2 (I tried up to 3.16.3, same outcome ...)

**Additional context**
Other users seem to not have this issue ...

**Comment by TotoGaz** [comment]
So 
```
  Target "lvarray" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/home/franc90/code/geosx/GEOSX/src/../../thirdPartyLibs/install-environment-release/chai/include"
```
indeed points to 
```
/home/franc90/code/geosx//thirdPartyLibs/install-environment-release/chai/include
```
which I guess is valid.

There seems to be wrong "_file name resolution_".

Are you up-to-date with `LvArray.git` submodule ? No cache problem?
Using the python script, do you point to the TPLs explicitly (`-DGEOSX_TPL_DIR=/oath/to/TPLS...`) or do you let the default?
Can you give a shot by providing the absolute path?

**Comment by TotoGaz** [comment]
If it makes any difference, maybe changing https://github.com/GEOSX/GEOSX/blob/aa4b4d1389329eb44219c3f7596c299be8a76146/src/cmake/thirdparty/setupThirdPartyDirectory.cmake#L3-L5 ?
