### ISSUE TITLE
[Bug] Problem of memory allocation when creating GraphVertexFace

### ISSUE THREAD

**Issue by ValarcherL** [GEOSX/GEOSX#1168]
**Describe the bug**
After creating a variable as GraphVertexFace and stocking it in a GraphVertex list, it became impossible to cast it again as GraphVertexFace.
Furthermore the attribute associated with this class (m_correspondingId) is written over between two steps

**To Reproduce**
Using the branch feature/valarcher/graph_structure, run the command using src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_hex_gravity.xml as the input file (it is also important that the graph files mentioned in the xml are created) 

**Expected behavior**
During execution two series of paired number should appear, for each line the first number correspond to the m_correspondingId of the GraphVertexFace (it is supposed to be indentical to the index of the face it represents). The second number is the index of the second vertex of the edge in the global graph system.
The first set of values correspond to the values obtained just after the attribution of m_correspondingId at https://github.com/GEOSX/GEOSX/blob/1827b9dd14350256b3893637c2373f40d16fd2e5/src/coreComponents/mesh/GraphFromText.cpp#L432
The second set is the one recovered just before the creation of the stencil at
https://github.com/GEOSX/GEOSX/blob/40c6e008b27a704c299fe0c817fae0832f514cb0/src/coreComponents/finiteVolume/TwoPointFluxApproximationWithGraph.cpp#L143

We can see that the two values are different despite the fact that there are supposed to be left unchanged during the process.

![image](https://user-images.githubusercontent.com/68332658/93752569-2ab5a100-fbff-11ea-8c95-e73b9a9d234b.png)
Values after setting of m_correspondingId

![image](https://user-images.githubusercontent.com/68332658/93752649-41f48e80-fbff-11ea-86df-3df74210a0ab.png)
Values at recovery in ComputeBoundaryStencil

**Comment by rrsettgast** [comment]
@ValarcherL Did you mean to close this?

**Comment by herve-gross** [comment]
Yes, I think @ValarcherL found a solution to this issue.

**Comment by ValarcherL** [comment]
Yes sorry I closed it without giving a proper explanation. The problem was due to a deletion of the pointer by another function that will be reworked, as for the moment it shouldn't do that
