### ISSUE TITLE
[Feature] Bypassing PAMELA mesh generator on restart

### ISSUE THREAD

**Issue by francoishamon** [GEOSX/GEOSX#1171]
**What is the requested feature?**
I am trying to run a relatively large unstructured test case (8M tetrahedra) in which the mesh is read using PAMELA. In parallel, the mesh generation step in PAMELA  requires a lot of memory because each rank reads the entire mesh, which forces us to limit the number of ranks per node (otherwise we get an out-of-memory error). 

I was hoping to use the restart option to do the following (input file [here](https://totalcse.box.com/s/wpt2c62xa8t9vkx0p7s7ok1vsz342w3d)):
1) In a first simulation, read the mesh through PAMELA and output a restart file at the first time step:
```
srun -n 64 -N 64  ./geosx --input hi24l_co2_wells.xml
```
2) In a second simulation, start from the restart file directly to bypass PAMELA:
```
srun -n 64 -N 8  ./geosx --input hi24l_co2_wells.xml --restart hi24l_co2_wells_restart_000000001
```

But from the simulation output I see, PAMELA still reads the mesh at step 2), which is what I was trying to avoid.

**Describe the solution you'd like**
If possible, restart the simulation without going through PAMELA (and without reading the mesh again).
Any suggestion or code modification that I can try would be great.

**Describe alternatives you've considered**
I am not very familiar with the restart option. Maybe what I describe above is just the expected behavior and we simply cannot skip the mesh generation when we restart.

@rrsettgast @corbett5 I don't know whom to tag for this issue so please let me know if there is someone else that could help on that.

**Comment by corbett5** [comment]
That should definitely be possible. Reading in a restart file doesn't create any new Groups or Wrappers in the repository, what it does is resize/fill existing Wrappers that have a corresponding entry in the file.

I imagine this would mean passing a flag to PAMELA that tells it that it only needs to read in meta-data such as the sub-regions, etc instead of the entire geometry. @AntoineMazuyer does this sound possible?

**Comment by AntoineMazuyer** [comment]
It sounds possible ! I am not very familiar with the restart files too but I guess that if we restart after the PAMELAMeshGenerator GenerateMesh() method, we do not have anything to do ?

**Comment by corbett5** [comment]
We need to create the correct data repository structure, but the Wrappers have garbage data. This means that we need to know at least the number of and names of the regions and sub-regions.

**Comment by francoishamon** [comment]
Closed as not planned in the short term
