### ISSUE TITLE
[Bug] Submodule init appears to fails when user does not have access to integratedTests

### ISSUE THREAD

**Issue by cssherman** [GEOSX/GEOSX#1175]
I've been working with Hewei Tang to compile the code this morning, and ran into an issue with the submodule initialization.  Because she doesn't have permissions to access the integratedTests repository, the `git submodule init` commands throws an error and skips the initialization for the remaining submodules.

The solution should involve 1) fixing the git configuration and/or 2) updating the quickstart documentation to include a manual init for each submodule.

**Comment by joshua-white** [comment]
@csshermanm We added instructions to the quick start guide regarding de-initing the integratedTests.  Does that resolve this issue?

**Comment by cssherman** [comment]
@joshua-white - yep!
