### ISSUE TITLE
[Bug] Some cases run fine, but the results cannot be loaded in VisIt

### ISSUE THREAD

**Issue by herve-gross** [GEOSX/GEOSX#1186]
**Describe the bug**
Impossible to display the result of some simulations in VisIt even when the simulation is ending successfully on some test problems. Here is the error message when trying to load the results of the `10x10x10_LaplaceFEM`:

```VisIt could not read from the file "/Users/xx/tmp/siloFiles/plot_* database".

The generated error message was:

There was an error opening /Users/xx/tmp/siloFiles/plot_* database. It may be an invalid file.
VisIt tried using the following file format readers to open the file: PDB, Silo

If you know the specific format reader VisIt should use to
read this data, you can use Open As... (GUI) or
'-o <file>,<plugin> (CL arg.) and identify that specific reader
for VisIt to try. This will possibly give more information on
the exact error.
```

**To Reproduce**
Run GEOSX using the integrated test file `10x10x10_LaplaceFEM.xml`
Load the plot*.database file in VisIt

**Expected behavior**
It should load the files, and then allow users to visualize results.

**Platform (please complete the following information):**
- Machine : MacOS
- Compiler: AppleClang
- GEOSX Version: develop, commit hash ffaa7f0281c4b9d07b025502014c13ddcfb31c94

**Additional info**

Here is the console output of the run:

```
Running simulation
Time: 0s, dt:1s, Cycle: 0
Rank 0: Writing out restart file at 10x10x10_LaplaceFEM_restart_000000000/rank_0000000.hdf5
Time: 1s, dt:1s, Cycle: 1
Rank 0: Writing out restart file at 10x10x10_LaplaceFEM_restart_000000001/rank_0000000.hdf5
Cleaning up events
Rank 0: Writing out restart file at 10x10x10_LaplaceFEM_restart_000000002/rank_0000000.hdf5

init time = 0.061009s, run time = 0.40593s
Umpire            HOST high water mark:   15.0 MB
```

**Comment by sytuannguyen** [comment]
I got the same issue while running the Laplace solver. Actually I must output vtk data for visualization.
