### ISSUE TITLE
[Bug] Duplicated size of FaceManager.m_toElements

### ISSUE THREAD

**Issue by ValarcherL** [GEOSX/GEOSX#1192]
**Describe the bug**
The attribute of FaceManager m_toElements has size that is twice what it should be, similarly its own attributes (m_toElementRegion, m_toElementSubRegion, m_toElementIndex) are twice the size they should be too.
Going through any of those lists we see that the entries between the value n and 2n-1 are set to 0 or an extremely high number (4620974692658839552 for example) seemingly showing that those values are not even recorded.

**To Reproduce**
In any function executed after https://github.com/GEOSX/GEOSX/blob/b15e201de3d129af60cdf92cea1bf8d94bd073ae/src/coreComponents/managers/ProblemManager.cpp#L164 Recover the FaceManager from the MeshLevel and then use the providers for m_toElements or its lists
https://github.com/GEOSX/GEOSX/blob/b15e201de3d129af60cdf92cea1bf8d94bd073ae/src/coreComponents/mesh/FaceManager.hpp#L386-L436 Then just show the sizes or the elements to visualize the problem. 
I personnaly use the file src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_hex_gravity.xml as it is a simple 10*10*10 hexahedral mesh, and so the number of faces can be easily calculated (3300 expected, and so the size result show 6600 indices). I've tried to show the result at two different steps, the first case was done when I encountered the bug in my own part of the code in https://github.com/GEOSX/GEOSX/blob/3b7616bb3d5cf3ca335fd58f709e76a471100eea/src/coreComponents/mesh/GraphFromText.cpp#L472-L488 For this case I managed to get the value of the elemList after the value 3300 and having a return similar to this
![image](https://user-images.githubusercontent.com/68332658/95328260-9d807680-08a5-11eb-9a25-defcb8bfa199.png) 
To understand more the problem I tried to run it directly from the ProblemManager and got an error showing, but still the size of the lists is considered to be 6600
![image](https://user-images.githubusercontent.com/68332658/95329484-4e3b4580-08a7-11eb-9c45-235b6ae614d3.png) 
So depending where it is calle dit is possible that either one of this pattern will show, or even a third different one.

**Comment by ValarcherL** [comment]
@herve-gross @corbett5 Concerning the issue we were discussing I found some other things that I added there

**Comment by corbett5** [comment]
Can you try this out with an internally generated mesh? Say SSLE-sedov (which should also be 10x10x10)? If it works there then it's most likely an issue involving PAMELA.

**Comment by ValarcherL** [comment]
I tried it some time ago with src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/3D_10x10x10_compressible.xml, and got the same problem. With SSLE-sedov I see no particular difference (and I can confirm that is is a 10x10x10), the size appears as twice what it should be

**Comment by ValarcherL** [comment]
It seems that what I observed come from the fact that for a matrix constructed with LvArrays of size (m,n) the value returned from size() is m*n, a recovery of m or n is still possible with size(0) or size(1). Since it isn't really a bug, but more a misunderstanding of the function, I think I will close this issue
