### ISSUE TITLE
[Bug] PhaseFieldFracture_Damage tests need rebaseline

### ISSUE THREAD

**Issue by corbett5** [GEOSX/GEOSX#1208]
Some things in the data repository were renamed and the baselines need to be updated.

https://github.com/GEOSX/nightlyTests/blob/a5e1ea25b55fdd3879e7cbf80718ba16b733e9fa/quartz/integratedTestsDebugFiles/PhaseFieldFracture_DamageAndLoad_01.data#L3316

**Comment by corbett5** [comment]
@andrembcosta I tagged you because you're labeled as the owner of these tests.

**Comment by rrsettgast** [comment]
@taojinllnl This must have slipped through the cracks between all the updates. Can you rebaseline the tests again?

**Comment by taojinllnl** [comment]
> @taojinllnl This must have slipped through the cracks between all the updates. Can you rebaseline the tests again?

Will do.

**Comment by taojinllnl** [comment]
> @taojinllnl This must have slipped through the cracks between all the updates. Can you rebaseline the tests again?

@rrsettgast Just rebaselined the tests.

**Comment by taojinllnl** [comment]
#1213  This PR solved this issue.
