### ISSUE TITLE
[Bug] Potential difference calculation using molar variables for compositional simulations

### ISSUE THREAD

**Issue by francoishamon** [GEOSX/GEOSX#1209]
**Describe the bug**
With the `useMass` keyword, we have the capability to assemble either a molar balance (`useMass == 0`) or a mass balance (`useMass == 1`) in the compositional solvers (flow + wells). When `useMass == 0`, the `phaseDensity` field of `MultiFluidBase` contains molar densities [mol.m^-3], and when `useMass == 1`, `phaseDensity` becomes a vector of mass densities [kg.m^-3].

When the `gravityVector` is non-zero, we may have a unit inconsistency in the molar case when we compute the potential difference in the flux term (`CompositionalMultiphaseFlow::AssembleFluxTerm`)
and in the perforation rates (`CompositionalMultiphaseWell::ComputePerforationRates`). This issue is also present when we compute the hydrostatic pressure to initialize the wells (`CompositionalMultiphaseWell::InitializeWells`). 

The potential issue arises for the following reason. We compute the potential difference as:
`\Delta \Phi = \Delta p + \rho_{avg} g \Delta z`.
The unit of the potential difference in GEOSX is [Pa] = [kg.m^-1.s^-2], so the gravity term should be in the same unit. The gravitational acceleration is in [m.s^-2] and the elevation difference is [m], which suggests that the density used in the calculation of the potential difference should always be the mass density in [kg.m^-3], even when `useMass == 0`.

Hopefully I did not confuse myself. @klevzoff @CusiniM does what is above make sense to you?

**Expected behavior**
We should obtain the same results with `useMass == 0` and `useMass == 1` when the `gravityVector` is non-zero (provided that the initial component fractions have been adjusted appropriately in the input file).

**Additional context**
I started addressing this issue in `bugfix/hamon/gravTermWithMolarVars` by passing around an additional `phaseMassDensity` field for the potential difference calculations. It should be a quick fix, but I am not sure I will have time to finish it in the next couple of days, so I am posting this issue in the meantime.

**Comment by CusiniM** [comment]
Yes, I does make sense and I agree with you that the density used should be a mass density and not a molar one. What you are doing sounds reasonable. Anyways, I will check the PR and comment there on the fix you are proposing.

**Comment by klevzoff** [comment]
> @klevzoff @CusiniM does what is above make sense to you?

Yeah, and I'm glad someone is finally using the solver and finding my bugs from 2 years ago :)
