### ISSUE TITLE
[Feature] External Abaqus mesh support

### ISSUE THREAD

**Issue by cssherman** [GEOSX/GEOSX#1221]
**What is the requested feature?**
 We should consider support for importing abaqus (.inp) format meshes in GEOSX, since they were were the legacy mesh format for GEOS.  Alternately, we should build documentation / tools for handling conversion.

**Is your request related to a specific problem?**
I'm working with some meshes that are generated in Cubit, which are written in abaqus format.  These files have complicated surfaces that are defined via nodesets (topography, arbitrary faults, etc.).  Some of these surfaces would be quite cumbersome to define nodesets for using Geometry block.  For example:

![fault_mesh](https://user-images.githubusercontent.com/4932756/97748945-818a8200-1aab-11eb-8fd0-7c811b8873f8.png)

In the case of the faults, historically I've first imported the un-broken mesh, and then supplied the fault nodesets to the fracture generator.  My understanding is that the two external formats that we are currently supporting (gmsh and medit) don't support nodesets (please correct me if I am mistaken, @AntoineMazuyer ).

**Describe the solution you'd like**
I can see a couple of options available in the near-term:

1) Port the legacy abaqus reader from GEOS and use the existing workflow
2) Re-think the way that faults should be imported into GEOSX.  For example, will we need to manually split the mesh and construct the appropriate surface mesh that conforms to the fault
3) Write and include the (very long) set of Geometry instructions to define the fault

**Comment by cssherman** [comment]
Any thoughts @rrsettgast ?

**Comment by cssherman** [comment]
Another potential option would be to use the python interface and the meshio package: https://github.com/nschloe/meshio

**Comment by AntoineMazuyer** [comment]
HI @cssherman, is is possible using PAMELA and msh file format to define nodeset through surfaces.
Basically, a surface named "West" will generate a nodeset named "West" in GEOSX while loading it.

**Comment by rrsettgast** [comment]
We could always bring in the old reader, but I would rather consolidate the mesh reading in a single package. I think if we have a couple of options along this line. But yes, we should be able to read in abaqus meshes.

**Comment by cssherman** [comment]
> 
> 
> HI @cssherman, is is possible using PAMELA and msh file format to define nodeset through surfaces.
> Basically, a surface named "West" will generate a nodeset named "West" in GEOSX while loading it.

Which revisions of the format are you supporting?  The external mesh documentation says that we are supporting v2, but going over that documentation several times, it seems that only supports element tags.

Are we supporting the current revision of the .msh format (http://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format)?  And is there an example of such a file in the repository?  The ones that I've looked at only seem to use element tags.  The gmsh documentation is a bit... arcane.

**Comment by AntoineMazuyer** [comment]
We are indeed supporting the v2 mesh format

Quoting the documentation https://geosx-geosx.readthedocs-hosted.com/en/latest/coreComponents/mesh/docs/Mesh.html

> Surfaces are imported throught point sets in GEOSX. This feature is supported using only the gmsh file format. In the same way than the regions, the surfaces of interests can be defined using the physical entity names. The surfaces are automatically import in GEOSX if they exist in the gmsh file. Within GEOSX, the point set will have the same name than the one given in the file. This name can be used again to impose boundary condition. For instance, if a surface is named “Bottom” and the user wants to impose a Dirichlet boundary condition of 0 on it, it can be easily done using this syntax.

So you need to define the physical tag within the Gmsh file. It works the same way as the ElementRegion. There is a "toy_model.msh" with surfaces and regions defined as this in the repo, used in Tutorial 3.

**Comment by cssherman** [comment]
@AntoineMazuyer - Ahh, taking a look at that example, I think I understand how you are doing this.  I had seen that file before, but I had thought that it was building a separate face mesh for another purpose.  I'll give it a shot.

**Comment by AntoineMazuyer** [comment]
@cssherman don't hesitate to ping me on slack if you encounter some problems :)

**Comment by cssherman** [comment]
Addressed by #1224
