### ISSUE TITLE
[Feature] Customized realtive permeability table

### ISSUE THREAD

**Issue by tang39** [GEOSX/GEOSX#1226]
**What is the requested feature?**
Input two-phase relative permeability as tables

**Is your request related to a specific problem?**
Yes. The reservoir model I am currently working on has the permeability table from a research paper that specifically for scCO2 displacing water. It would be beneficial for a more flexible reservoir model.

**Describe the solution you'd like**
Input Sw, Krw, Sg, Krg as tables

**Additional context**
@francoishamon @rrsettgast @klevzoff @PengchengFu4 @cssherman

**Comment by tang39** [comment]
Found that the specific relative permeability table I am working on can fit to the Brooks-Corey relative permeability model.

**Comment by klevzoff** [comment]
I think the request is quite reasonable though. Up to you, but I'd keep it open to have it on our radar as I'm sure we'll eventually face this situation again.

**Comment by tang39** [comment]
Following @klevzoff 's suggestion, the feature request is reopened.

**Comment by cssherman** [comment]
@tang39 - While we often use functions with spatial/temporal inputs, they are completely general.  As long as you're OK with a linear/nearest interpolation on a grid, they should work.   Note: for this to work well, the input/output parameters should live on the same object (you would have to do additional work if you had mixed nodal/cell data for instance).

https://geosx-geosx.readthedocs-hosted.com/en/latest/coreComponents/managers/docs/FunctionManager.html#nd-table

**Comment by klevzoff** [comment]
> @tang39 - While we often use functions with spatial/temporal inputs, they are completely general. As long as you're OK with a linear/nearest interpolation on a grid, they should work. Note: for this to work well, the input/output parameters should live on the same object (you would have to do additional work if you had mixed nodal/cell data for instance).
> 
> https://geosx-geosx.readthedocs-hosted.com/en/latest/coreComponents/managers/docs/FunctionManager.html#nd-table

Yes, using `TableFunction` is definitely a good way to proceed from a design pov. We could just roll a constitutive model wrapper that delegates interpolation to a table object. The trickier part, however, would be to make it all work in a device kernel, which might involve a substantial change to `TableFunction`. This is important because relative permeability is evaluated for every cell in the flow domain, multiple times per time step.

**Comment by cssherman** [comment]
@klevzoff - great point.  We definitely would like to have table functions working on device, regardless.  I'll open a separate issue for this.

**Comment by klevzoff** [comment]
Oh, and one more thing - we need the table function to return not just the value, but also the derivative (i.e. slope). This shouldn't be difficult, but it does slightly extend the existing function interface.

**Comment by cssherman** [comment]
We've certainly considered this before.  There are a couple of easy ways to do this:

1) Rely on the user to calculate the derivatives and input them as separate tables (works now, but probably not preferred)
2) Have a flag in the table, which will compute the derivatives when the table is generated.  These could be accessed by generating new tables (using a standard naming scheme), or placed into some new structure in TableFunction.
3) Create a separate table interface that will compute derivatives on the fly.
