### ISSUE TITLE
[Other] Compilation problem(s)

### ISSUE THREAD

**Issue by user550** [GEOSX/GEOSX#1233]
I was trying to install the code per this [documentation](https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/QuickStart.html#download), but I am getting errors while compiling the main (`GEOSX`) code. Specifically, using the standard configuration file given under the instructions, I was able to complete the following steps for `thirdPartyLibs`:
```
cd thirdPartyLibs
python scripts/config-build.py -hc ../GEOSX/host-configs/your-platform.cmake -bt Release
cd build-your-platform-release
make

```
I encountered some errors while trying to `make` in the above step, which after spending a lot of time I was able to resolve by installing all the required `zlib` files. After that I moved to installing the main code, however I get an error at the following step that is related to an unidentified command/variable `blt_append_custom_compiler_flag`. Although it seems to be a flag, I could not find it anywhere in any of the given configuration file examples, but it does appear in few file (e.g. `src/cmake/GeosxOptions.cmake`, `src/CMakeLists.txt`).
```
cd ../../GEOSX
python scripts/config-build.py -hc host-configs/your-platform.cmake -bt Release
cd build-your-platform-release
```

*_Other issue, which although I believe is not keeping me from compilation, is that the `integratedTests` subdirectory is empty, so `git submodule update` after cloning gives an error. But, it seems like that should not be a problem to move forward with the compilation steps_.

**Comment by klevzoff** [comment]
Hi @user550 , there is indeed a known issue with `integratedTests` submodule which is currently restricted access. While the submodule itself is not required to build and run the code, it sometimes messes up the `update` command for other (required) submodules. I believe this is the source of the problem you're describing.

Could you please try making a fresh clone of the main code (GEOSX) and inside of it run, before anything else:
```
git submodule init
git submodule deinit integratedTests
git submodule update
```
and then proceed with the rest of the build steps (python, etc.).

Let us know if this helps.

**Comment by user550** [comment]
@klevzoff thanks. I followed the steps you listed and now although the other issue is resolved, I get a new error on `make install` for main code after `79%` of compilation as follows:

```
GEOSX/src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVM.cpp:311:54: internal compiler error: in finish_member_declaration, at cp/semantics.c:3029
                                      m_elemGhostRank.toNestedViewConst(),
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
coreComponents/physicsSolvers/CMakeFiles/physicsSolvers.dir/build.make:224: recipe for target 'coreComponents/physicsSolvers/CMakeFiles/physicsSolvers.dir/fluidFlow/SinglePhaseFVM.cpp.o' failed
make[2]: *** [coreComponents/physicsSolvers/CMakeFiles/physicsSolvers.dir/fluidFlow/SinglePhaseFVM.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:7767: recipe for target 'coreComponents/physicsSolvers/CMakeFiles/physicsSolvers.dir/all' failed
make[1]: *** [coreComponents/physicsSolvers/CMakeFiles/physicsSolvers.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by klevzoff** [comment]
@user550 Unfortunately it's a compiler bug. We've stopped supporting gcc-7 a while ago because of compiler crashes like this. Do you have the option to use gcc-8 or later or clang-8 or later on your system?

**Comment by user550** [comment]
@klevzoff thank you! Changing the compiler from gcc-7 to later version made it work.
