### ISSUE TITLE
[Other] Errors while running tutorials 4 and 9

### ISSUE THREAD

**Issue by user550** [GEOSX/GEOSX#1234]
I am getting errors while running Tutorial 4 and Tutorial 9. Following are the errors I get for these two tutorials, resp.:

**Tutorial 4:** I believe the error for this tutorial indicates there is no such directory (`GEOSXDATA/DataSets`) where mesh files are located: 
```
real64 is alias of double
localIndex is alias of long
globalIndex is alias of long long
GEOSX must be configured to use Python to use parameters, symbolic math, etc. in input files
Adding Solver of type CompositionalMultiphaseReservoir, named coupledFlowAndWells
Adding Solver of type CompositionalMultiphaseFlow, named compositionalMultiphaseFlow
Adding Solver of type CompositionalMultiphaseWell, named compositionalMultiphaseWell
Adding Mesh: PAMELAMeshGenerator, mesh
***** ERROR
***** LOCATION: /GEOSX/src/coreComponents/common/Path.cpp:39
***** Controlling expression (should be false): true
***** Rank 0: Could not get the absolute path for /GEOSX/src/coreComponents/physicsSolvers/fluidFlow/benchmarks/SPE10/../../../../../../../GEOSXDATA/DataSets/SPE10/EclipseBottomLayers/SPE10_LAYERS_83_84_85.GRDECL from /GEOSX/src/coreComponents/physicsSolvers/fluidFlow/benchmarks/SPE10
```

 **Tutorial 9:** I am using 6 cores to run this example as follows
`srun -n6 -ppdebug geosx -i hydrofracture_processed.xml -x 3 -y 1 -z 2`

I get the following messages (repeated messages have been removed) before the error:
```
real64 is alias of double
localIndex is alias of long
globalIndex is alias of long long
.
GEOSX must be configured to use Python to use parameters, symbolic math, etc. in input files
.
Adding Mesh: InternalMesh, mesh1
.
Adding Geometric Object: Box, source_a
.
Adding Geometric Object: Box, perf_a
.
Adding Geometric Object: ThickPlane, fracturable_a
.
Adding Solver of type Hydrofracture, named hydrofracture
.
Adding Solver of type SolidMechanicsLagrangianSSLE, named lagsolve
.
Adding Solver of type SinglePhaseFVM, named SinglePhaseFlow
.
Adding Solver of type SurfaceGenerator, named SurfaceGen
.
Adding Output: Silo, siloOutput
.
Adding Output: Restart, restartOutput
Adding Output: Restart, restartOutput
Adding Event: SoloEvent, preFracture
Adding Event: SoloEvent, preFracture
.
Adding Event: PeriodicEvent, outputs
.
Adding Event: PeriodicEvent, solverApplications_a
.
Adding Event: PeriodicEvent, solverApplications_b
.
Adding Event: PeriodicEvent, solverApplications_c
.
Adding Event: HaltEvent, restarts
.
   TableFunction: flow_rate
   .
   TableFunction: sigma_xx
   TableFunction: sigma_yy
   .
   TableFunction: sigma_zz
   .
   TableFunction: init_pressure
   .
   TableFunction: bulk_modulus
   .
   TableFunction: shear_modulus
   .
Adding Object CellElementRegion named Region2 from ObjectManager::Catalog.
.
Adding Object SurfaceElementRegion named Fracture from ObjectManager::Catalog.
.
```

The error following the above message I get (for each of the 6 frames) is: 
```
/GEOSX/src/coreComponents/mpiCommunications/SpatialPartition.cpp:256
***** Controlling expression (should be false): check != m_size
***** Rank 0: 
Expected check == m_size
  check = 6
  m_size = 1


** StackTrace of 6 frames **
Frame 0: geosx::InternalMeshGenerator::GenerateMesh(geosx::DomainPartition*) 
Frame 1: geosx::MeshManager::GenerateMeshes(geosx::DomainPartition*) 
Frame 2: geosx::ProblemManager::GenerateMesh() 
Frame 3: geosx::ProblemManager::ProblemSetup() 
Frame 4: main 
Frame 5: __libc_start_main 
Frame 6: _start
.
.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

It seems like this tutorial is giving error at the condition `check != m_size` in `SpatialPartition.cpp`, even though the only change I am making is the number of cores (from 36 to 6).

**Comment by francoishamon** [comment]
Hello @user550, 
Thanks for reporting these errors. The problem in Tutorial 4 is that we have not made the GEOSXDATA folder public yet. This folder contains the large meshes that we do not want to store in the main repository. The same error would occur for Tutorial 5 because it also reads a mesh located in the GEOSXDATA folder. Let me ask around about this and I will come back to you when we have a solution.

**Comment by cssherman** [comment]
@user550 - I just tried running Tutorial 9 using the partitioning scheme you mentioned using a recent version of GEOSX.  There is a bug in one of the xml files, but it does not appear to be related to the error message you received.  In heterogeneousInSituBase.xml, the attribute _Problem/Solvers/SolidMechanicsLagrangianSSLE/targetRegions_ should be equal to "{ Region2, Fracture }" (this is due to a recent-ish change in the way one of the key fields are initialized).

Once that is resolved, and the xml is pre-processed again, I don't see any errors.

**Comment by user550** [comment]
@francoishamon thank you!
@cssherman - thanks. I made the change you suggested, then pre-processed the input file (using geosx_xml_tools) before running it again, but unfortunately it did not change the error. The example seems to run without a cluster with `geosx -i hydrofracture_processed.xml` command.

**Comment by cssherman** [comment]
@user550 - that's interesting...  This problem is failing in a place that will be used by a lot of other problems, so I expect that the issue will show up for other parallel runs (not just Tutorial 9).  Have you tried running any other problems in parallel that use the internal mesh generator?  As a simple test, you could try running [Tutorial 8](https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/tutorials/step08/Tutorial.html) using two partitions along the x-dimension.

**Comment by user550** [comment]
@cssherman - I get the same error on running Tutorial 8 in parallel.
`srun -n 2 -ppdebug geosx -i poroElastic_Terzaghi.xml -x 2 -y 1 -z 1`


```
***** Controlling expression (should be false): check != m_size
***** Rank 0: 
Expected check == m_size
  check = 2
  m_size = 1
```

**Comment by cssherman** [comment]
@user550 - OK, I think what's happening here is that the parallel job is not starting (m_size is how many resources GEOSX has access to, check is how many are required for the specified partitioning scheme).

There are a number of ways to spin up a parallel job, and the one in the tutorial is relying on a slurm environment (srun).  If you aren't on a system using slurm, then you may need to run something like this (from the quick start guide, setting the appropriate paths to mpirun, geosx):

mpirun -np 8 ./bin/geosx -i your-problem.xml -x 2 -y 2 -z 2

**Comment by rrsettgast** [comment]
@cssherman @joshua-white 
Can we make a note for the next docday to expand some of the user docs to cover the various common ways to launch parallel jobs.

**Comment by user550** [comment]
@cssherman thanks. I ran using the `mpirun` command you suggested and it seemed to run, but it throws an error that doesn't stop it from continuing to run:
`ERROR : in almalgamation 28647 => 9549(9549).  Have you specified the correct number of DOFs?`

However, it throws another error after running for a while that stops the program:
```
GEOSX/src/coreComponents/physicsSolvers/SolverBase.cpp:592
***** Controlling expression (should be false): true
***** Rank 1: Nonconverged solutions not allowed. Terminating...
```

**Comment by rrsettgast** [comment]
@user550 can you provide more information?

1. The problem you are currently running
1. The exact command line execution command so that we can reproduce the error?
1. The platform and compiler you are running on?
1. The full output from running the `config-build.py` script?

**Comment by user550** [comment]
@rrsettgast -
1. Tutorial 8 (although I can't run any tutorial in parallel without an error).
2. `mpirun -np 8 ./bin/geosx -i poroElastic_Terzaghi.xml -x 2 -y 2 -z 2`
3. I am using `Ubuntu 18.04` with the following compilers: gcc-8, g++-8, mpicc, mpic++
```
$ mpicc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
$ mpic++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

```
4. It can be found in the file`output_configbuildpy` here: https://filebin.net/y6xnp6ixl5cje7mp

**Comment by cssherman** [comment]
@user550 - The mesh in Tutorial 8 is 42x1x1 elements in size.  So, the issue here is that you are requesting more parallel ranks in the y/z dimensions than there are elements.  I expect that if you run the following, the problem will run  as expected:

mpirun -np 2 ./bin/geosx -i poroElastic_Terzaghi.xml -x 2 -y 1 -z 1

**Comment by user550** [comment]
@cssherman - you are right. Changing the cores to `1` for each y and z dimensions made it work. However, using the same strategy/command to tutorial 9 throws a convergence error: `mpirun -np 8 geosx -i hydrofracture_processed.xml -x 2 -y 2 -z 2`

```
.
.
ERROR : in almalgamation 28647 => 9549(9549).  Have you specified the correct number of DOFs?
ERROR : in almalgamation 28647 => 9549(9549).  Have you specified the correct number of DOFs?
New dt = 0.5
Convergence not achieved.
***** ERROR
***** LOCATION: /home/code_geosx/GEOSX/src/coreComponents/physicsSolvers/SolverBase.cpp:592
***** Controlling expression (should be false): true
***** Rank 1: Nonconverged solutions not allowed. Terminating...

```

**Comment by francoishamon** [comment]
Hello @user550 and sorry for jumping in the middle of the conversation. 

The [GEOSXDATA](https://github.com/GEOSX/GEOSXDATA) repository is now public which should allow you to run Tutorials 4 and 5. You will have to clone it next to the main GEOSX folder as explained at the beginning of the [tutorial](https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/tutorials/step04/Tutorial.html#tutorial-4-multiphase-flow-with-wells).

If you try, you will see that the tutorials 4 and 5 (and 6) are configured to run with a direct solver and that they are therefore slow (see #1069). We recently made some changes in the default configuration of GEOSX that make it possible to use a more efficient iterative solver (specifically, gmres preconditioned by Multigrid Reduction (MGR) from the _hypre_ linear solver package). I will work on updating the tutorials to accelerate them now, thanks for your patience.

**Comment by user550** [comment]
@francoishamon - thank you! Not a problem. I appreciate your help.
