### ISSUE TITLE
testLAOperations fails on Lassen with Trilinos/SolverTestLaplace2D/0.Direct

### ISSUE THREAD

**Issue by corbett5** [GEOSX/GEOSX#1238]
After #1169 `testLAOperations` fails on Lassen.

**Comment by castelletto1** [comment]
It is a problem with Superlu_dist. Switching to the serial direct solver removes the error.

**Comment by af1990** [comment]
> It is a problem with Superlu_dist. Switching to the serial direct solver removes the error.

Does it work properly with a serial direct solver?
Can we close the issue?

**Comment by castelletto1** [comment]
The problem with Superlu_dist is this function:

https://github.com/GEOSX/GEOSX/blob/ecaa0f242c7f24fa523ecae350b58e2458d46b84/src/coreComponents/linearAlgebra/interfaces/direct/SuperLU_Dist.cpp#L154-L165

The serial solver fixes the issue on Lassen, but we can't close it yet. The serial direct solver doesn't pass one unit test ([Pangea2_gcc8.3.0_release](https://travis-ci.com/github/GEOSX/GEOSX/jobs/444166784)).
