### ISSUE TITLE
Wrong deletion in the parallelization of the graph

### ISSUE THREAD

**Issue by ValarcherL** [GEOSX/GEOSX#1241]
**Describe the bug**
When running a parallel call with the graph loaded the expected behavior is the deletion of vertices depending on wether or not their associated element in the mesh is deleted. The function of vertex deletion makes sure that no reference to the deleted vertex still exist, by deleting the associated edge. But running through the code some invalid edges still exist (pointing to adresses where a call to the index send a value like 2000000).
Initially the lists were done using vectors and the simulation functionned, although the problem might exist at this time as no check were executed. Changing to array1d those wrong adresses prevent from running the code in parallel.

**To Reproduce**
Switch to the branch feature/valarcher/graph_structure
Run the xml file located in src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_hex_gravity.xml

**Additional context**
The problem was first observed on the boundary conditions, having some inconsistencies in values, and the change to array1d was done to see if something changed.

**Comment by joshua-white** [comment]
@ValarcherL, It sounds like you still have some exploration to do to make a minimal example.  Let us know if we can help with anything.

**Comment by TotoGaz** [comment]
Concerns an abandoned dev.
