### ISSUE TITLE
[Feature] Add a cuda debug build to Travis

### ISSUE THREAD

**Issue by CusiniM** [GEOSX/GEOSX#1248]
**What is the requested feature?**
Add a cuda debug build to Travis.

**Is your request related to a specific problem?**
On Travis we only test cuda release builds. Some NVCC errors only show up in debug builds and it has happened that they were not caught prior to merging certain branches.

**Describe the solution you'd like**
add clang-cuda and gcc-cuda debug to travis.

@corbett5

**Comment by corbett5** [comment]
My preference would actually be to change one of the existing CUDA builds from release to debug. These builds take around an hour and I'd strongly prefer not to add any more.

**Comment by CusiniM** [comment]
yeah, you are right. It would make the travis tests much longer. Alternatively, couldn't we add just a debug build on lassen to the nightly tests? Just building the code and running the unit tests. It would not prevent merges but we would find out immediately.

**Comment by corbett5** [comment]
I believe @bmhan12 was looking into adding new builds to the nightly tests. I think we should do both.

**Comment by rrsettgast** [comment]
We can just add a debug build to Travis. Things are run in parallel on TravisCI anyways, and the debug build would hypothetically run a lot faster than the release.

**Comment by corbett5** [comment]
There's a limit on the number of jobs running concurrently. But I agree it should be ~2x faster.
