### ISSUE TITLE
[Feature] Blueprint and cell-wise vs. quadrature-point-wise data

### ISSUE THREAD

**Issue by joshua-white** [GEOSX/GEOSX#1249]
The current blueprint output assumes all constitutive data lives quadrature-point-wise, and attempts to average across the second dimension of the data array for output.  We sometimes have data that is one-per-element (like the bulk modulus) and so they are stored as array1Ds.  The averaging function below gets mad when it sees one of these:

`src/coreComponents/managers/Outputs/BlueprintOutput.cpp` at line 275.

I think we just need to expand the logic a little bit to handle both 2D and 1D arrays.

**Comment by corbett5** [comment]
@joshua-white did you just try this out? Either way, nice find!

**Comment by corbett5** [comment]
Also it assumes that all constitutive data is stored as `NUM_ELEMENTS, NUM_QUADRATURE, ...` so if you have a vector field stored on the quadrature points after averaging it will be output as `NUM_ELEMENTS, 3`.

**Comment by corbett5** [comment]
@joshua-white do you have an xml I can use as a test?
