### ISSUE TITLE
Third Party Libraries Compilation Issue: ../binutils/2.32-GCCcore-8.3.0/bin/ld.gold: fatal error: ../OpenMPI/4.0.3-GCC-8.3.0-2.32/lib: pread failed: Is a directory

### ISSUE THREAD

**Issue by omeralpak** [GEOSX/GEOSX#1256]
Dear Sir/Lady:

I am tying to compile GEOSX. Using the host configuration template you have provided, I have designed one for my system. Please kindly see the below:

# file: hougdc_alt.cmake

# detect host and name the configuration file
site_name(HOST_NAME)
set(CONFIG_NAME "hougdc_alt" CACHE PATH "")
message( "CONFIG_NAME = ${CONFIG_NAME}" )

# set paths to C, C++, and Fortran compilers. Note that while GEOSX does not contain any Fortran code,
# some of the third-party libraries do contain Fortran code. Thus a Fortran compiler must be specified.
set(CMAKE_C_COMPILER "/glb/data/hpcrnd/easybuild/PRODUCTION/software/rhel/7/GCCcore/8.3.0/bin/gcc" CACHE PATH "")
set(CMAKE_CXX_COMPILER "/glb/data/hpcrnd/easybuild/PRODUCTION/software/rhel/7/GCCcore/8.3.0/bin/g++" CACHE PATH "")
set(CMAKE_Fortran_COMPILER "/glb/data/hpcrnd/easybuild/PRODUCTION/software/rhel/7/GCCcore/8.3.0/bin/gfortran" CACHE PATH "")
set(ENABLE_FORTRAN OFF CACHE BOOL "" FORCE)

# enable MPI and set paths to compilers and executable.
# Note that the MPI compilers are wrappers around standard serial compilers.
# Therefore, the MPI compilers must wrap the appropriate serial compilers specified
# in CMAKE_C_COMPILER, CMAKE_CXX_COMPILER, and CMAKE_Fortran_COMPILER.
set(ENABLE_MPI ON CACHE PATH "")
set(MPI_C_COMPILER "/glb/data/hpcrnd/easybuild/PRODUCTION/software/rhel/7/OpenMPI/4.0.3-GCC-8.3.0-2.32/bin/mpicc" CACHE PATH "")
set(MPI_CXX_COMPILER "/glb/data/hpcrnd/easybuild/PRODUCTION/software/rhel/7/OpenMPI/4.0.3-GCC-8.3.0-2.32/bin/mpicxx" CACHE PATH "")
set(MPI_Fortran_COMPILER "/glb/data/hpcrnd/easybuild/PRODUCTION/software/rhel/7/OpenMPI/4.0.3-GCC-8.3.0-2.32/bin/mpifort" CACHE PATH "")
set(MPIEXEC "/glb/data/hpcrnd/easybuild/PRODUCTION/software/rhel/7/OpenMPI/4.0.3-GCC-8.3.0-2.32/bin/mpirun" CACHE PATH "")

# disable CUDA and OpenMP
set(CUDA_ENABLED "OFF" CACHE PATH "" FORCE)
set(ENABLE_OPENMP "OFF" CACHE PATH "" FORCE)

# enable PAMELA and PVTPackage
set(ENABLE_PAMELA ON CACHE BOOL "" FORCE)
set(ENABLE_PVTPackage ON CACHE BOOL "" FORCE)

# enable tests
set(ENABLE_GTEST_DEATH_TESTS ON CACHE BOOL "" FORCE )

I am loading the following modules for my RHEL 7 system:

module load git/2.27.0
module load git-lfs/2.11.0
module load CMake/3.17.0
module load GCC/8.3.0-2.32
module load OpenMPI/4.0.3-GCC-8.3.0-2.32
module load Python/2.7.9

My Linux version is:
Linux 3.10.0-1160.2.2.el7.x86_64 x86_64

I am almost successful with the compilation but I am running into an issue and I was not able to find much information in the 
web. 
...
...
95%] Built target fparser
Scanning dependencies of target tpl
[ 95%] Building CXX object CMakeFiles/tpl.dir/tpl.cpp.o
[ 96%] Linking CXX executable bin/tpl
[ 96%] Built target tpl
Scanning dependencies of target gtest
[ 96%] Building CXX object blt/thirdparty_builtin/googletest-master-2018-02-01/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 97%] Linking CXX static library ../../../../lib/libgtest.a
[ 97%] Built target gtest
Scanning dependencies of target gtest_main
[ 97%] Building CXX object blt/thirdparty_builtin/googletest-master-2018-02-01/googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 98%] Linking CXX static library ../../../../lib/libgtest_main.a
[ 98%] Built target gtest_main
Scanning dependencies of target blt_mpi_smoke
[ 99%] Building CXX object blt/tests/smoke/CMakeFiles/blt_mpi_smoke.dir/blt_mpi_smoke.cpp.o
[ 99%] Linking CXX executable ../../../tests/blt_mpi_smoke
/glb/data/hpcrnd/easybuild/PRODUCTION/software/rhel/7/binutils/2.32-GCCcore-8.3.0/bin/ld.gold: fatal error: /glb/data/hpcrnd/easybuild/PRODUCTION/software/rhel/7/OpenMPI/4.0.3-GCC-8.3.0-2.32/lib: pread failed: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [tests/blt_mpi_smoke] Error 1
make[1]: *** [blt/tests/smoke/CMakeFiles/blt_mpi_smoke.dir/all] Error 2
make: *** [all] Error 2

I have tried a different (older) version of GCC (GCCcore/7.3.0) and OpenMPI (OpenMPI/3.1.1-GCC-4.9.3). I am running into exactly the same issue. 

Since I am stuck, I would like to respectfully request your comments/support, if you have seen this before or know about it.

Sincerely,
Omer

**Comment by TotoGaz** [comment]
Hi @omeralpak not too many people to answer during this period...
Do you confirm that you can build all the TPLs? (`fparser`, `trilinos`,...) and that you are blocked at the very end of the process?

**Comment by omeralpak** [comment]
Hi @TotoGaz, Yes. I confirm that I am blocked at the very end of the process.

**Comment by omeralpak** [comment]
Hi @TotoGaz , This exactly where things are going wrong (when I call make again):
[usoal0@houcy1-n-w10288 build-hougdc_alt-release]$ make
[  5%] Built target metis
[  9%] Built target suitesparse
[ 13%] Built target parmetis
[ 18%] Built target superlu_dist
[ 23%] Built target hypre
[ 27%] Built target hdf5
[ 32%] Built target conduit
[ 37%] Built target axom
[ 41%] Built target doxygen
[ 45%] Built target astyle
[ 49%] Built target uncrustify
[ 54%] Built target silo
[ 58%] Built target raja
[ 62%] Built target adiak
[ 66%] Built target chai
[ 71%] Built target caliper
[ 75%] Built target mathpresso
[ 80%] Built target pugixml
[ 85%] Built target trilinos
[ 90%] Built target vtk
[ 95%] Built target fparser
[ 96%] Built target tpl
[ 97%] Built target gtest
[ 98%] Built target gtest_main
[ 98%] Linking CXX executable ../../../tests/blt_mpi_smoke
/glb/data/hpcrnd/easybuild/PRODUCTION/software/rhel/7/binutils/2.32-GCCcore-8.3.0/bin/ld.gold: fatal error: /glb/data/hpcrnd/easybuild/PRODUCTION/software/rhel/7/OpenMPI/4.0.3-GCC-8.3.0-2.32/lib: pread failed: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [tests/blt_mpi_smoke] Error 1
make[1]: *** [blt/tests/smoke/CMakeFiles/blt_mpi_smoke.dir/all] Error 2
make: *** [all] Error 2

**Comment by TotoGaz** [comment]
Hmm, this is really weird.
Do you confirm that these tools usually work for other software (I believe it should, but...).

This `tpl.cpp` is a  build/compilation `cmake` trick that will be removed after we use `spack` (see https://spack.io/).
_As a workaround before a solution is found_ I think that you should be able to continue building GEOSX since all your TPLs are built (`tpl` is the very last dummy step).

Our `travis-ci` CI/CD compiles against `openmpi 4` on MacOSX and `gcc` on multiple platforms (not together alongside though, but...)

Do you think it may be a `binutils` issue (I mean an error/option on our side revealed by a different version of the `binutils`)? Do you have any alternate version to test?

**Comment by omeralpak** [comment]
Hello @TotoGaz, 

Thank you very much indeed for the helpful comments.

I have worked with a subset of these tools before (especially trilinos) and I confirm they work for other software but I cannot confirm this particular installation. I will investigate this item. Perhaps, before the latter, I will investigate continuing building GEOSX and see whether I will succeed or not.  

I will get in touch with our Linux administrator to investigate/answer your question about binutils. I will keep you informed.

**Comment by omeralpak** [comment]
Hello @TotoGaz, 

While the issue remains to be there, the workaround indeed works fine. Thank you very much indeed for the help.

**Comment by TotoGaz** [comment]
Hi @corbett5 in https://github.com/GEOSX/GEOSX/issues/1256#issuecomment-751894205 I said that `tpl.cpp` was a trick that was going to disappear with `spack`.

Am I correct?

If so I may want to close the issue because I do not think it's worth spending time on a problem that will be void resolved!

**Comment by corbett5** [comment]
@omeralpak so you were indeed able to compile GEOSX? I would have guessed that you'd receive the same error when building GEOSX as `tpl.cpp`, but I guess not.

@TotoGaz yup, it's going away.

**Comment by omeralpak** [comment]
@corbett5  and @TotoGaz, Yes. I confirm. It seems I can still compile GEOSX. I think, issue can be closed.

**Comment by TotoGaz** [comment]
@omeralpak Patch https://github.com/GEOSX/thirdPartyLibs/pull/148 should probably fix your problem for good. If some day you have the opportunity to test. 😉

**Comment by omeralpak** [comment]
Hello Thomas,

I will try a clean installation and let you know probably in 2 weeks or so.

Kind Regards,
Omer
