### ISSUE TITLE
[Cleanup] homogenize style of indexing, penthesis, bracket, etc.

### ISSUE THREAD

**Issue by sytuannguyen** [GEOSX/GEOSX#1279]
**Describe the issue**

Both indexing styles [i] and [ i ] exist makes the code less consistent.

e.g.

real64 dNdX[ numNodesPerElem ][ 3 ];
real64 strainInc[6] = {0};

Similarly, the use of space inside parenthesis and bracket is not homogeneous such as:

 (voila), ( voila ), ( voila), (voila ), {voila}, { voila }, etc.

**Proposed cleanup**

I propose to homogenize this by systematically removing the space. 
This option is consistent with other stuffs such as #include that does not accept the space in <>, cmake that does not accept the space in {}, .gitmodules that does not accept the space in [].  

**Additional context**

**Comment by TotoGaz** [comment]
Hello @sytuannguyen 
Our code style is done by `uncrustify` so far.
If we add some modification to provide, that would probably be through this tool for the moment.
Because your PR will not pass the unit tests which check code style (to some extent).

**Comment by sytuannguyen** [comment]
I just check uncrustify, yes it is for this but it seems not be applied yet.
