### ISSUE TITLE
Git submodule update not working for PTP

### ISSUE THREAD

**Issue by sytuannguyen** [GEOSX/GEOSX#1290]
**Describe the bug**
Cannot update GEOSX_PTP by: git submodule update

**To Reproduce**

1. Go to local GEOSX source code
2. type: git submodule update
3. Goto src/coreComponents/physicsSolvers/GEOSX_PTP/ParallelTopologyChange.cpp
4. The function names are not changed with the correction of camelCase rule as we can see on github

**Expected behavior**
The correction of function names with respect to the camelCase rule is updated for the build
**Screenshots**

**Platform (please complete the following information):**
- Machine [Pangea] 

**Additional context**

Finally I needed to copy manually the file in GEOSX_PTP from github to my local source code.

**Comment by TotoGaz** [comment]
Maybe (probably) a proxy issue?

**Comment by sytuannguyen** [comment]
It is resolved now by removing the folder GEOSX_PTP then rerun git module update.

**Comment by TotoGaz** [comment]
Great news!
