### ISSUE TITLE
[Feature] Provide functionality for EDFM working with wells

### ISSUE THREAD

**Issue by ishovkun** [GEOSX/GEOSX#1302]
As for now, the EDFM FVM code only allows static source/sink terms assigned within bounding boxes. If wells are assigned, GEOSX fails. 

My test case is as follows: https://pastebin.com/mELNpfPq
Note: wells do not intersect fractures in this setup; this would probably be a separate issue.

The GEOSX log is as follows: https://pastebin.com/q6tp7RwK

The issue apparently arises due to the mishandling of the stencils.

**Comment by francoishamon** [comment]
Hello @ishovkun,
Yes, I can have a look at this problem and make the wells work with fractures. This is a combination that we have never tried before. The first thing to double check is whether the Jacobian matrix is set up correctly when you have fractures and wells. I don't think it is the case right now, and I guess this is causing the error that you reported. I will get back to you.

**Comment by CusiniM** [comment]
@francoishamon, either @ishovkun or myself can also fix this. We just wanted to check with you to see what you thought the problem might be. Having a quick look at the code yesterday I think that the sparsity pattern needs to be changed and as you mentioned the sizes might be wrong.

**Comment by francoishamon** [comment]
Here is a slightly updated xml (only modification: I removed `wellControls3` since there are only two wells). 

<details>
<summary> the updated xml </summary>
<?xml version="1.0" ?>
 
<Problem>
  <Solvers>
    <SinglePhaseReservoir
      name="reservoirSystem"
      flowSolverName="singlePhaseFlow"
      wellSolverName="singlePhaseWell"
      logLevel="1"
      targetRegions="{ MatrixRegion, wellRegion1, wellRegion2, Fracture }">
      <NonlinearSolverParameters
        lineSearchAction="None"
        newtonMaxIter="40"/>
      <LinearSolverParameters
        solverType="direct"
        directParallel="0"
        logLevel="0"/>
    </SinglePhaseReservoir>
 
    <SinglePhaseFVM
      name="singlePhaseFlow"
      logLevel="1"
      discretization="singlePhaseTPFA"
      fluidNames="{ water }"
      solidNames="{ rock }"
      targetRegions="{ MatrixRegion, Fracture }"/>
 
    <SinglePhaseWell
      name="singlePhaseWell"
      logLevel="1"
      fluidNames="{ water }"
      targetRegions="{ wellRegion1, wellRegion2 }">
      <WellControls
        name="wellControls1"
        type="producer"
        control="BHP"
        targetBHP="5e5"
        targetRate="1e-1"/>
      <WellControls
        name="wellControls2"
        type="injector"
        control="liquidRate"
        targetBHP="1e8"
        targetRate="1e-2"/>
    </SinglePhaseWell>
 
    <EmbeddedSurfaceGenerator
      name="SurfaceGenerator"
      logLevel="1"
      solidMaterialNames="{ rock }"
      targetRegions="{ MatrixRegion, Fracture }"
      fractureRegion="Fracture"/>
 
  </Solvers>
 
  <Mesh>
    <InternalMesh
      name="mesh1"
      elementTypes="{ C3D8 }"
      xCoords="{ 0, 15 }"
      yCoords="{ 0, 15 }"
      zCoords="{ 0, 1 }"
      nx="{ 20 }"
      ny="{ 20 }"
      nz="{ 1 }"
      cellBlockNames="{ cb1 }"/>
 
    <InternalWell
      name="well_producer1"
      wellRegionName="wellRegion1"
      wellControlsName="wellControls1"
      meshName="mesh1"
      polylineNodeCoords="{ { 0.5, 0.5, 0.5 },
                            { 7.5, 0.5, 0.35 },
                            { 14.5, 0.5, 0.2 } }"
      polylineSegmentConn="{ { 0, 1 },
                             { 1, 2 } }"
      radius="0.1"
      numElementsPerSegment="20">
      <Perforation
        name="producer1_perf1"
        distanceFromHead="14"
        transmissibility="1.02e-14"/>
      <Perforation
        name="producer1_perf2"
        distanceFromHead="11"
        transmissibility="1.02e-14"/>
      <Perforation
        name="producer1_perf3"
        distanceFromHead="8"
        transmissibility="1.02e-14"/>
    </InternalWell>
 
    <InternalWell
      name="well_producer2"
      wellRegionName="wellRegion2"
      wellControlsName="wellControls2"
      meshName="mesh1"
      polylineNodeCoords="{ { 14.5, 14.5, 0.5 },
                            { 7.5, 14.5, 0.35 },
                            { 0.5, 14.5, 0.2 } }"
      polylineSegmentConn="{ { 0, 1 },
                             { 1, 2 } }"
      radius="0.1"
      numElementsPerSegment="17">
      <Perforation
        name="producer2_perf1"
        distanceFromHead="14."/>
      <Perforation
        name="producer2_perf2"
        distanceFromHead="10"/>
      <Perforation
        name="producer2_perf3"
        distanceFromHead="6"/>
    </InternalWell>
 
  </Mesh>
 
  <Geometry>
    <BoundedPlane
      name="FracturePlane"
      normal="1, 0, 0"
      origin="10, 10, 0.5"
      lengthVector="0, 15, 0"
      widthVector="0, 0, 15"
      dimensions="{ 100, 100 }"/>
  </Geometry>
 
  <Events
    maxTime="1e5">
 
    <SoloEvent
      name="preFracture"
      target="/Solvers/SurfaceGenerator"/>
 
    <PeriodicEvent
      name="solverApplications"
      forceDt="1e4"
      target="/Solvers/reservoirSystem"/>
 
    <PeriodicEvent
      name="outputs"
      cycleFrequency="1"
      targetExactTimestep="1"
      target="/Outputs/vtkOutput"/>
  </Events>
 
  <NumericalMethods>
 
    <FiniteVolume>
      <TwoPointFluxApproximation
        name="singlePhaseTPFA"
        fieldName="pressure"
        coefficientName="permeability"/>
    </FiniteVolume>
 
  </NumericalMethods>
 
  <ElementRegions>
    <CellElementRegion
      name="MatrixRegion"
      cellBlocks="{ cb1 }"
      materialList="{ water, rock }"/>
 
    <WellElementRegion
      name="wellRegion1"
      materialList="{ water }"/>
 
    <WellElementRegion
      name="wellRegion2"
      materialList="{ water }"/>
 
    <SurfaceElementRegion
      name="Fracture"
      defaultAperture = "1e-3"
      materialList="{ water, rock }"
      subRegionType="embeddedElement"/>
 
  </ElementRegions>
 
  <Constitutive>
    <CompressibleSinglePhaseFluid
      name="water"
      defaultDensity="1000"
      defaultViscosity="0.001"
      referencePressure="0.0"
      referenceDensity="1000"
      compressibility="0"
      referenceViscosity="0.005"
      viscosibility="0.0"/>
 
    <PoreVolumeCompressibleSolid
      name="rock"
      referencePressure="0.0"
      compressibility="1e-9"/>
  </Constitutive>
 
  <FieldSpecifications>
    <FieldSpecification
      name="permx"
      component="0"
      initialCondition="1"
      setNames="{ all }"
      objectPath="ElementRegions/MatrixRegion/cb1"
      fieldName="permeability"
      scale="2.0e-16"/>
 
    <FieldSpecification
      name="permy"
      component="1"
      initialCondition="1"
      setNames="{ all }"
      objectPath="ElementRegions/MatrixRegion/cb1"
      fieldName="permeability"
      scale="2.0e-16"/>
 
    <FieldSpecification
      name="permz"
      component="2"
      initialCondition="1"
      setNames="{ all }"
      objectPath="ElementRegions/MatrixRegion/cb1"
      fieldName="permeability"
      scale="2.0e-16"/>
 
    <FieldSpecification
      name="referencePorosity"
      initialCondition="1"
      setNames="{ all }"
      objectPath="ElementRegions/MatrixRegion/cb1"
      fieldName="referencePorosity"
      scale="0.05"/>
 
    <FieldSpecification
      name="initialPressure"
      initialCondition="1"
      setNames="{ all }"
      objectPath="ElementRegions/MatrixRegion/cb1"
      fieldName="pressure"
      scale="5e6"/>
  </FieldSpecifications>
 
  <Functions>
    <TableFunction
      name="timeFunction"
      inputVarNames="{ time }"
      coordinates="{ 1.0, 2.0, 6e4 }"
      values="{ 1.0, 2.0, 2.0 }"/>
  </Functions>
 
  <Outputs>
    <VTK
      name="vtkOutput"
      plotFileRoot="fractureMatrixFlow"
      plotLevel="2"
      writeBinaryData="0"/>
  </Outputs>
</Problem>
</details>
