### ISSUE TITLE
[Bug] make failed

### ISSUE THREAD

**Issue by Ron-Wang** [GEOSX/GEOSX#1326]
@rrsettgast 
Thanks for your updating so much! 
I pull the lastest version, but I met some mistakes during making as following: 
"
/GEOSX/src/coreComponents/managers/initialization.cpp:360:3: error: ‘finalizeCaliper’ was not declared in this scope; did you mean ‘finalizeLogger’?
  360 |   finalizeCaliper();
      |   ^~~~~~~~~~~~~~~
      |   finalizeLogger
"

**Comment by CusiniM** [comment]
I have fixed this in PR #1229 which is ready to be merged. 

if building without caliper you need to define that function.

**Comment by Ron-Wang** [comment]
> I have fixed this in PR #1229 which is ready to be merged.

thanks a lot! I cheacked the makefile and found that I didn't add the CALIPER_DIR. Now, I have finied the installation. Thanks a lot!
I wonder if I want to add some code (mainly about Explicit Coupled Flow and Mechanics Solver), can I build a new branch and finally pull resquest. 
Thanks a lot for your reply!!
