### ISSUE TITLE
Paraview crashes when opening the pvd file with multiple regions.

### ISSUE THREAD

**Issue by CusiniM** [GEOSX/GEOSX#1355]
Every time I try to open the `pvd` file with 2 regions (a `cellElementRegion` one and  a `SurfaceElementRegion`) paraview crashes. If I open the single `vtu` files separately it works fine.

**Comment by joshua-white** [comment]
Ideas

- Check if region size is changing with timestep
- Rollback prior to Sergey's merge (or even further)
- Send to VTK mailing list
- Try to reproduce with different subregion types

**Comment by TotoGaz** [comment]
Maybe testing with another tool (like `pyvtk`, even if it's still VTK...).
You may get additional information instead of a raw crash.

**Comment by francoishamon** [comment]
I just checked in `develop`, and for the simulations with both `CellElementRegion` et `WellElementRegion`, opening the `pvd` file in Paraview is still working fine. I can view each region separately, or all of them together. The region sizes are constant during the simulation. I use Paraview on Quartz.

![screenshot_matteo](https://user-images.githubusercontent.com/20196406/111706571-bf403b00-87ff-11eb-913c-1d34f8d85dd5.png)

**Comment by CusiniM** [comment]
Ok, I have found out what the issue is. I was assigning a material to the `FractureRegion` which only has 1 integration point. As a consequence paraview crashes because the two regions have the same property but with different sizes (the stress is defined at each integration point). The fix is to just not assign a material to the fracture which does not need one. However, it may be an issue later one if we plan on using a single constitutive model for regions which use different integration rules.

**Comment by CusiniM** [comment]
Ok, I have found out what the issue is. I was assigning a material to the `FractureRegion` which only has 1 integration point. As a consequence paraview crashes because the two regions have the same property but with different sizes (the stress is defined at each integration point). The fix is to just not assign a material to the fracture which does not need one. However, it may be an issue later one if we plan on using a single constitutive model for regions which use different integration rules.
