### ISSUE TITLE
Homogenize input source flux to avoid confuse

### ISSUE THREAD

**Issue by sytuannguyen** [GEOSX/GEOSX#1369]
**What is the requested feature?**
Homogenize input source flux to avoid confuse

**Is your request related to a specific problem?**
When applying source flux boundary condition, I realized that the scale value is mass rate, not volume rate. This is quite easy to be confused. Also it makes GEOSX less consistent in term of flux BC. Indeed, when checking the well solver, I found that the flux BC is a volumetric rate not a mass rate as SourceFLux BC. 

Beside, in operational applications, volumetric rate is usually given, not the mass rate.

**Describe the solution you'd like**
Use volume rate for SourceFlux BC

**Describe alternatives you've considered**

**Additional context**

**Comment by francoishamon** [comment]
To specify a volumetric rate of injection, we recommend using true wells, which have the necessary information (constitutive models and surface conditions) to do a proper conversion from volume rate to mass rate. Therefore, I am closing this issue
