### ISSUE TITLE
Separate native multiphase constitutive models and PVTPackage models.

### ISSUE THREAD

**Issue by rrsettgast** [GEOSX/GEOSX#1388]
This is not correct anymore, we have multiphase constitutive models that run natively in GEOSX, without `PVTPackage`. Perhaps constitutive dispatch needs to be fixed to avoid `PVTPackage`-dependent models when it's not enabled. We can do it in a follow up.

_Originally posted by @klevzoff in https://github.com/GEOSX/GEOSX/pull/1352#r611122429_

**Comment by klevzoff** [comment]
Resolved in https://github.com/GEOSX/GEOSX/pull/1463
