### ISSUE TITLE
Investigate VTK usage in Visit

### ISSUE THREAD

**Issue by rrsettgast** [GEOSX/GEOSX#1402]
Determine if Visit is able to seamlessly read/work with vtk flies. 

requires name changes in vtk?

Potentially requires the creation of a top level file for vtk/visit?

Potentially remove silo :) 

Silo users please try out vtk output in visit. 

- [ ] @cssherman 
- [ ] @jhuang2601 
- [ ] @sytuannguyen

**Comment by cssherman** [comment]
@rrsettgast - The smart file grouping in Visit seems to work with our existing vtk file names.  The only major piece of information that visit cannot find in the files is the cycle/timestamp information (these only appear to be written to the paraview-specific file).  I was able to find some instructions for adding this to the files on the visit user forums.  In each of the rank-specific files (e.g.: vtkOutput/0.0000000/0_Region.vtu), we need to have the following information:

```xml
<UnstructuredGrid>
    <FieldData>
      <DataArray type="Float32" Name="TIME" NumberOfTuples="1" format="ascii">
       10.543
      </DataArray>
      <DataArray type="Int32" Name="CYCLE" NumberOfTuples="1" format="ascii">
       42
      </DataArray>
    </FieldData>
    ...
</UnstructuredGrid>
```

This should only take a couple of new lines to add...

**Comment by rrsettgast** [comment]
@cssherman That seems straightforward. Can you give it a shot?

**Comment by jhuang2601** [comment]
@rrsettgast I've tested this capability by running the Sneddon problem with embedded fracture. First of all, Visit can now load and visualize the vtk files, which is promising. As @cssherman mentioned, the time series of the output cannot be handled, which requires some additional work. As for the output variables, such as stress/displacement field, their components are not named and output properly. 
![image](https://user-images.githubusercontent.com/53012159/125338143-7152c400-e315-11eb-8d70-8568d5dd2122.png)

**Comment by cssherman** [comment]
@jhuang2601 @rrsettgast - There may be a quick fix for the time-series issue:

Visit is able to properly load the database for problems with parallel output enabled, due to the different naming scheme.  For serial outputs, we only output the file for the individual rank which has the ".000" suffix that confuses visit's name parser.  We could consider changing the output name, or always do the extra work to write out the parallel-format files.

**Comment by cssherman** [comment]
Looking further into the issue of visit + vtk, it seems like the database grouping feature does not like our file names: `time.decimal.vtm`.  Visit prefers this format: `header_integer.extension'.  @rrsettgast - Are there any issues with using cycle instead of time in the file names, like we currently do with silo?

https://github.com/GEOSX/GEOSX/blob/33f16efd83eaf66c0d6eaedf70d4d41a158761b8/src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp#L770-L773

**Comment by rrsettgast** [comment]
> Looking further into the issue of visit + vtk, it seems like the database grouping feature does not like our file names: `time.decimal.vtm`.  Visit prefers this format: `header_integer.extension'.  @rrsettgast - Are there any issues with using cycle instead of time in the file names, like we currently do with silo?
> 
> 
> 
> https://github.com/GEOSX/GEOSX/blob/33f16efd83eaf66c0d6eaedf70d4d41a158761b8/src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp#L770-L773

I am surprised that we are using time in the filename. That seems problematic? Cycle_subcycle would be better?

**Comment by cssherman** [comment]
@rrsettgast - agreed.  Using the floating point time certainly doesn't scale for varying time scales.  In order to avoid confusing visit, we'd either need to drop the underscore (we do this with silo) or move the subcycle up to the header

**Comment by cssherman** [comment]
There seem to be a couple of additional issues with the vtk files in visit:

1) After loading the vtm file, only the first region (CellElementRegion) shows up in the interface.  This also seems to be the case in Paraview (I am not an expert here and could be missing something), so perhaps something else is wrong?  To illustrate this, I'd recommend looking at one of the hydraulic fracturing examples.   In visit, if these regions are separated into multiple files, then the database correlation feature works just fine to keep the visualization in sync.
2) This is more cosmetic, but we are currently placing all of the values at the root level.  Visit splits variable names on `/` and sorts values into folders.  If we would like to group values on solvers, constitutive models, etc., we could use this to clean up the variable list.
3) We aren't specifying which values correspond to cells/nodes like we do in silo.  If we want to communicate this to users, we could prepend variable names with something like `nodalValues/`

Any thoughts @rrsettgast @klevzoff ?

**Comment by jhuang2601** [comment]
@cssherman @rrsettgast  I've tested one hydraulic fracturing example (`inputFiles/hydraulicFracturing/Sneddon_hydroFrac_benchmark.xml`) with vtk outputs.

- In Paraview, all the regions (not just the CellElementRegion) can be loaded and output variables along fracture surface can be visualized.

![image](https://user-images.githubusercontent.com/53012159/151445709-65e7aee9-a858-435f-8ff9-c92b4fa0f305.png)

- If using Visit, only the first region (CellElementRegion) can be displayed, as mentioned above. Moreover, certain variables associated with this region are invalid and cannot be visualized, such as totalDisplacement. All output variables along fracture surface are missing from this option.

![image](https://user-images.githubusercontent.com/53012159/151446180-218e0465-e583-49ec-9523-f2db5defcc2e.png)

**Comment by cssherman** [comment]
@jhuang2601 - What property are you visualizing on the fracture?  I can get paraview to display only the fracture, but do not have access to specific properties such as aperture.

![image](https://user-images.githubusercontent.com/4932756/151449442-a5e6f07d-14be-423e-9040-11671ef29702.png)

**Comment by jhuang2601** [comment]
@cssherman hydraulicAperture, fracturePerm_permeability, elementAperture can all be visualized for fracture. 
![image](https://user-images.githubusercontent.com/53012159/151450277-68373879-c0cb-4917-8a32-71d9d986d1e6.png)

**Comment by cssherman** [comment]
@jhuang2601 - Oh, I see.  The options show up in the color-by section, but not the properties section.

**Comment by jhuang2601** [comment]
@cssherman The properties section is the place to select and import certain variables, not for visualization.

**Comment by cssherman** [comment]
@rrsettgast (or anyone else interested), I have an open issue in the visit repo disussing the issues with our vtk file (see above).  They've confirmed that visit is currently only reading the first region to generate the metadata, which explains why we can't see certain fracture-based properties.  If you want to chime in on the solution, feel free to do so there

**Comment by rrsettgast** [comment]
@cssherman Has there been any progress on this?

**Comment by cssherman** [comment]
> @cssherman Has there been any progress on this?

I've fully moved to vtk, and have some workarounds to deal with oddities multi-region meshes in visit.  @povolny1 - are you using vtk for your work?

**Comment by povolny1** [comment]
I have a multi-body .vtm hierarchy that's working for me, and I can visualize everything in Paraview but not in VisIt (can only see meshes in VisIt). The VisIt folks were going to work on it but they're waiting for us to finalize the .vtm hierarchy.

**Comment by rrsettgast** [comment]
Great! Thanks!
