### ISSUE TITLE
Some problems of Metis partition

### ISSUE THREAD

**Issue by Ron-Wang** [GEOSX/GEOSX#1408]
With an external mesh file (.msh file),  I use mpirun Geosx.  However, it say there in rank 1 doesn't have some regions. 
I think it's because the mesh has some many regions (26 regions), and some small regions are not in all partitions (ranks).  
I wonder How can I solve this problem?  Thanks a lot!

**Comment by AntoineMazuyer** [comment]
Hi @Ron-Wang, can you please communicate the logs of your simulation ? Thanks !

**Comment by Ron-Wang** [comment]
Thanks! @AntoineMazuyer 
The logs of my simulation are  as follows: 
"
***** ERROR
***** LOCATION: /home/jp/GEOSX/GEOSX/src/coreComponents/mesh/CellElementRegion.cpp:51
***** Controlling expression (should be false): source == nullptr
***** Rank 11: Cell block named Region1_TETRA does not exist

** StackTrace of 5 frames **
Frame 0: geosx::ElementRegionManager::GenerateMesh(geosx::dataRepository::Group*) 
Frame 1: geosx::ProblemManager::GenerateMesh() 
Frame 2: geosx::ProblemManager::ProblemSetup() 
Frame 3: main 
Frame 4: __libc_start_main 
Frame 5: _start 
=====
"
I use the tetra element type, and I think  some small regions are not in all partitions (ranks) when mpirun. For example, the partition of "Rank 11" doesn't have the "Region1_TETRA".

**Comment by wrtobin** [comment]
Please provide any input decks and meshes.

Documenting that this may be related to #841 and if/when that is resolved this should be checked.

**Comment by TotoGaz** [comment]
The `msh` format is no more supported since we no more use `PAMELA` but `vtk` instead.
