### ISSUE TITLE
[Bug] Compilation broken when GEOSX_BUILD_OBJ_LIBS=OFF

### ISSUE THREAD

**Issue by klevzoff** [GEOSX/GEOSX#1421]
**Describe the bug**
I tried turning object libraries off (since they slow down a full build considerably for me) and got an early build error.

**To Reproduce**
1. Add `set(GEOSX_BUILD_OBJ_LIBS OFF CACHE BOOL "")` to your host-config
2. Configure a clean build
3. try `make common`
4. Observe the error:
```
[ 50%] Building CXX object coreComponents/common/CMakeFiles/common.dir/initializeEnvironment.cpp.o
In file included from /home/klevtsov/work/GEOSX-develop/src/coreComponents/common/initializeEnvironment.cpp:15:
/home/klevtsov/work/GEOSX-develop/src/coreComponents/common/initializeEnvironment.hpp:24:10: fatal error: adiak.hpp: No such file or directory
 #include <adiak.hpp>
          ^~~~~~~~~~~
compilation terminated.

```

**Expected behavior**
Should build with object libraries disabled.

**Platform (please complete the following information):**
- Machine: my laptop (ubuntu 20.04)
- Compiler: gcc-8.4.0 (but it's compiler independent I think)
- GEOSX version: most recent `develop` (`4ad3852`)

**Additional context**
Here's what compilation line for `initializeEnvironment.cpp` looks like with object libraries **enabled** (I isolated just the includes)
```
-I/home/klevtsov/work/GEOSX-develop/build-gcc8-debug/include
-I/home/klevtsov/work/thirdPartyLibs/install-gcc8-debug/pugixml/include
-I/home/klevtsov/work/thirdPartyLibs/install-gcc8-debug/conduit/include
-I/home/klevtsov/work/thirdPartyLibs/install-gcc8-debug/conduit/include/conduit
-I/home/klevtsov/work/GEOSX-develop/src/coreComponents
-isystem /home/klevtsov/work/thirdPartyLibs/install-gcc8-debug/raja/include
-isystem /home/klevtsov/work/thirdPartyLibs/install-gcc8-debug/chai/include
-isystem /home/klevtsov/work/thirdPartyLibs/install-gcc8-debug/caliper/include
-isystem /opt/openmpi/openmpi-4.1.0-gcc-8.4.0/include
-isystem /home/klevtsov/work/thirdPartyLibs/install-gcc8-debug/adiak/include 
```
and **disabled**
```
-I/home/klevtsov/work/GEOSX-develop/build-gcc8-debug/include 
-I/home/klevtsov/work/GEOSX-develop/src/coreComponents 
-isystem /home/klevtsov/work/thirdPartyLibs/install-gcc8-debug/raja/include 
-isystem /home/klevtsov/work/thirdPartyLibs/install-gcc8-debug/chai/include 
-isystem /home/klevtsov/work/thirdPartyLibs/install-gcc8-debug/pugixml/include 
-isystem /home/klevtsov/work/thirdPartyLibs/install-gcc8-debug/conduit/include 
-isystem /home/klevtsov/work/thirdPartyLibs/install-gcc8-debug/conduit/include/conduit 
-isystem /home/klevtsov/work/thirdPartyLibs/install-gcc8-debug/hdf5/include 
-isystem /opt/openmpi/openmpi-4.1.0-gcc-8.4.0/include 
```

I've confirmed that dependency list of `common` is identical in both cases (and includes both `caliper` and `adiak`), it's just not adding the includes correctly for some reason.

**Comment by klevzoff** [comment]
If anyone could independently confirm this issue on a different system, that would be great.

**Comment by bmhan12** [comment]
@klevzoff Can confirm this issue on quartz and lassen. Working on a PR to fix this.
