### ISSUE TITLE
[Bug] Perforation transmissibility and perforation moving in parallel run

### ISSUE THREAD

**Issue by wdmhouston** [GEOSX/GEOSX#1469]
Please find the attached test dataset with one horizontal well(3 perforations)
[test_hwells.zip](https://github.com/GEOSX/GEOSX/files/6713585/test_hwells.zip)

test1: non parallel run geosx -i test_hwells1.xml 
![image](https://user-images.githubusercontent.com/19333848/123370583-a30e1180-d545-11eb-98c4-e56f681db3de.png)
![image](https://user-images.githubusercontent.com/19333848/123370641-c3d66700-d545-11eb-982d-011bac3ab3c6.png)
CO2 is not supposed to be injected through perforation 2 because second perforation has transmissiblity=0

test2: same dataset with transmissiblity =0 for perforation 2  and run it in parallel:  mpirun -np 9 geosx -i test_hwells1.xml -x 3 -y 3 -z 1
paraview reports error in calculation and no results found. It seems the "transmissiblity =0" crashed vtk results in parallel run mode

test3: remove transmissibility  from perforation 2 and run it in parallel:  mpirun -np 9 geosx -i test_hwells1.xml -x 3 -y 3 -z 1
![image](https://user-images.githubusercontent.com/19333848/123370956-6393f500-d546-11eb-9202-8de9c2683c77.png)
Geosx log shows
"Moving perforation #1 of well wellInjector1 from { 5025, 4824, 28.82 } to { 5025, 5024, 28.82 } to make sure that no well element is shared between two MPI ranks
Moving perforation #2 of well wellInjector1 from { 5025, 4624, 28.82 } to { 5025, 5024, 28.82 } to make sure that no well element is shared between two MPI ranks
".
and only one perforation left in reservoir
![image](https://user-images.githubusercontent.com/19333848/123371375-4a3f7880-d547-11eb-9113-ff5522a09f36.png)

This is an unexpected behavior. Perforations are not supposed to be moved(merged?) because the whole well doesn't cross partitions.
![image](https://user-images.githubusercontent.com/19333848/123371243-f7fe5780-d546-11eb-88b2-8bb9c647cb31.png)

Please review and fix it in future release if it's confirmed as bug.

**Comment by francoishamon** [comment]
Hello @wdmhouston ,

See #1472 

Regarding the first issue, if you set the transmissibility to zero, GEOSX is silently recomputing the transmissibility using the Peaceman formula. With the PR listed above, GEOSX will output the following warning:
```
Warning! A perforation is defined with a zero transmissibility!                                                                                                                                                
The simulation is going to proceed with this zero transmissibility,                                                                                                                                             
but a better strategy to shut down a perforation is to remove to <Perforation> block from the XML
```
and proceed with the simulation.

Regarding the second issue, we do not allow a well element to own two perforations, but the error message was cryptic, you are definitely right. I replaced it with
```
The GEOSX wells currently have the following limitation in parallel:                                                                                                                                            
We cannot allow an element of the well mesh to have two or more perforations associated with it.                                                                                                                
So, in the present simulation, perforation #2 of well wellInjector1 is moved from { 5025, 4624, 28.82 } to { 5025, 5024, 28.82 } to make sure that no element of the well mesh has two perforations associated \
with it.                                                                                                                                                                                                        
To circumvent this issue, please increase the value of "numElementsPerSegment" that controls the number of (uniformly distributed) well mesh elements per segment of the well polyline.                         
Our recommendation is to choose "numElementsPerSegment" such that each well mesh element has at most one perforation.
```
As the new error message suggests, your simulation will work if you increase the number of elements per segment. I tried your input file with 
```
numElementsPerSegment="3"
```
to have one well element per perforation in the last segment of the well and it worked fine in parallel with your parallel setup.
