### ISSUE TITLE
[Bug] time-step doesn't increase in current develop branch 

### ISSUE THREAD

**Issue by wdmhouston** [GEOSX/GEOSX#1477]
Tried the "develop" branch today with a test dataset, and find the time-step doesn't increase. 
I was expecting the dt value increases over time when newton solver converged, but it doesn't change(dt=2.592e+06s). 
![image](https://user-images.githubusercontent.com/19333848/124056686-caecf180-d9eb-11eb-973b-2fd5f0c69f73.png)

please review and fix.

**Comment by francoishamon** [comment]
Hello @wdmhouston, can you please post your xml file so we can help? You may have some periodic events (outputs?) that prevent the time step from increasing.

**Comment by wdmhouston** [comment]
Francois,
    Thanks for the reply. You're right, I forgot to change coupledFlowAndWells maxEventDt in my new test case. I'll close this ticket.
