### ISSUE TITLE
Error with compilation

### ISSUE THREAD

**Issue by m-nsor** [GEOSX/GEOSX#1502]
This is the error that I got

ETIS_INC="/Users/mike/Desktop/Git/codes/thirdPartyLibs/install-mk-host-release/metis/include" CUDA=no library && cd ..
SuiteSparse_config.c:12:10: fatal error: 'math.h' file not found
#include <math.h>
         ^~~~~~~~
1 error generated.
make[3]: *** [SuiteSparse_config.o] Error 1
/Users/mike/Desktop/Git/codes/thirdPartyLibs/build-mk-host-release/build_suitesparse_for_geosx: line 2: cd: AMD: No such file or directory
/Users/mike/Desktop/Git/codes/thirdPartyLibs/build-mk-host-release/build_suitesparse_for_geosx: line 3: cd: BTF: No such file or directory
/Users/mike/Desktop/Git/codes/thirdPartyLibs/build-mk-host-release/build_suitesparse_for_geosx: line 4: cd: CAMD: No such file or directory
/Users/mike/Desktop/Git/codes/thirdPartyLibs/build-mk-host-release/build_suitesparse_for_geosx: line 5: cd: CCOLAMD: No such file or directory
/Users/mike/Desktop/Git/codes/thirdPartyLibs/build-mk-host-release/build_suitesparse_for_geosx: line 6: cd: COLAMD: No such file or directory
/Users/mike/Desktop/Git/codes/thirdPartyLibs/build-mk-host-release/build_suitesparse_for_geosx: line 7: cd: CHOLMOD: No such file or directory
/Users/mike/Desktop/Git/codes/thirdPartyLibs/build-mk-host-release/build_suitesparse_for_geosx: line 8: cd: KLU: No such file or directory
/Users/mike/Desktop/Git/codes/thirdPartyLibs/build-mk-host-release/build_suitesparse_for_geosx: line 9: cd: UMFPACK: No such file or directory
make[2]: *** [suitesparse/src/suitesparse-stamp/suitesparse-build] Error 1
make[1]: *** [CMakeFiles/suitesparse.dir/all] Error 2
make: *** [all] Error 2

To Reproduce

cd thirdPartyLibs
python scripts/config-build.py -hc ../GEOSX/host-configs/mk-host.cmake -bt Release

cd build-mk-host-release
make

THIS IS THE HOST-CONFIG FILE THAT I WROTE

file: mk-host.cmake
detect host and name the configuration file
site_name(HOST_NAME)
set(CONFIG_NAME "mk-host" CACHE PATH "")
message( "CONFIG_NAME = ${CONFIG_NAME}" )

set paths to C, C++, and Fortran compilers. Note that while GEOSX does not contain ˓→any Fortran code,
some of the third-party libraries do contain Fortran code. Thus a Fortran compiler ˓→must be specified.
set(CMAKE_C_COMPILER "/Library/Developer/CommandLineTools/usr/bin/clang" CACHE PATH "")
set(CMAKE_CXX_COMPILER "/Library/Developer/CommandLineTools/usr/bin/clang++" CACHE PATH "")
#set(CMAKE_Fortran_COMPILER "/Library/Developer/CommandLineTools/usr/local/bin/gfortran" CACHE PATH "")
set(ENABLE_FORTRAN OFF CACHE BOOL "" FORCE)

enable MPI and set paths to compilers and executable.
Note that the MPI compilers are wrappers around standard serial compilers.
Therefore, the MPI compilers must wrap the appropriate serial compilers specified # in CMAKE_C_COMPILER, CMAKE_CXX_COMPILER, and CMAKE_Fortran_COMPILER. set(ENABLE_MPI ON CACHE PATH "")
set(MPI_C_COMPILER "/Library/Developer/CommandLineTools/usr/bin/mpicc" CACHE PATH "")
set(MPI_CXX_COMPILER "/Library/Developer/CommandLineTools/usr/bin/mpicxx" CACHE PATH "")
set(MPI_Fortran_COMPILER "/Library/Developer/CommandLineTools/usr/bin/mpifort" CACHE PATH "")
set(MPIEXEC "/Library/Developer/CommandLineTools/usr/bin/mpirun" CACHE PATH "")

disable CUDA and OpenMP
set(CUDA_ENABLED "OFF" CACHE PATH "" FORCE)
set(ENABLE_OPENMP "OFF" CACHE PATH "" FORCE)

enable PAMELA and PVTPackage
set(ENABLE_PAMELA ON CACHE BOOL "" FORCE)
set(ENABLE_PVTPackage ON CACHE BOOL "" FORCE)

enable tests
set(ENABLE_GTEST_DEATH_TESTS ON CACHE BOOL "" FORCE )

set(GEOSX_TPL_DIR=/path/to/thirdPartyLibs/install--release python scripts/config-build.py -hc host-configs/environment.cmake -bt Release
)
include(${CMAKE_CURRENT_LIST_DIR}/tpls.cmake)

**Comment by klevzoff** [comment]
@m-nsor can you post the entire log (the output of both `python` and `make` commands)? You can attach it as a text file if it's too long for a post.

**Comment by m-nsor** [comment]
I have attached it. Thank you
[compilation.pdf](https://github.com/GEOSX/GEOSX/files/6846592/compilation.pdf)


> @m-nsor can you post the entire log (the output of both `python` and `make` commands)? You can attach it as a text file if it's too long for a post.
