### ISSUE TITLE
submodule deinit integratedTests

### ISSUE THREAD

**Issue by m-nsor** [GEOSX/GEOSX#1503]
**Describe the bug**
error: could not lock config file .git/modules/integratedTests/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'integratedTests'

**To Reproduce**
git submodule deinit integratedTests

Also  the manual update using the commands below but GEOSX_PTP, PAMELA, PVTPackage could not be found.

git submodule init src/coreComponents/physicsSolvers/GEOSX_PTP
git submodule init src/externalComponents/PAMELA
git submodule init src/externalComponents/PVTPackage

**Comment by klevzoff** [comment]
Has the previous command `git submodule init` completed successfully?
Could you please run `git submodule` ans post the full output?

**Comment by m-nsor** [comment]
I run it and I have attached it
[SUBMODULE.pdf](https://github.com/GEOSX/GEOSX/files/6852083/SUBMODULE.pdf)

**Comment by m-nsor** [comment]
> Has the previous command `git submodule init` completed successfully?
> Could you please run `git submodule` ans post the full output?

**Comment by m-nsor** [comment]
> Has the previous command `git submodule init` completed successfully?
> Could you please run `git submodule` ans post the full output?

I run it and I have attached it
[SUBMODULE.pdf](https://github.com/GEOSX/GEOSX/files/6852104/SUBMODULE.pdf)

**Comment by klevzoff** [comment]
I'm not sure about the source of the error, it seems to be related to git on your system. I don't have a Mac to try this on, and I haven't heard about this problem from other users/developers, but I'm seeing a couple similar issues in a quick google search. Most likely it can be ignored, and you submodules are in a good state. To confirm, run `git submodule` and you output should look something like
```
-aabea5203beae2166a8236359377c454a0659e32 integratedTests
 85e24b99e537da61ad206270482dcff48c1cffa6 src/cmake/blt (v0.2.0-572-g85e24b9)
 b80e1b1df9ad2d3e9163d7a5ff088f0e3895ebb8 src/coreComponents/LvArray (v0.2.1-1-gb80e1b1)
 2dcf490c6bd8dfb4597fb28e32a698dca3be9ea9 src/coreComponents/constitutive/PVTPackage (remotes/origin/HEAD)
 bbc6bd0e2bfe6057ae9913e2713688eb8c26bc09 src/coreComponents/fileIO/coupling/hdf5_interface (remotes/origin/HEAD)
 9afe424e0c35208f3b8f07b25ab2b91004df7514 src/coreComponents/mesh/PAMELA (remotes/origin/HEAD)
```
Note the little `-` prefixing the `integratedTests` line - it's a sign the submodule is deactivated, so you can proceed with `git submodule update` and building the code. Let us know if there are any problems with this.

**Comment by m-nsor** [comment]
> I'm not sure about the source of the error, it seems to be related to git on your system. I don't have a Mac to try this on, and I haven't heard about this problem from other users/developers, but I'm seeing a couple similar issues in a quick google search. Most likely it can be ignored, and your submodules are in a good state. To confirm, run `git submodule` and you output should look something like
> 
> ```
> -aabea5203beae2166a8236359377c454a0659e32 integratedTests
>  85e24b99e537da61ad206270482dcff48c1cffa6 src/cmake/blt (v0.2.0-572-g85e24b9)
>  b80e1b1df9ad2d3e9163d7a5ff088f0e3895ebb8 src/coreComponents/LvArray (v0.2.1-1-gb80e1b1)
>  2dcf490c6bd8dfb4597fb28e32a698dca3be9ea9 src/coreComponents/constitutive/PVTPackage (remotes/origin/HEAD)
>  bbc6bd0e2bfe6057ae9913e2713688eb8c26bc09 src/coreComponents/fileIO/coupling/hdf5_interface (remotes/origin/HEAD)
>  9afe424e0c35208f3b8f07b25ab2b91004df7514 src/coreComponents/mesh/PAMELA (remotes/origin/HEAD)
> ```
> 
> Note the little `-` prefixing the `integratedTests` line - it's a sign the submodule is deactivated, so you can proceed with `git submodule update` and building the code. Let us know if there are any problems with this.

I am unable to proceed and attached the output.
[compilation.pdf](https://github.com/GEOSX/GEOSX/files/6852339/compilation.pdf)
