### ISSUE TITLE
GEOSX compilation

### ISSUE THREAD

**Issue by m-nsor** [GEOSX/GEOSX#1507]
**Describe the bug**
CMake Error at cmake/thirdparty/SetupGeosxThirdParty.cmake:131 (message):
  GEOSX requires hdf5, set HDF5_DIR to the hdf5 installation directory.

**To Reproduce**
 cd ../../GEOSX
python scripts/config-build.py -hc host-configs/mk-host.cmake -bt Release

**Comment by TotoGaz** [comment]
Hello @m-nsor 

> Describe the bug
CMake Error at cmake/thirdparty/SetupGeosxThirdParty.cmake:131 (message):
GEOSX requires hdf5, set HDF5_DIR to the hdf5 installation directory.

Depending on your input, this maybe a legit behavior and not a bug. 😉 

Can you provide more information (your host config file for example)?
Did you build the TPL properly?
This looks like the script does not find them.

**Comment by m-nsor** [comment]
> Hello @m-nsor
> 
> > Describe the bug
> > CMake Error at cmake/thirdparty/SetupGeosxThirdParty.cmake:131 (message):
> > GEOSX requires hdf5, set HDF5_DIR to the hdf5 installation directory.
> 
> Depending on your input, this maybe a legit behavior and not a bug. 😉
> 
> Can you provide more information (your host config file for example)?
> Did you build the TPL properly?
> This looks like the script does not find them.

Attached is the error and my host config.
[mk-host.pdf](https://github.com/GEOSX/GEOSX/files/6858279/mk-host.pdf)

<img width="588" alt="error" src="https://user-images.githubusercontent.com/86014570/126546989-b457b1d5-1ea4-4585-9338-fc2183d92567.png">

**Comment by TotoGaz** [comment]
I think that you do not tell GEOSX where it can find the third party libraries. You can use the `GEOSX_TPL_DIR` for that purpose. See https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/buildGuide/BuildProcess.html?highlight=GEOSX_TPL_DIR#build-steps

**Comment by m-nsor** [comment]
> I think that you do not tell GEOSX where it can find the third party libraries. You can use the `GEOSX_TPL_DIR` for that purpose. See https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/buildGuide/BuildProcess.html?highlight=GEOSX_TPL_DIR#build-steps



I added this path. Kindly verify if I did it right. Thank you



set(GEOSX_TPL_DIR=/path/to/thirdPartyLibs/install--release python scripts/config-build.py -hc host-configs/mk-host.cmake -bt Release
)
include(${CMAKE_CURRENT_LIST_DIR}/tpls.cmake)

**Comment by klevzoff** [comment]
@m-nsor 

1. Were you able to complete building `thirdPartyLibs`? You closed the other issue about it, so I'm assuming you found the solution?
2. You need to replace `/path/to/thirdPartyLibs` in the set command with the actual path to where you built it. Most likely it is `/Users/mike/Desktop/Git/codes/thirdPartyLibs`
