### ISSUE TITLE
Conduit issue

### ISSUE THREAD

**Issue by m-nsor** [GEOSX/GEOSX#1513]
I am getting this error 

CMake Error at cmake/thirdparty/SetupGeosxThirdParty.cmake:140 (find_package):
  Could not find a package configuration file provided by "Conduit" with any
  of the following names:

    ConduitConfig.cmake
    conduit-config.cmake

  Add the installation prefix of "Conduit" to CMAKE_PREFIX_PATH or set
  "Conduit_DIR" to a directory containing one of the above files.  If
  "Conduit" provides a separate development package or SDK, be sure it has
  been installed.

HOW DO I SET CONDUIT PATH TO AVOID THIS ERROR?

 Conduit
################################
if(DEFINED CONDUIT_DIR)
    message(STATUS "CONDUIT_DIR = ${CONDUIT_DIR}")

    find_package(Conduit REQUIRED
                 PATHS ${CONDUIT_DIR}/lib/cmake
                 NO_DEFAULT_PATH)

    set( CONDUIT_TARGETS conduit conduit_relay conduit_blueprint )
    foreach( targetName ${CONDUIT_TARGETS} )
        get_target_property( includeDirs 
                             ${targetName}
                             INTERFACE_INCLUDE_DIRECTORIES)
                             
        set_property(TARGET ${targetName} 
                     APPEND PROPERTY INTERFACE_SYSTEM_INCLUDE_DIRECTORIES
                     ${includeDirs})
    endforeach()
    set(thirdPartyLibs ${thirdPartyLibs} conduit::conduit )
else()
    message(FATAL_ERROR "GEOSX requires conduit, set CONDUIT_DIR to the conduit installation directory.")
endif()

**Comment by TotoGaz** [comment]
Hi @m-nsor!
Were you able to complete building thirdPartyLibs? You closed the other issue about it, so I'm assuming you found the solution?

**Comment by m-nsor** [comment]
> Hi @m-nsor!
> Were you able to complete building thirdPartyLibs? You closed the other issue about it, so I'm assuming you found the solution

  The thirdPartyLibs compiled without any error
but compiling the GEOSX is now the problem

**Comment by TotoGaz** [comment]
Do you see the `conduit` folder (with content) in your TPLs installation dir?
How do you provide the TPL installation directory to GEOSX?

**Comment by m-nsor** [comment]
In this path /Users/mike/Desktop/codes/thirdPartyLibs/install-tpls-release, I see conduit folder but it is empty.

**Comment by TotoGaz** [comment]
So you need to get back to your TPL build to check what was going on with conduit (and maybe other libraries then).

**Comment by m-nsor** [comment]
> Do you see the `conduit` folder (with content) in your TPLs installation dir?
> How do you provide the TPL installation directory to GEOSX?

This is the path I specified

set(GEOSX_TPL_DIR=/Users/mike/Desktop/codes/thirdPartyLibs/install--release python scripts/config-build.py -hc host-configs/mk-host.cmake -bt Release
)

**Comment by TotoGaz** [comment]
> > Do you see the `conduit` folder (with content) in your TPLs installation dir?
> > How do you provide the TPL installation directory to GEOSX?
> 
> This is the path I specified
> 
> set(GEOSX_TPL_DIR=/Users/mike/Desktop/codes/thirdPartyLibs/install--release python scripts/config-build.py -hc host-configs/mk-host.cmake -bt Release
> )

@klevzoff did answer about this: https://github.com/GEOSX/GEOSX/issues/1507#issuecomment-884511525

**Comment by klevzoff** [comment]
@m-nsor just do this in your host-config:
```
set(GEOSX_TPL_DIR /Users/mike/Desktop/codes/thirdPartyLibs/install--release)
```

I think my comment https://github.com/GEOSX/GEOSX/issues/1501#issuecomment-882304194 may have been confusing. The command line I gave there was not for including in the host-config file - it was an actual command line to run in the shell, as an alternative to setting the variable in host-config file.

**Comment by m-nsor** [comment]
> @m-nsor just do this in your host-config:
> 
> ```
> set(GEOSX_TPL_DIR /Users/mike/Desktop/codes/thirdPartyLibs/install--release)
> ```
> 
> I think my comment [#1501 (comment)](https://github.com/GEOSX/GEOSX/issues/1501#issuecomment-882304194) may have been confusing. The command line I gave there was not for including in the host-config file - it was an actual command line to run in the shell, as an alternative to setting the variable in host-config file.

I did as you stated but I still get the error
I am attaching everything that I have done so far.
Please, check and see. Thank you
[compilation error.pdf](https://github.com/GEOSX/GEOSX/files/6873390/compilation.error.pdf)

**Comment by klevzoff** [comment]
Do you still have the this line
```
include(${CMAKE_CURRENT_LIST_DIR}/tpls.cmake)
```
in `mk-host.cmake`? Could you please make sure it is there, and below the `set(GEOSX_TPL_DIR ...)` line?

In other words, your host-config should have the following:
```
set(GEOSX_TPL_DIR /Users/mike/Desktop/codes/thirdPartyLibs/install--release)
include(${CMAKE_CURRENT_LIST_DIR}/tpls.cmake)
```
where the first line sets the variable and the second line uses it to define paths to each individual library. Please also make sure you're not setting `CONDUIT_DIR` and other TPL paths manually in the host-config.

**Comment by m-nsor** [comment]
> Do you still have the this line
> 
> ```
> include(${CMAKE_CURRENT_LIST_DIR}/tpls.cmake)
> ```
> 
> in `mk-host.cmake`? Could you please make sure it is there, and below the `set(GEOSX_TPL_DIR ...)` line?
> 
> In other words, your host-config should have the following:
> 
> ```
> set(GEOSX_TPL_DIR /Users/mike/Desktop/codes/thirdPartyLibs/install--release)
> include(${CMAKE_CURRENT_LIST_DIR}/tpls.cmake)
> ```
> 
> where the first line sets the variable and the second line uses it to define paths to each individual library. Please also make sure you're not setting `CONDUIT_DIR` and other TPL paths manually in the host-config.

THIS IS WHAT I HAVE IN mk-host

# file: mk-host.cmake

# detect host and name the configuration file
site_name(HOST_NAME)
set(CONFIG_NAME "mk-host" CACHE PATH "")
message( "CONFIG_NAME = ${CONFIG_NAME}" )


# set paths to C, C++, and Fortran compilers. Note that while GEOSX does not contain ˓→any Fortran code,
# some of the third-party libraries do contain Fortran code. Thus a Fortran compiler ˓→must be specified.

set(CMAKE_C_COMPILER "/usr/bin/clang" CACHE PATH "")
set(CMAKE_CXX_COMPILER "/usr/bin/g++" CACHE PATH "")
set(CMAKE_Fortran_COMPILER "/usr/local/bin/gfortran" CACHE PATH "")
set(ENABLE_FORTRAN OFF CACHE BOOL "" FORCE)

# enable MPI and set paths to compilers and executable.
# Note that the MPI compilers are wrappers around standard serial compilers.
# Therefore, the MPI compilers must wrap the appropriate serial compilers specified # in CMAKE_C_COMPILER, CMAKE_CXX_COMPILER, and CMAKE_Fortran_COMPILER. set(ENABLE_MPI ON CACHE PATH "")

set(MPI_C_COMPILER "/usr/local/bin/mpicc" CACHE PATH "")
set(MPI_CXX_COMPILER "/usr/local/bin/mpicxx" CACHE PATH "")
set(MPI_Fortran_COMPILER "/usr/local/bin/mpifort" CACHE PATH "")
set(MPIEXEC "/usr/local/bin/mpirun" CACHE PATH "")

# disable CUDA and OpenMP

set(CUDA_ENABLED "OFF" CACHE PATH "" FORCE)
set(ENABLE_OPENMP "OFF" CACHE PATH "" FORCE)

# enable PAMELA and PVTPackage

set(ENABLE_PAMELA ON CACHE BOOL "" FORCE)
set(ENABLE_PVTPackage ON CACHE BOOL "" FORCE)

# enable tests
set(ENABLE_GTEST_DEATH_TESTS ON CACHE BOOL "" FORCE )

set(GEOSX_TPL_DIR "/Users/mike/Desktop/NSOR/thirdPartyLibs/install--release")
include(${CMAKE_CURRENT_LIST_DIR}/tpls.cmake)

**Comment by klevzoff** [comment]
I've just noticed that your `thirdPartlyLibs` installation directory in the attached log is different (compared to the previous issues), so I've edited my post above to reflect this, but just to be clear, here's once again what must be in the host-config:
```
set(GEOSX_TPL_DIR /Users/mike/Desktop/NSOR/thirdPartyLibs/install-mk-host-release)
include(${CMAKE_CURRENT_LIST_DIR}/tpls.cmake)
```
In other words, the directory you set must be exactly where `thirdPartyLibs` were installed. From the log, it seems like GEOSX build is still looking for the old path (`/Users/mike/Desktop/codes/thirdPartyLibs/install--release`).

**Comment by m-nsor** [comment]
I just repeated the whole installation the folder NSOR. I previously did it in  the folder codes.  I got the same result.

> I've just noticed that your `thirdPartlyLibs` installation directory in the attached log is different (compared to the previous issues), so I've edited my post above to reflect this, but just to be clear, here's once again what must be in the host-config:
> 
> ```
> set(GEOSX_TPL_DIR /Users/mike/Desktop/NSOR/thirdPartyLibs/install-mk-host-release)
> include(${CMAKE_CURRENT_LIST_DIR}/tpls.cmake)
> ```
> 
> In other words, the directory you set must be exactly where `thirdPartyLibs` were installed. From the log, it seems like GEOSX build is still looking for the old path (`/Users/mike/Desktop/codes/thirdPartyLibs/install--release`).

"(/Users/mike/Desktop/codes/thirdPartyLibs/install--release)" is the correct path but I repeated the whole installation in the folder NSOR that why this path "set(GEOSX_TPL_DIR /Users/mike/Desktop/NSOR/thirdPartyLibs/install-mk-host-release)". But the results were the same

**Comment by TotoGaz** [comment]
Hello @m-nsor 

From the log you attached we can see that you installed your TPL in `/Users/mike/Desktop/NSOR/thirdPartyLibs/install-mk-host-release`. Conduit being built and installed indeed . See pages 413 to 423 e.g. 
```
-- Installing: /Users/mike/Desktop/NSOR/thirdPartyLibs/install-mk-host-release/c
onduit/lib/cmake/conduit_setup_deps.cmake
-- Installing: /Users/mike/Desktop/NSOR/thirdPartyLibs/install-mk-host-release/c
onduit/lib/cmake/conduit_setup_targets.cmake
[ 75%] Completed 'conduit'
[ 75%] Built target conduit
```
Then when you build `GEOSX`, the log says
```
GEOSX_TPL_DIR=/Users/mike/Desktop/codes/thirdPartyLibs/install--release
```
which is inconsistent.

Further, `hdf5` is found in `/usr/local/Cellar/hdf5/1.12.1`. Which is not the location of your TPL, you surely have another version on your system; which is fine but it's not the version `GEOSX` wants.
Just after that, GEOSX cannot find `conduit`: it's looking in `/Users/mike/Desktop/codes/thirdPartyLibs/install--release` and not `/Users/mike/Desktop/codes/thirdPartyLibs/install-mk-host-release`

Please provide consistent `GEOSX_TPL_DIR`, there is nothing more that we can do on our side.
If you have another issues, please provide logs as you did, it helps us (actually, for this kind of problems, it's very unlikely we can help you with no logs).

**Comment by m-nsor** [comment]
> Hello @m-nsor
> 
> From the log you attached we can see that you installed your TPL in `/Users/mike/Desktop/NSOR/thirdPartyLibs/install-mk-host-release`. Conduit being built and installed indeed . See pages 413 to 423 e.g.
> 
> ```
> -- Installing: /Users/mike/Desktop/NSOR/thirdPartyLibs/install-mk-host-release/c
> onduit/lib/cmake/conduit_setup_deps.cmake
> -- Installing: /Users/mike/Desktop/NSOR/thirdPartyLibs/install-mk-host-release/c
> onduit/lib/cmake/conduit_setup_targets.cmake
> [ 75%] Completed 'conduit'
> [ 75%] Built target conduit
> ```
> 
> Then when you build `GEOSX`, the log says
> 
> ```
> GEOSX_TPL_DIR=/Users/mike/Desktop/codes/thirdPartyLibs/install--release
> ```
> 
> which is inconsistent.
> 
> Further, `hdf5` is found in `/usr/local/Cellar/hdf5/1.12.1`. Which is not the location of your TPL, you surely have another version on your system; which is fine but it's not the version `GEOSX` wants.
> Just after that, GEOSX cannot find `conduit`: it's looking in `/Users/mike/Desktop/codes/thirdPartyLibs/install--release` and not `/Users/mike/Desktop/codes/thirdPartyLibs/install-mk-host-release`
> 
> Please provide consistent `GEOSX_TPL_DIR`, there is nothing more that we can do on our side.
> If you have another issues, please provide logs as you did, it helps us (actually, for this kind of problems, it's very unlikely we can help you with no logs).

Thank you.

**Comment by TotoGaz** [comment]
@m-nsor Is it working now ? 😉

**Comment by m-nsor** [comment]
Yes, it is now working. The issue was that the thirdpartLibs could not be detected and also default MPI was turned off. Thank you

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________
