### ISSUE TITLE
Automatic allocation of compound constitutive relations

### ISSUE THREAD

**Issue by klevzoff** [GEOSX/GEOSX#1528]
@CusiniM, I could see the need to specify all of the sub-materials independently becoming a usability issue.  Users may perhaps forget to add rock when they define porousRock.  Just something to think about.

_Originally posted by @joshua-white in https://github.com/GEOSX/GEOSX/pull/1475#discussion_r682035369_

This was in reference to the following XML input:
```
materialList="{ rock, water, porousRock, rockPerm, rockPorosity}"
```

**Comment by klevzoff** [comment]
Simple proposal (subject to debate):
1. In `ConstitutiveBase`, add `virtual std::vector< string > getSubRelationNames() { return {}; }` (de-uglify the name)
2. Override in `CoupledSolid` to `return { m_solidModelName, m_porosityModelName, m_permeabilityModelName };`
3. Modify `ConstitutiveManager::hangConstitutiveRelation()` to additionally loop over this list from the compound relation and automatically register all sub-relations with the same quadrature.
4. Modify all XML files to only include the top-level model.

We can also consider doing this for multiphase fluids, where fluid, relative permeability and capillary pressure can be combined into a meta-model.

**Comment by CusiniM** [comment]
I think this is the way to go and we should also do it for the Fluid models as you suggested. Although capillary pressure and relative permeability are these weird properties which I don't know whether should belong to the fluid or to the porous material since they kind of depend on both. In any case, this will also allow to avoid specifying all the material names in the solvers which I think will make our xmls easier to handle.

**Comment by joshua-white** [comment]
I like this suggestion a lot.

**Comment by CusiniM** [comment]
I would allow flexibility in terms of number of constitutive points though. For example, I think one may want the permeability to be piecewise constant and the porosity to vary at each quadrature point.

**Comment by rrsettgast** [comment]
@klevzoff This is a good suggestion. 

@CusiniM Do we want a composite model mixing different quadratures for sub-models?

**Comment by CusiniM** [comment]
I think that for certain cases we do. For example, if we choose to run a problem with a permeability model that ignores all permeability dependencies on the state variables it feels a bit of a waste allocating it at each quadrature point. This though, does not necessarily mean that the porosity will also be constant.

**Comment by CusiniM** [comment]
I will start doing this.
