### ISSUE TITLE
[Bug] Crash when running FieldCaseTutorial1.xml

### ISSUE THREAD

**Issue by m-nsor** [GEOSX/GEOSX#1529]
**Describe the bug**
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

**To Reproduce**
[error.pdf](https://github.com/GEOSX/GEOSX/files/6929089/error.pdf)

**Comment by klevzoff** [comment]
Hey @m-nsor ,

It seems you have copied the input file from its original location (`src/coreComponents/physicsSolvers/multiphysics/integratedTests/FieldCaseTutorial1.xml`) to a different directory. Note that this input file is not self-contained, it references some other files, in particular, `tables_FieldCaseTuto/xlin.geos` and others under the `<Functions>` XML block. These files must be accessible using the same relative paths from the location of the main XML file.

In your case, this means you need to copy the entire directory `src/coreComponents/physicsSolvers/multiphysics/integratedTests/tables_FieldCaseTuto` into `/Users/mike/Desktop/nemick`, and make sure you can open `` in any program (e.g. `cat` or a text editor).

If the problem does not go away, please post the output of the following commands:
```
$ ls -la /Users/mike/Desktop/nemick/tables_FieldCaseTuto/
$ cat /Users/mike/Desktop/nemick/tables_FieldCaseTuto/xlin.geos
```

**Comment by m-nsor** [comment]
> Hey @m-nsor ,
> 
> It seems you have copied the input file from its original location (`src/coreComponents/physicsSolvers/multiphysics/integratedTests/FieldCaseTutorial1.xml`) to a different directory. Note that this input file is not self-contained, it references some other files, in particular, `tables_FieldCaseTuto/xlin.geos` and others under the `<Functions>` XML block. These files must be accessible using the same relative paths from the location of the main XML file.
> 
> In your case, this means you need to copy the entire directory `src/coreComponents/physicsSolvers/multiphysics/integratedTests/tables_FieldCaseTuto` into `/Users/mike/Desktop/nemick`, and make sure you can open `/Users/mike/Desktop/nemick/tables_FieldCaseTuto/xlin.geos` in any program (e.g. `cat` or a text editor).
> 
> If the problem does not go away, please post the output of the following commands:
> 
> ```
> $ ls -la /Users/mike/Desktop/nemick/tables_FieldCaseTuto/
> $ cat /Users/mike/Desktop/nemick/tables_FieldCaseTuto/xlin.geos
> ```

I repeated the run with the original path but still got the same error. Thank you
[error1.pdf](https://github.com/GEOSX/GEOSX/files/6929675/error1.pdf)

**Comment by klevzoff** [comment]
The second file contains a different error. The simulation now successfully initializes and makes the first time step, and the crash happens during VTK output. I'm not able to reproduce the crash on my machine, so it might be something specific to MacOS. It seems more like a VTK bug than a GEOSX one, but I can't say for sure unless I can reproduce and debug it.

@herve-gross @francoishamon @AntoineMazuyer has there ever been a problem with VTK output crashing on Mac?
The stack trace is below:
```
Received signal 8: Floating point exception: 8
Floating point exception:
** StackTrace of 22 frames **
Frame 0: _sigtramp
Frame 1: vtkXMLWriter::UpdateProgressDiscrete(float)
Frame 2: vtkXMLWriter::WriteCellDataInline(vtkCellData*, vtkIndent)
Frame 3: vtkXMLUnstructuredDataWriter::WriteInlinePiece(vtkIndent)
Frame 4: vtkXMLUnstructuredGridWriter::WriteInlinePiece(vtkIndent)
Frame 5: vtkXMLUnstructuredDataWriter::WriteInlineMode(vtkIndent)
Frame 6: vtkXMLUnstructuredDataWriter::WriteAPiece()
Frame 7: vtkXMLUnstructuredDataWriter::ProcessRequest(vtkInformation*, vtkInform
ationVector**, vtkInformationVector*)
Frame 8: vtkExecutive::CallAlgorithm(vtkInformation*, int, vtkInformationVector*
*, vtkInformationVector*)
Frame 9: vtkDemandDrivenPipeline::ExecuteData(vtkInformation*, vtkInformationVec
tor**, vtkInformationVector*)
Frame 10: vtkCompositeDataPipeline::ExecuteData(vtkInformation*, vtkInformationV
ector**, vtkInformationVector*)
Frame 11: vtkDemandDrivenPipeline::ProcessRequest(vtkInformation*, vtkInformatio
nVector**, vtkInformationVector*)
Frame 12: vtkStreamingDemandDrivenPipeline::ProcessRequest(vtkInformation*, vtkI
nformationVector**, vtkInformationVector*)
Frame 13: vtkStreamingDemandDrivenPipeline::Update(int, vtkInformationVector*)
Frame 14: vtkXMLWriter::Write()
Frame 15: geosx::vtk::VTKPolyDataWriterInterface::writeUnstructuredGrid(double,
std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<ch
ar> > const&, vtkUnstructuredGrid&) const
Frame 16: geosx::vtk::VTKPolyDataWriterInterface::writeCellElementRegions(double
, geosx::ElementRegionManager const&, geosx::NodeManager const&) const
Frame 17: geosx::vtk::VTKPolyDataWriterInterface::write(double, int, geosx::Doma
inPartition const&)
Frame 18: geosx::VTKOutput::execute(double, double, int, int, double, geosx::Dom
ainPartition&)
Frame 19: geosx::EventBase::execute(double, double, int, int, double, geosx::Dom
ainPartition&)
Frame 20: geosx::EventManager::run(geosx::DomainPartition&)
Frame 21: geosx::GeosxState::run()
Frame 22: main 
```

**Comment by herve-gross** [comment]
@klevzoff I just re-ran this tutorial with develop (hash 90ee53) and I have the same problem. Commenting out the VTK output and replacing by a Silo output makes the case work. I will investigate with a debugger. @m-nsor thanks for finding this!

**Comment by klevzoff** [comment]
@m-nsor If you check out the latest version from `develop` branch, you should now be able to use VTK output (e.g. running `FieldCaseTutorial1.xml`) on Mac without issues.

**Comment by m-nsor** [comment]
Thank you Sergey.

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________
