### ISSUE TITLE
[Other] Throw on invalid XML

### ISSUE THREAD

**Issue by klevzoff** [GEOSX/GEOSX#1533]
GEOSX should probably throw/terminate if XML input was not parsed correctly. Currently we just log the error and attempt to proceed. I'm not sure what the use case for this behavior is. Usually it just leads to much less user-friendly errors down the line.

In addition, `ProblemManager` member variables `xmlDocument`, `xmlResult` and `xmlProblemNode` don't seem to be used outside of a single function, `ProblemManager::parseInputFile()`. As such, they may not need to be members, and keeping the whole document around is pointless. We should verify that no part of the code is keeping around xml node handles, and dispose of the document once it's fully processed.

**Comment by joshua-white** [comment]
I second both points.  Adding @cssherman as our all-things-xml guru.

**Comment by rrsettgast** [comment]
@klevzoff Do you have an example xml that is not parsed properly, but continues to run?

**Comment by klevzoff** [comment]
@rrsettgast Adding malformed XML to any input file, for example adding an extra `<` before `<Problem>` gets you this:
```
Max threads: 12
XML parsed with errors!
Error description: Could not determine tag type
Error offset: 25

***** LOCATION: /home/klevtsov/work/GEOSX-develop/src/coreComponents/dataRepository/Group.hpp:325
***** Controlling expression (should be false): child == nullptr
***** Rank 0: Group /domain/MeshBodies doesn't have a child 0
```
Of course, it doesn't continue to run, but not because we rejected invalid XML, but because of a later error that reveals no information about the cause. My point is there seems to be no reason to continue beyond these lines:
https://github.com/GEOSX/GEOSX/blob/d3e262301b7dd124135d9797f118b86b20acde57/src/coreComponents/mainInterface/ProblemManager.cpp#L382-L388
i.e. we should throw here instead of just logging. Unless you think there is a case for "recoverable" errors?

**Comment by klevzoff** [comment]
For a more convincing example, I added the same malformed `<` later in the file, before `<Outputs>`, which leads to
```
Max threads: 12
XML parsed with errors!
Error description: Could not determine tag type
Error offset: 3066
Adding Solver of type SinglePhaseFVM, named SinglePhaseFlow
Adding Mesh: InternalMesh, mesh1
Adding Geometric Object: Box, source
Adding Geometric Object: Box, sink
Adding Event: PeriodicEvent, outputs
Adding Event: PeriodicEvent, solverApplications
Adding Event: PeriodicEvent, restarts
Adding Object CellElementRegion named Region1 from ObjectManager::Catalog.
  Region1/block1/water is allocated with 1 quadrature points.
  Region1/block1/rock is allocated with 1 quadrature points.
  Region1/block1/rockPerm is allocated with 1 quadrature points.

***** LOCATION: /home/klevtsov/work/GEOSX-develop/src/coreComponents/dataRepository/Group.hpp:336
***** Controlling expression (should be false): child == nullptr
***** Rank 0: Group /Outputs doesn't have a child siloOutput

** StackTrace of 6 frames **
Frame 0: geosx::dataRepository::Group::getBaseGroupByPath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const 
Frame 1: geosx::EventBase::getTargetReferences() 
Frame 2: geosx::EventManager::run(geosx::DomainPartition&) 
Frame 3: geosx::GeosxState::run() 
Frame 4: main 
Frame 5: __libc_start_main 
Frame 6: _start 
=====
```

I.e. it fails but much later. One can imagine though, that the last thing in an input file is some `<FieldSpecification>` tag that will just get ignored.

**Comment by cssherman** [comment]
@klevzoff - Unless we are willing to write an xml first aide tool, I think that we should just throw an error here.  In the long-term, we should be encouraging people to use an xml editor that can use the schema to identify issues before they are submitted.
