### ISSUE TITLE
[Bug] Time history collection with MPI runs

### ISSUE THREAD

**Issue by jhuang2601** [GEOSX/GEOSX#1545]
**Describe the bug**
When running the attached case (Sneddon problem with Lagrangian contact solver), some problem related to TimeHistory is observed. Running in parallel, simulation works fine and matches with the corresponding analytical solution.

Although there is no issue on the solver and simulation results,  some elements (-0.95 & -0.05) are repeatedly collected in the generated hdf5 files. Here is the example for the collected y-coordinates of the element center along the fracture plane:
on one rank:
```
[-0.95 -0.85 -0.75 -0.65 -0.55 -0.45 -0.35 -0.25 -0.15 -0.05  0.05  0.15
  0.25  0.35  0.45  0.55  0.65  0.75  0.85  0.95]
```
on two ranks:
```
[-0.95 -0.85 -0.75 -0.65 -0.55 -0.45 -0.35 -0.25 -0.15 -0.05  0.05  0.15
  0.25  0.35  0.45  0.55  0.65  0.75  0.85  0.95 -0.95 -0.95 -0.95 -0.95
 -0.95 -0.95 -0.95 -0.95 -0.95 -0.95 -0.95 -0.95 -0.95 -0.95 -0.95 -0.95
 -0.95 -0.95 -0.95 -0.95]
```
on four ranks:
```
[-0.95 -0.85 -0.75 -0.65 -0.55 -0.45 -0.35 -0.25 -0.15 -0.05 -0.95  0.05
  0.15  0.25  0.35  0.45  0.55  0.65  0.75  0.85  0.95  0.05 -0.95 -0.95
 -0.95 -0.95 -0.95 -0.95 -0.95 -0.95 -0.95 -0.95 -0.95 -0.05 -0.05 -0.05
 -0.05 -0.05 -0.05 -0.05 -0.05 -0.05 -0.05 -0.05]
```

**To Reproduce**
Corresponding xml file and lsf file are attached to reproduce the behavior
[TimeHistoryIssue.zip](https://github.com/GEOSX/GEOSX/files/7048585/TimeHistoryIssue.zip)

**Expected behavior**
With MPI runs, this observed redundancy of reporting data in TimeHistory does not jeopardize this specific simulation; however, it should be removed to avoid any potential issue.

**Platform (please complete the following information):**
- Machine: Pangea2 
- Compiler: gcc/8.3.0
- GEOSX Version: GEOSX-496f5b2

**Comment by cssherman** [comment]
@wrtobin - I'm not sure if it is related, but I'm also seeing some odd time history behavior for a parallel problem with an external mesh.  I'm packing the surface displacements from a model, and am planning to compare them to satellite measurements.  Looking at the outputs in python, I see a three timestep cycle: one complete snapshot and two incomplete snapshots (corresponding to the model rank) of surface displacement.

Here's a plot showing the model rank on the surface:
![image](https://user-images.githubusercontent.com/4932756/131731633-e9509b51-dc40-4b32-ac2f-fd11f8a92154.png)

Here's one of the complete-looking snapshots.  The box corresponds to the model boundary.  Also, it appears that there are a couple of zero-points that seem out of place:
![image](https://user-images.githubusercontent.com/4932756/131731703-4079b6f4-1727-4f9a-9d2d-f3f214c321fb.png)

Here's one of the incomplete snapshots (both look similar).  The valid-looking data seems to correspond to points in ranks 1, 19, 25, 27, 28:
![image](https://user-images.githubusercontent.com/4932756/131731898-3b2b516d-860d-42ed-8d57-d516da21fdf6.png)
![image](https://user-images.githubusercontent.com/4932756/131732063-40bac212-a661-487b-b510-b1e3de41ee8a.png)

**Comment by wrtobin** [comment]
@cssherman Hopefully it will wind up being the same underlying issue, but potentially it could be a wrinkle added by the external mesh somehow.

I'm hoping to be able to start taking a look at the two current time history issues next week.

**Comment by cssherman** [comment]
@wrtobin - great, thanks.  In the meantime, I'll see if I can cook up a smaller examples with an identical internal/external mesh for comparison.
