### ISSUE TITLE
[Feature] Better warning messages and documentation for incorrectly applied boundary conditions

### ISSUE THREAD

**Issue by jhuang2601** [GEOSX/GEOSX#1548]
**Describe the bug**
If using the outdated way to define traction loading, the simulation can still be running with develop repo and no warning/error message is returned.  As the boundary condition was not properly specified, the simulation got crashed at the very first time step. Users spent several weeks to pin down this issue and fix it by using the new format.

Old format to specify traction boundary condition:
![image](https://user-images.githubusercontent.com/53012159/131161647-2b8ee618-dc6b-4f5d-b895-c7247987ae89.png)

Most updated format to define traction boundary condition:
![image](https://user-images.githubusercontent.com/53012159/131161755-60d8908f-2603-4ba9-9c95-4ea872ebadd1.png)

**Expected behavior**
Proper check and warning message should be provided for any unaware change.

**Comment by joshua-white** [comment]
Proposed solutions:
(1) better logging of boundary condition applications via LogLevel output
(2) add high level guidance to documentation on field spec, boundary conditions, and debugging
(3) each physics solver provides a common problem / debugging section

**Comment by joshua-white** [comment]
Long-term solution could be a preprocessing layer / GUI that properly validates the XML input deck

**Comment by jhuang2601** [comment]
Not relevant anymore
