### ISSUE TITLE
[Docs] Wrong path for xml file

### ISSUE THREAD

**Issue by cj215** [GEOSX/GEOSX#1560]
src/docs/sphinx/tutorials/step02/Tutorial.rst --> wrong path xml file?

It should be GEOSX/src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/pamela_test

**Comment by jhuang2601** [comment]
@cj215 I just checked the Tutorial 2 and the path of xml files is correctly mentioned.  The inclusion of "GEOSX/" is not necessary, as all the folders are assumed to be the subfolders within the main folder of GEOSX in all documents.
