### ISSUE TITLE
[Bug] Invalid Solver Type for Tutorial 6 (CO2 injection)

### ISSUE THREAD

**Issue by brandonneth** [GEOSX/GEOSX#1563]
The solver type provided in the xml for tutorial 6 is not supported by Trilinos. The xml sets the solver type to "fgmres" but this solver type is not supported in the Trilinos interface code. 

**To Reproduce**
1. run: mpirun -np 4 ./bin/geosx -i ../src/coreComponents/physicsSolvers/multiphysics/integratedTests/FieldCaseCo2InjTutorial.xml
2. See error
```
***** ERROR
***** LOCATION: /g/g15/neth3/climate/GEOSX/src/coreComponents/linearAlgebra/interfaces/trilinos/TrilinosSolver.cpp:61
***** Controlling expression (should be false): true
***** Rank 1: Solver type not supported in Trilinos interface: fgmres

** StackTrace of 13 frames **
Frame 0: geosx::TrilinosSolver::TrilinosSolver(geosx::LinearSolverParameters)
Frame 1: std::_MakeUniq<geosx::TrilinosSolver>::__single_object std::make_unique<geosx::TrilinosSolver, geosx::LinearSolverParameters>(geosx::LinearSolverParameters&&)
Frame 2: geosx::TrilinosInterface::createSolver(geosx::LinearSolverParameters)
Frame 3: geosx::SolverBase::solveSystem(geosx::DofManager const&, geosx::EpetraMatrix&, geosx::EpetraVector&, geosx::EpetraVector&)
Frame 4: geosx::ReservoirSolverBase::solveSystem(geosx::DofManager const&, geosx::EpetraMatrix&, geosx::EpetraVector&, geosx::EpetraVector&)
Frame 5: geosx::SolverBase::nonlinearImplicitStep(double const&, double const&, int, geosx::DomainPartition&)
Frame 6: geosx::ReservoirSolverBase::solverStep(double const&, double const&, int, geosx::DomainPartition&)
Frame 7: geosx::SolverBase::execute(double, double, int, int, double, geosx::DomainPartition&)
Frame 8: geosx::EventBase::execute(double, double, int, int, double, geosx::DomainPartition&)
Frame 9: geosx::EventManager::run(geosx::DomainPartition&)
Frame 10: geosx::ProblemManager::runSimulation()
Frame 11: geosx::GeosxState::run()
Frame 12: main
Frame 13: /lib64/libc.so.6
=====
```

**Platform (please complete the following information):**
- Machine: LLNL/Lassen
- Compiler: clang upstream 2019.03.26 
- GEOSX Version: develop branch

**Additional context**
I went into the xml file and changed it from fgmres to gmres and the above error went away. However, I get a new, similar error:
```
***** ERROR
***** LOCATION: /g/g15/neth3/climate/GEOSX/src/coreComponents/linearAlgebra/interfaces/trilinos/TrilinosPreconditioner.cpp:304
***** Controlling expression (should be false): true
***** Rank 1: Preconditioner type not supported in Trilinos interface: mgr

** StackTrace of 11 frames **
Frame 0: geosx::TrilinosSolver::setup(geosx::EpetraMatrix const&)
Frame 1: geosx::SolverBase::solveSystem(geosx::DofManager const&, geosx::EpetraMatrix&, geosx::EpetraVector&, geosx::EpetraVector&)
Frame 2: geosx::ReservoirSolverBase::solveSystem(geosx::DofManager const&, geosx::EpetraMatrix&, geosx::EpetraVector&, geosx::EpetraVector&)
Frame 3: geosx::SolverBase::nonlinearImplicitStep(double const&, double const&, int, geosx::DomainPartition&)
Frame 4: geosx::ReservoirSolverBase::solverStep(double const&, double const&, int, geosx::DomainPartition&)
Frame 5: geosx::SolverBase::execute(double, double, int, int, double, geosx::DomainPartition&)
Frame 6: geosx::EventBase::execute(double, double, int, int, double, geosx::DomainPartition&)
Frame 7: geosx::EventManager::run(geosx::DomainPartition&)
Frame 8: geosx::ProblemManager::runSimulation()
Frame 9: geosx::GeosxState::run()
Frame 10: main
Frame 11: /lib64/libc.so.6
=====
```

Changing it to amg within the xml fixes this error as well.

**Comment by francoishamon** [comment]
Hello @brandonneth, 

The issue that you are observing comes from the fact that you are using a GEOSX configuration based on Trilinos (our default linear algebra package on Lassen), but the linear solver package required to run this tutorial is Hypre. 

To resolve this issue on Lassen, you have to uncomment this line here:
https://github.com/GEOSX/GEOSX/blob/d174b40b822501aec4fbadd674d39ab8bd87825b/host-configs/LLNL/lassen-base.cmake#L54
then reconfigure GEOSX, and then type: `make geosx`

There is another problem with this tutorial on Lassen: the solver uses a well to perform CO2 injection, but our current linear solution strategy cannot handle wells on GPU. Soon we should be able to overcome this limitation, but in the meantime this tutorial will not run well / not run at all on the GPU. I will add a note about this in the text of the tutorial.

However, you can still perform CO2 simulations on the GPU by replacing wells with simpler boundary conditions. An example can be found [here](https://github.com/GEOSX/GEOSX/blob/develop/src/coreComponents/physicsSolvers/fluidFlow/integratedTests/compositionalMultiphaseFlow/co2_flux_3d.xml), and we can help you construct a more complex test case using this approach.

**Comment by francoishamon** [comment]
I added the note about the GEOSX configuration with hypre in #1538
