### ISSUE TITLE
[Bug] PoroElastic Advanced Example Issue

### ISSUE THREAD

**Issue by serhiikryvenko16** [GEOSX/GEOSX#1579]
Unfortunately, I cannot run the Wellbore_Problem_PoroElastic.xml example. Something is wrong when I am adding a solver. Please see the error attached as a snippet. Thanks!
![image](https://user-images.githubusercontent.com/69527989/133853146-d8bdf409-a62e-4f31-baae-d3bf7ab6bc8f.png)

**Comment by jhuang2601** [comment]
@serhiikryvenko16 Which branch are you using to run this example? Try to use the most updated `develop` repository.

**Comment by serhiikryvenko16** [comment]
@jhuang2601 Thanks for a quick response. I was using the same XML file being provided. 
Just realized that after I run git pull, I have identical errors for other tutorials ... 
![image](https://user-images.githubusercontent.com/69527989/133860254-98dd432f-7f13-4a1a-aabe-537711e90887.png)

**Comment by serhiikryvenko16** [comment]
@jhuang2601 - FYI: I have simply reinstalled GEOSX - now it all works.
