### ISSUE TITLE
[Bug] Issue of poroelastic wellbore problem in tutorial

### ISSUE THREAD

**Issue by jhuang2601** [GEOSX/GEOSX#1587]
**Describe the bug**
Rerun the tutorial example for poroelastic wellbore problem with recent develop repo; however, the simulation results cannot match analytical solutions anymore. Similarly, Sy-Tuan observed the same issue with a different wellbore problem.

**To Reproduce**
1. Run the case from `src/coreComponents/physicsSolvers/multiphysics/benchmarks/WellboreProblem_PoroElastic.xml`
2. Use the recent develop repo `cea27cd`

**Expected behavior**
This tutorial example previously worked with develop repo (`496f5b2`) and correlated well with the analytical solutions. Some recent changes cause the unexpected issue of the poromechanics solver and this kind of degradation should be fixed.

**Screenshots**
![image](https://user-images.githubusercontent.com/53012159/134391459-993645b5-1824-4d14-ae6f-e762544d7337.png)

**Platform (please complete the following information):**
- Machine: Pangea2 
- Compiler: gcc 8.3.0
- GEOSX Version: cea27cd

**Comment by joshua-white** [comment]
Grrr, @shabnamjs has added this problem as an integrated test on her branch so we would catch this type of regression.  It looks like we are too late.

@jhuang2601, can you step through the commit history and figure out more precisely where this broke?

**Comment by jhuang2601** [comment]
@joshua-white By tracking commit history and testing the example, the reported regression takes place from commit `a23824a`. The commit `d6347e0` is the last good one.

![image](https://user-images.githubusercontent.com/53012159/134405710-7f943d99-9bbb-49c9-be2c-844dc11806db.png)

**Comment by joshua-white** [comment]
Okay, this PR updates the constitutive models, so that makes sense, but @CusiniM had to pass all of the poroelastic integrated tests to get it in, so those must still work.  Are you sure it is not an issue with a slight re-definition of the XML parameters?  What happens with the other wellbore examples?

@CusiniM, thoughts?

**Comment by CusiniM** [comment]
Hmm Can I see the input files and have a few more details about the test case? The wellbore integratedTests work fine so hopefully it's just something with the xml files.

As a separate note, these test cases should have some coarse version as integratedTests to avoid issues like this one.

**Comment by joshua-white** [comment]
I can confirm the overlap between tutorial and integratedTest coverage is basically zero.  Not good.

**Comment by CusiniM** [comment]
It's a little hard to tell coz it's a `poroelastic` case but by looking at the pressure distribution I have a feeling it has to do with the porosity (is the biotCoefficient the same?) and/or the permeability.

**Comment by CusiniM** [comment]
I am actually a bit confused.

1.  I don't see any history for that input file. Was this created once the `PorousSolid` had already been added to the code? 

2. the commit that has broken the results only touches the constitutive models for the flow and the stencils.

I am afraid that the only way out is to run both versions of the code and compare them step by step. Let me know if you want me to do it.

**Comment by jhuang2601** [comment]
@CusiniM @joshua-white 

This advanced example was created and added to the develop repo after the PR with `PorousSolid`. 

Exactly same xml file (same porosity and permeability model) is tested with different commits to track down where the regression happens. The xml file is located at `src/coreComponents/physicsSolvers/multiphysics/benchmarks/WellboreProblem_PoroElastic.xml`

The coarse version of this example is prepared; however, it has not been added to the integrated test. 

I've also tested the wellbore problem with Extended Drucker-Prager model and no issue for that one.

**Comment by jhuang2601** [comment]
@CusiniM @joshua-white 
Actually, Sy-Tuan first found this problem for his poroelastic case with deviated wellbore and checked me. I tried to rerun the tutorial example (which is different from his wellbore example) and observed the same issue.

**Comment by joshua-white** [comment]
that is odd thought that Drucker-Prager works.  What happens if you set the cohesion to a very high value?  Do you get the right poroelastic answer?  How exactly are the two problems different?

**Comment by jhuang2601** [comment]
@joshua-white Drucker-Prager works for the case without pore pressure, which can only confirm the issue is not related to mechanical solver.

**Comment by CusiniM** [comment]
I think I have found the issue. It is the porosity. Let me understand how to fix it and I ll either post it here or send you something on slack.

**Comment by CusiniM** [comment]
The solution seems to be trivial but it may show a more general issue.

Adding 

````xml
 <FieldSpecification 
    name="initialPorosity"
    initialCondition="1"
    setNames="{all}"
    objectPath="ElementRegions/Omega/cb1"
    fieldName="rockPorosity_porosity"
    scale="0.2"/>

seems to fix it. In that PR I have changed the default value for the porosity. The pressure porosity initializes the porosity to the reference value (I think) but the `BiotPorosity`, in theory, would require an initialization which we don't do. It's important to provide an initial value. I don't love this though coz it's easy to forget and porosity will be equal to 1 in that case. Maybe we should throw an error for any nonphysical value...

**Comment by jhuang2601** [comment]
@CusiniM @joshua-white As suggested, by initializing the porosity, correct results could be obtained
![image](https://user-images.githubusercontent.com/53012159/134439347-cbc04baa-3766-47ff-95e3-54627c0e02c9.png)

**Comment by joshua-white** [comment]
Nice.  Let's work with @shabnamjs to make sure appropriate integratedTests get added on her PR.  I think we can merge that one any day now.  Let's discuss tomorrow at the dev meeting.

**Comment by sytuannguyen** [comment]
> The solution seems to be trivial but it may show a more general issue.
> 
> Adding
> 
> ```
>  <FieldSpecification 
>     name="initialPorosity"
>     initialCondition="1"
>     setNames="{all}"
>     objectPath="ElementRegions/Omega/cb1"
>     fieldName="rockPorosity_porosity"
>     scale="0.2"/>
> ```
> 
> seems to fix it. In that PR I have changed the default value for the porosity. The `PressurePorosity` initializes the porosity to the reference value (I think) but the `BiotPorosity`, in theory, would require an initialization which we don't really do in geosx for now. It's important to provide an initial value. I don't love this though coz it's easy to forget and porosity will be equal to 1 in that case. Maybe we should throw an error for any nonphysical value...

So actually we need to define two indentical porosities in the XML, one in `BiotPorosity` block and one in `FieldSpecification` block. We may want to remove one of them by updating the code?
