### ISSUE TITLE
blt_mpi_smoke and testFloatingPointExceptions tests fail

### ISSUE THREAD

**Issue by macdoncj** [GEOSX/GEOSX#1588]
I am trying to install GEOSX on Ubuntu 20.04.3 and have carefully followed the instructions given in the Quick Start Guide. Everything works except that the final testing (via the ctest -V command) reports 2 errors:

The following tests FAILED:
          2 - blt_mpi_smoke (Failed)
         73 - testFloatingPointExceptions (Failed).

Details are:

test 2

[HANDLER_OUTPUT]
        Start   2: blt_mpi_smoke

[HANDLER_VERBOSE_OUTPUT]

2: Test command: /usr/bin/mpirun "-n" "4" "/home/macdoncj/geosx/codes/GEOSX/build-ubuntu-laptop-release/tests/blt_mpi_smoke"

2: Test timeout computed to be: 1500
2: --------------------------------------------------------------------------
2: There are not enough slots available in the system to satisfy the 4
2: slots that were requested by the application:
2:
2:   /home/macdoncj/geosx/codes/GEOSX/build-ubuntu-laptop-release/tests/blt_mpi_smoke
2:
2: Either request fewer slots for your application, or make more slots
2: available for use.
2:
2: A "slot" is the Open MPI term for an allocatable unit where we can
2: launch a process.  The number of slots available are defined by the
2: environment in which Open MPI processes are run:
2:
2:   1. Hostfile, via "slots=N" clauses (N defaults to number of
2:      processor cores if not provided)
2:   2. The --host command line parameter, via a ":N" suffix on the
2:      hostname (N defaults to 1 if not provided)
2:   3. Resource manager (e.g., SLURM, PBS/Torque, LSF, etc.)
2:   4. If none of a hostfile, the --host command line parameter, or an
2:      RM is present, Open MPI defaults to the number of processor cores
2:
2: In all the above cases, if you want Open MPI to default to the number
2: of hardware threads instead of the number of processor cores, use the
2: --use-hwthread-cpus option.
2:
2: Alternatively, you can use the --oversubscribe option to ignore the
2: number of available slots when deciding the number of processes to
2: launch.
2: --------------------------------------------------------------------------
[HANDLER_OUTPUT]
  2/138 Test   #2: blt_mpi_smoke ........................................
***Failed    0.30 sec

test 73

[HANDLER_OUTPUT]
        Start  73: testFloatingPointExceptions

[HANDLER_VERBOSE_OUTPUT]

73: Test command: /home/macdoncj/geosx/codes/GEOSX/build-ubuntu-laptop-release/tests/testFloatingPointExceptions

73: Test timeout computed to be: 1500
73: [==========] Running 5 tests from 1 test suite.
73: [----------] Global test environment set-up.
73: [----------] 5 tests from TestFloatingPointEnvironment
73: [ RUN      ] TestFloatingPointEnvironment.Underflow
73: /home/macdoncj/geosx/codes/GEOSX/src/coreComponents/LvArray/unitTests/testFloatingPointExceptions.cpp:36: Failure
73: Death test: divide( double(2.22507385850720138309023271733240406e-308L), 2 )
73:     Result: failed to die.
73:  Error msg:
73: [  DEATH   ]
73: [  FAILED  ] TestFloatingPointEnvironment.Underflow (4 ms)
73: [ RUN      ] TestFloatingPointEnvironment.DivideByZero
73: /home/macdoncj/geosx/codes/GEOSX/src/coreComponents/LvArray/unitTests/testFloatingPointExceptions.cpp:48: Failure
73: Death test: divide( 1, 0 )
73:     Result: failed to die.
73:  Error msg:
73: [  DEATH   ]
73: [  FAILED  ] TestFloatingPointEnvironment.DivideByZero (6 ms)
73: [ RUN      ] TestFloatingPointEnvironment.Overlow
73: /home/macdoncj/geosx/codes/GEOSX/src/coreComponents/LvArray/unitTests/testFloatingPointExceptions.cpp:54: Failure
73: Death test: multiply( double(1.79769313486231570814527423731704357e+308L), 2 )
73:     Result: failed to die.
73:  Error msg:
73: [  DEATH   ]
73: [  FAILED  ] TestFloatingPointEnvironment.Overlow (4 ms)
73: [ RUN      ] TestFloatingPointEnvironment.Invalid
73: /home/macdoncj/geosx/codes/GEOSX/src/coreComponents/LvArray/unitTests/testFloatingPointExceptions.cpp:60: Failure
73: Death test: invalid()
73:     Result: failed to die.
73:  Error msg:
73: [  DEATH   ]
73: [  FAILED  ] TestFloatingPointEnvironment.Invalid (3 ms)
73: [ RUN      ] TestFloatingPointEnvironment.FloatingPointExceptionGuard
73: /home/macdoncj/geosx/codes/GEOSX/src/coreComponents/LvArray/unitTests/testFloatingPointExceptions.cpp:70: Failure
73: Death test: multiply( double(1.79769313486231570814527423731704357e+308L), 2 )
73:     Result: failed to die.
73:  Error msg:
73: [  DEATH   ]
73: [  FAILED  ] TestFloatingPointEnvironment.FloatingPointExceptionGuard (5 ms)
73: [----------] 5 tests from TestFloatingPointEnvironment (22 ms total)
73:
73: [----------] Global test environment tear-down
73: [==========] 5 tests from 1 test suite ran. (22 ms total)
73: [  PASSED  ] 0 tests.
73: [  FAILED  ] 5 tests, listed below:
73: [  FAILED  ] TestFloatingPointEnvironment.Underflow
73: [  FAILED  ] TestFloatingPointEnvironment.DivideByZero
73: [  FAILED  ] TestFloatingPointEnvironment.Overlow
73: [  FAILED  ] TestFloatingPointEnvironment.Invalid
73: [  FAILED  ] TestFloatingPointEnvironment.FloatingPointExceptionGuard
73:
73:  5 FAILED TESTS
 73/138 Test  #73: testFloatingPointExceptions ..........................
***Failed    0.04 sec

Please can you suggest how I can stop these tests from failing.

Thank-you

Additional Information:
cpp version - cpp (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
cpic++ version - g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
mpirun version - mpirun (Open MPI) 4.0.3

**Comment by klevzoff** [comment]
> Multiple solutions are proposed in the log. Surely the easiest for you is to run with
> 
> ```
> 2: Alternatively, you can use the --oversubscribe option to ignore the
> 2: number of available slots when deciding the number of processes to
> 2: launch.
> ```

To have this flag added to MPI tests automatically, add the following to your host-config:
```cmake
set( BLT_MPI_COMMAND_APPEND "--oversubscribe" CACHE STRING "" )
```
and then from the build directory rerun 
```
$ cmake -C /path/to/host-config.cmake ../src
$ make -j
$ ctest
```
Alternatively, you can do a bull rebuild after changing host-config (i.e. starting with `confif-build.py` script), but it'll take longer.

**Comment by macdoncj** [comment]
Thank-you for your constructive suggestions to the blt_mpi_smoke issue and apologies for not saying so sooner.

**Comment by joshua-white** [comment]
@macdoncj, can you try two things?

- Have you confirmed your MPI environment works independently of GEOSX?  That is, can you launch a simple mpi_hello_world program without problems?
- Can you try explicitly defining the partitioning in the command line arguments? `mpirun -np 2 geosx -i 3D_10x10x10_compressible.xml -x 2 -y 1 -z 1` for two processes, split along x.

**Comment by macdoncj** [comment]
I finally managed to run the first GEOSX tutorial problem as follows:

$ mpirun -np 2 -mca mca_btl_vader_single_copy_mechanism cma ./bin/geosx -i 3D_10x10x10_compressible.xml -x 2 -y 1 -z 1

As far as I can make out, the MPI errors and warnings I get are related to the file /proc/sys/kernel/yama/ptrace_scope having the value 1 instead of 0. With Ubuntu running under Windows 10 I am unable to edit this file to change the value from 1 to 0. This seems to be a Windows security feature. If anyone has a solution to this, I’d be grateful to hear about in. In the meantime, I am going to make by laptop a dual boot system (Ubuntu and Widows 10). I shall then re-install GEOSX and see whether the 2 test failures resolve themselves,

At the moment, my issues all seem to be related to trying to install GEOSX on a Windows 10 machine. Perhaps a warning in the installation instructions that this is not the best way to go would be very helpful.

I have also run a simple mpi_hello_world program that runs with and without the -mca mca_btl_vader_single_copy_mechanism cma option. In both cases, the output is surrounded by MPI warnings:

$ mpirun -n 2 openmpi.exe
--------------------------------------------------------------------------
WARNING: Linux kernel CMA support was requested via the
btl_vader_single_copy_mechanism MCA variable, but CMA support is
not available due to restrictive ptrace settings.

The vader shared memory BTL will fall back on another single-copy
mechanism if one is available. This may result in lower performance.

  Local host: DESKTOP-AR1P9PB
--------------------------------------------------------------------------
Hello world from processor DESKTOP-AR1P9PB, rank 1 out of 2 processors
Hello world from processor DESKTOP-AR1P9PB, rank 0 out of 2 processors
[DESKTOP-AR1P9PB:00075] 1 more process has sent help message help-btl-vader.txt / cma-permission-denied
[DESKTOP-AR1P9PB:00075] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

**Comment by TotoGaz** [comment]
> At the moment, my issues all seem to be related to trying to install GEOSX on a Windows 10 machine. Perhaps a warning in the installation instructions that this is not the best way to go would be very helpful.

You may consider using docker https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/developerGuide/Contributing/UsingDocker.html 
It's officially unsupported but it's working well and could help you in the first steps of your journey.

**Comment by joshua-white** [comment]
To date, most of our windows users have opted to use WSL (Windows Subsystem for Linux) with good success:

https://docs.microsoft.com/en-us/windows/wsl/

Given the available working options (WSL, docker, Virtual Machines) we have not made supporting native Windows installation a priority.  The level of effort that would be required is high, given that the microsoft development ecosystem is not always standards compliant ... or at least, it likes to follow its own standard :-)

That said, the point is very well taken we need to upgrade our documentation to point new Windows users in a good direction.  I'll add a documentation issue.  If you are happy with the resolution here, @macdoncj, would you mind closing this one?
