### ISSUE TITLE
[Other] Installation issue on Ubuntu

### ISSUE THREAD

**Issue by brendonhall** [GEOSX/GEOSX#1606]
I'm trying to install GEOSX on a Ubuntu 20.04.3 LTS workstation.  The TPLs configure and build fine.  I'm getting the following error when configuring the main code:

```
  Unknown CMake command "blt_import_library".
Call Stack (most recent call first):
  cmake/CMakeBasics.cmake:49 (include)
  CMakeLists.txt:36 (include)
```

Any help would be appreciated, and I'm sure I can supply additional information.  These are the compiler versions I'm using:

```
$ cpp --version
cpp (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ mpic++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ cmake --version
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by klevzoff** [comment]
Hi @brendonhall ,

Please make sure you've run these commands after cloning the main GEOSX repository:
```
git submodule init
git submodule deinit integratedTests
git submodule update
```

If the error persists, could you please provide the output of `git submodule` command?

**Comment by brendonhall** [comment]
Hi Sergey, thank you for the help.  I was able to compile geosx succesfully.  I'm having issues running some of the examples, which I'll post in a different issue.
