### ISSUE TITLE
[Bug] real64 xml inputs do not throw an error when alpha characters are present

### ISSUE THREAD

**Issue by cssherman** [GEOSX/GEOSX#1632]
Using the sedov problem as an example, I found that the code does not throw an error when it detects alpha characters when parsing real64 values (at least) from an input xml.  For example, you could replace the forceDt in the sedov example, and it would run:

```xml
<PeriodicEvent
      name="solverApplications"
      forceDt="NotANumber"
      target="/Solvers/lagsolve"/>
```

**Comment by klevzoff** [comment]
Fixed
