### ISSUE TITLE
Move Nightly CI Tests from Bamboo to Gitlab

### ISSUE THREAD

**Issue by bmhan12** [GEOSX/GEOSX#1685]
Bamboo will be going down Jan. 17, 2022 as LC moves to supporting gitlab ([LC Gitlab link](https://lc.llnl.gov/gitlab/users/sign_in))

- [x] Setup mirroring from Github to gitlab. LC Guide: https://lc.llnl.gov/confluence/pages/viewpage.action?pageId=662832265
- [x] Move bamboo scripts and setup to gitlab
- [x] Reconfigure scripts on gitlab to push updates to nightlyTests repo

**Comment by TotoGaz** [comment]
Hi @bmhan12 This looks like this was done in https://github.com/GEOSX/GEOSX/pull/1888 maybe?

**Comment by bmhan12** [comment]
Yes, I'll close this issue.
