### ISSUE TITLE
[Bug] cannot visualize the silo outputs for proppant example

### ISSUE THREAD

**Issue by jhuang2601** [GEOSX/GEOSX#1699]
**Describe the bug**
Cannot open the Silo outputs after running advanced example for proppant slot test.

**To Reproduce**
Run the xml file with develop repo from `inputFiles/proppant/ProppantSlotTest_benchmark.xml`
Use Visit (v3.2.1) to visualize the silo outputs and receive the following error:
```
VisIt could not read from the file "/lustre4/scratch/j0551570/geosx/Proppant/base/siloFiles/plot_* database".

The generated error message was:

There was an error opening /lustre4/scratch/j0551570/geosx/Proppant/base/siloFiles/plot_* database. It may be an invalid file.
VisIt tried using the following file format readers to open the file: Silo

If you know the specific format reader VisIt should use to
read this data, you can use Open As... (GUI) or
'-o <file>,<plugin> (CL arg.) and identify that specific reader
for VisIt to try. This will possibly give more information on
the exact error.
```

**Expected behavior**
Silo outputs should be correctly generated and visualized by Visit 

**Platform (please complete the following information):**
- Machine: Pecan 
- GEOSX Version: develop `8577777`

**Comment by joshua-white** [comment]
Jian believes the commit from September was still working.  He is going to step through the commit history to find where this breaks.  It is likely something outside of the proppant solver itself, as that hasn't been touched since September.

**Comment by jhuang2601** [comment]
Not relevant anymore and switch to vtk and HDF5 outputs.
