### ISSUE TITLE
[Bug] Crash running TimeHistory on compute nodes in Pangea2

### ISSUE THREAD

**Issue by francoishamon** [GEOSX/GEOSX#1724]
**Describe the bug**
Our Total users are not able to run simulations with `TimeHistory` output on Pangea2 whenever they launch simulations on the compute nodes. If they request an allocation and launch the simulation using `bsub`, the simulation fails with the following message:
```
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5F.c line 509 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../hdf5/src/H5Fint.c line 1652 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: ../../hdf5/src/H5Fsuper.c line 623 in H5F__super_read(): truncated file: eof = 9640, sblock->base_addr = 0, stored_eof = 11696
    major: File accessibilty
    minor: File has been truncated
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 119 in H5Dcreate2(): not a location ID
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: ../../hdf5/src/H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 331 in H5Dclose(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) MPI-process 0:
  #000: ../../hdf5/src/H5F.c line 671 in H5Fclose(): not a file ID
    major: File accessibilty
    minor: Inappropriate type
This requires fcntl(2) to be implemented. As of 8/25/2011 it is not. Generic MPICH Message: File locking failed in ADIOI_Set_lock(fd 1D,cmd F_SETLKW/7,type F_WRLCK/1,whence 0) with return value FFFFFFFF and errno 26.
- If the file system is NFS, you need to use NFS version 3, ensure that the lockd daemon is running on all the machines, and mount the directory with the 'noac' option (no attribute caching).
- If the file system is LUSTRE, ensure that the directory is mounted with the 'flock' option.
ADIOI_Set_lock:: Function not implemented
ADIOI_Set_lock:offset 14592, length 1736
```

**To Reproduce**
It requires accessing Pangea2
1. Checkout this [branch](https://github.com/GEOSX/GEOSX/tree/feature/hamon/forPierreAndAbdoulKassim) (not `develop`, because this branch has the fix for MGR with wells) on Pangea2 (already deployed)
2. Run this model with the launcher.lsf included: 
[ex6.zip](https://github.com/GEOSX/GEOSX/files/7841647/ex6.zip)

**Expected behavior**
It should work.

**Platform (please complete the following information):**
- Pangea2
- This [GEOSX branch](https://github.com/GEOSX/GEOSX/tree/feature/hamon/forPierreAndAbdoulKassim), deployed automatically on Pangea2 (here: `/workrd/SCR/GEOSX/install/gcc8/GEOSX-9ff787c/bin/geosx`)

**Additional context**
If we remove `TimeHistory` the simulation works fine.

**Comment by jhuang2601** [comment]
@francoishamon I've reported the same issue (#1482) last year. Thomas helped to solve this problem on Pangea2. You need to include a file called `ROMIO_HINTS` in your folder, which can be found in this example on Pangea2:
`/scratchrd/SCR/GEOS/GEOSX/Jian/Run`

**Comment by francoishamon** [comment]
Sounds great, thanks @jhuang2601, we forgot about this `ROMIO_HINTS` file. It should fix this issue.
