### ISSUE TITLE
[Bug] Compilation is impacted by environment after the configuration step

### ISSUE THREAD

**Issue by TotoGaz** [GEOSX/GEOSX#1738]
Issue https://github.com/GEOSX/GEOSX/issues/1722 (and specially comment https://github.com/GEOSX/GEOSX/issues/1722#issuecomment-1007773444) pinpointed a strange behavior in our build.

On the Pecan cluster, the `config-build.py` selects the proper `hdf5`:
```
-- HDF5_DIR_REAL=/.../travis-deployments/CPU/GEOSX_TPL-a634fc6/hdf5
-- Checking that found HDF5_INCLUDE_DIRS are in HDF5_DIR
-- HDF5_INCLUDE_DIRS=/.../travis-deployments/CPU/GEOSX_TPL-a634fc6/hdf5/include
--  /.../travis-deployments/CPU/GEOSX_TPL-a634fc6/hdf5/include includes HDF5_DIR (/.../travis-deployments/CPU/GEOSX_TPL-a634fc6/hdf5)
```
But when compiling, if `module load anaconda3` (after the `config-build.py` step), then we face compilation issues. Indeed, modifying the compilation command by adding the `-E` flag to get the pre-processed c++ file (at least with `gcc`) shows that
```
:# 1 "/hrtc/apps/scripting/anaconda3/x86_64/2020.02/include/hdf5.h" 1
```
is included and not the `hdf5.h` from our `TPL`s.

Unloading `anaconda3` (which comes with its own version of `hdf5`) solves the issue.

It seems that the environment influences our build after the set-up. Is it legit?

**Comment by klevzoff** [comment]
The module likely appends to `CPATH`, which takes priority in header search over anything that is included with `-isystem` (which is how we include TPLs I believe?): https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html

(BTW have I mentioned that environmental modules are trash? It's like using global mutable variables in a programming language, which everyone despises. It's so sad that there is no better solution for managing software installs in 2022)

**Comment by TotoGaz** [comment]
Hi @klevzoff Yes, it's surely something like this, obviously.

Now your link states that "_Each specifies a list of directories to be searched as if specified with -isystem, but after any paths given with -isystem options on the command line._".
In my memories, we have paths provided to `-isystem` (and the `hdf5` path, of course), so we should carefully check this.
Providing the appropriate path to the `TPL` should not let `CPATH` intercept our build, should it?

> (BTW have I mentioned that environment modules are trash? It's like using global mutable variables in a programming language, which everyone despises. It's so sad that there is no better solution for managing software installs in 2022)

You think as a developer, but users are very happy to blindly `module load` something. Maybe there could be a `pkg` and a `pkg-dev` distinction, like for linux distributions? I don't know. What I know is that it takes a lot of time to maintain!

And there are solution, like [nix](https://github.com/NixOS/nix), [guix](https://guix.gnu.org/) or [spack](https://spack.io/) that you've obviously hear of.

**Comment by klevzoff** [comment]
> Now your link states that "_Each specifies a list of directories to be searched as if specified with -isystem, but after any paths given with -isystem options on the command line._".
> In my memories, we have paths provided to `-isystem` (and the `hdf5` path, of course), so we should carefully check this.
> Providing the appropriate path to the `TPL` should not let `CPATH` intercept our build, should it?

Unfortunately, `CPATH` specifically is treated as if included with `-I`, which has priority over `-isystem` (the other three vars on that list are indeed processed as `-isystem`).

**Comment by klevzoff** [comment]
> You think as a developer, but users are very happy to blindly `module load` something. Maybe there could be a `pkg` and a `pkg-dev` distinction, like for linux distributions? I don't know. What I know is that it takes a lot of time to maintain!
> 
> And there are solution, like [nix](https://github.com/NixOS/nix), [guix](https://guix.gnu.org/) or [spack](https://spack.io/) that you've obviously hear of.

I mean, I was being exaggeratedly harsh. I do remember the times when Stanford's CEES cluster did not use modules, and getting something to compile correctly was a game of luck; modules came as a blessing, for sure. But these days, in the era of  CI and _reproducible_ builds, compilers relying on env vars and modules setting those vars seem antithetical to that. I wonder if CMake or BLT have considered adding an option to run all build commands in a squeaky-clean environment, so that only explicitly passed flags (and paths baked into the compiler binary itself) would be taken into account.

**Comment by XL64** [comment]
You wouldn't have to change the `#include`:
"Directories specified with -iquote apply only to the quote form of the directive, #include "file". Directories specified with -I, -isystem, or -idirafter apply to lookup for both the #include "file" and #include <file> directives. " (http://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html) -I seems safer than -isystem as far as I understand here.

**Comment by TotoGaz** [comment]
> So we should enforce -I instead of -isystem for our TPLs

I've just made one test on one platform with `gcc 8.3.0`.

At least for this version, our `-pedantic` option gets ignored for `-isystem` includes. Which is fair since we do not work with the same rules. (see https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html option `-pedantic`) 

By hand, I've tried to modify `-isystem` into `-I` (for the record on one `vtk` include), and it bursts with some 
```
In file included from /workrd/SCR/GEOSX/install/gcc8/GEOSX_TPL-173-714-9d4e8ce/vtk/include/vtk-9.0/vtkObject.h:46,
                 from /workrd/SCR/GEOSX/install/gcc8/GEOSX_TPL-173-714-9d4e8ce/vtk/include/vtk-9.0/vtkCellArray.h:139,
                 from ../coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp:23:
/workrd/SCR/GEOSX/install/gcc8/GEOSX_TPL-173-714-9d4e8ce/vtk/include/vtk-9.0/vtkSetGet.h:829:46: error: extra ‘;’ [-Wpedantic]
   vtkAbstractTypeMacro(thisClass, superclass);                                                     \
                                              ^
/workrd/SCR/GEOSX/install/gcc8/GEOSX_TPL-173-714-9d4e8ce/vtk/include/vtk-9.0/vtkXMLUnstructuredDataWriter.h:41:3: note: in expansion of macro ‘vtkTypeMacro’
   vtkTypeMacro(vtkXMLUnstructuredDataWriter, vtkXMLWriter);
   ^~~~~~~~~~~~
In file included from /workrd/SCR/GEOSX/install/gcc8/GEOSX_TPL-173-714-9d4e8ce/vtk/include/vtk-9.0/vtkXMLUnstructuredGridWriter.h:34,
                 from ../coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp:30:
/workrd/SCR/GEOSX/install/gcc8/GEOSX_TPL-173-714-9d4e8ce/vtk/include/vtk-9.0/vtkXMLUnstructuredDataWriter.h:41:59: error: extra ‘;’ [-Wpedantic]
   vtkTypeMacro(vtkXMLUnstructuredDataWriter, vtkXMLWriter);
```
It's obvious that we'll never deal with this. Let's stay with the `-isystem` with what it implies.

Closing as "_won't fix_".
