### ISSUE TITLE
Merging VTK Mesh Generator

### ISSUE THREAD

**Issue by TotoGaz** [GEOSX/GEOSX#1751]
Merging https://github.com/GEOSX/GEOSX/pull/1453 will require to deal with multiple issues.

- [x] Upgrade `vtk` to 9.0.3
- [x] ~~Upgrade `BLT` if necessary~~ Actually useless, proper VTK deployment was enough.
- [x] Merge `feature/mazuyer/vtkMeshGenerator` with `develop` and fix the last issues

Currently, I think I've found why the linking with `vtk` was not working on some targets.
I've been able to reproduce the issue in the `pangea2` docker, and I could find the proper fix for this (on my box).

I'm getting lost with all the PR and branches and submodule updates in multiple repositories.

I'd like to go step by step. Upgrading `vtk` should be OK for `develop` and I'd like to go with this first.
It's a bugfix version of the `9.0.0-rc3` we're using. It's something we may need, whatever the status of https://github.com/GEOSX/GEOSX/pull/1453. It may require some dependency work...

Then, I'll be able to be sure that BLT upgrade is still required.
We've been testing multiple things before finding the good `vtk` fix that I'd like some extra checks.
I'll check at that moment if it's better to split PRs again.

@joshua-white @herve-gross Do you agree with this schedule?

**Comment by joshua-white** [comment]
I have no issues with being systematic, so this sounds like a good plan.  There is urgency to get this capability in, but as long as we are making sustained progress, I don't see any advantage to taking risks with a mega-merge.

**Comment by herve-gross** [comment]
This is a good plan, yes. Upgrading VTK will be needed regardless, so let's proceed with this first. The BLT upgrade, you will be the best judge. I simply hope that the merge of the `VTKMeshGenerator` branch into `develop` will not take us down a complex path because of all the recent changes to `develop`. But the plan is good, good luck with its execution. Keep us posted.

**Comment by TotoGaz** [comment]
> I simply hope that the merge of the `VTKMeshGenerator` branch into `develop` will not take us down a complex path because of all the recent changes to `develop`.

At first glance, I think it should not be, since it plugs into an interface I did not touch. I'll have to dive deeper to be sure.
