### ISSUE TITLE
 Installing GEOSX in UBUNTU. 

### ISSUE THREAD

**Issue by sinaheidari22** [GEOSX/GEOSX#1753]
Hello, 
I am trying to install GEOSX in UBUNTU. 
While I was going for  : 
  " cd thirdPartyLibs "
  " python scripts/config-build.py -hc ../GEOSX/host-configs/your-platform.cmake -bt Release" 

to build he TPLs, I got this error:

Traceback (most recent call last):
  File "scripts/config-build.py", line 90, in <module>
    assert os.path.exists( cachefile ), "Could not find cmake cache file '%s'." % cachefile
AssertionError: Could not find cmake cache file '/home/codes/GEOSX/host-configs/your-platform.cmake'.

Could you please help me on this.

Thank you,

**Comment by XL64** [comment]
Hello, you have to chose an existing config file your-platform has to be replaced by one corresponding to your machine.

**Comment by sinaheidari22** [comment]
> Hello, you have to chose an existing config file your-platform has to be replaced by one corresponding to your machine.

I appreciate your quick response.
