### ISSUE TITLE
[Feature] Make XML preprocessor MPI-aware

### ISSUE THREAD

**Issue by klevzoff** [GEOSX/GEOSX#1776]
**What is the requested feature?**
Would be great if XML preprocessor was safe for launching via `mpirun`.

**Is your request related to a specific problem?**
I started using preprocessor heavily (it's great for maintaining families of test cases!). One thing that popped up is that, while `geosx_preprocessed` is a safe replacement for `geosx` in serial, it's not safe for launching via `mpirun` because every rank tries to write the preprocessed file at the same time. It sort of still works fine in practice with small number of processes, but it's subject to a data race, where some ranks could already launch `geosx` and try to consume the file while others are still overwriting it. To be clear, I've yet to observe this in practice with `geosx` specifically, but the XML validation script is already throwing exceptions.

**Describe the solution you'd like**
Perhaps `xml_processor.py` could take an (optional) dependency on `mpi4py`, detect when being called from an MPI job and have only one rank do the preprocessing and output of resulting XML, locking other ranks on a barrier until completion.

**Describe alternatives you've considered**
One can run the preprocessor manually and then launch the MPI job with only `geosx`. That's slightly less convenient.

**Comment by cssherman** [comment]
@klevzoff - I've just ran into this myself, and agree entirely.  I'm not sure how to do this under bash, but if we were to require mpi4py as a pre-requisite for geosx_xml_tools, I could limit the processing to the root rank.  I could probably make this an optional dependency if this package causes issues.

**Comment by TotoGaz** [comment]
Dealing with this properly using `mpi4py` could be interesting _w.r.t._ to `pygeosx` too?!

**Comment by cssherman** [comment]
@TotoGaz - Exactly.  This is what I've done in pygeosx_tools.xml  (https://github.com/GEOSX/GEOSX/blob/develop/src/coreComponents/python/modules/pygeosx_tools_package/pygeosx_tools/xml.py#L1)

**Comment by cssherman** [comment]
While testing this approach out, I've found that importing mpi4py causes some odd issues.  After preprocessing completes, when I try to call GEOSX, I get errors that look like this:

srun: error: quartz2: tasks 0-35: Exited with exit code 141

Thsi I'm suspicious that this is due to the way python is handling the mpi environment.  Be default mpi4py attempts to initialize the environment when we request the problem rank, and tries to finalize it when it destructor is called.  Any thoughts @TotoGaz ?

**Comment by klevzoff** [comment]
@cssherman I think the following way of importing might help:
```py
import mpi4py
mpi4py.rc.finalize = False
from mpi4py import MPI
...
```

**Comment by cssherman** [comment]
@klevzoff - I already tried that modification out unfortunately...

**Comment by cssherman** [comment]
Using a file lock approach could also work.  Do either of you have any experience with the various packages that do this in python @klevzoff @TotoGaz ?

**Comment by klevzoff** [comment]
I have used `lockfile` package in the distant past, but it seems deprecated now, although there are alternatives. It worked fine for a small number of processes, but I have no idea how well it scales for massive MPI jobs.

**Comment by TotoGaz** [comment]
> Using a file lock approach could also work. Do either of you have any experience [...]

I'd say that file lock (Are we talking about the `flock` linux feature?) is not available on plenty of parallel file systems like those we can find on HPC. 🤷  (or it may exists, but not activated) Not 100% sure, but this does not look like a good approach.

**Comment by TotoGaz** [comment]
I'm no expert of the `mpi4py` or of the way `geosx` is handling its `MPI` stuff, but are we sure that both `geosx` and `mpi4py` are dealing appropriately with communicators? Do we want those communicators to be the same? Or different?

For instance, in
```python
from mpi4py import MPI
comm = MPI.COMM_WORLD
```
is `comm` related to `MPI_COMM_GEOSX`? Does is have to be?

That would be the first thing I check.

**Comment by cssherman** [comment]
I don't think that we need to worry about any differences between ``comm`` and ``MPI_COMM_GEOSX``, as we simply need to limit the xml processing to one rank.  Also, I've checked to see if a significant delay between processes (from 0 - 10 s), and GEOSX doesn't seem bothered at all.

Something that might work here is a minimal pygeosx run script that handles the xml processing

**Comment by TotoGaz** [comment]
OK. It's just that `mpi4py.rc.finalize = False` makes sense if we share the same `comm`, doesn't i?

**Comment by klevzoff** [comment]
Resolved
