### ISSUE TITLE
[Bug] Imported mesh and internal mesh do not provide same results using coupled solver Poromechanics

### ISSUE THREAD

**Issue by alexandrebtessael** [GEOSX/GEOSX#1799]
Hello,
I tried to use the coupled solver SinglePhasePoromechanics on 2x2x2 cube model based on the example provided in your documentation : https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/basicExamples/poromechanics/Example.html

My goal was to check if my import of a cube2x2x2.msh file would provide the same results as when I use the InternalMesh with this specific coupling solver. The internal mesh and the imported mesh have the same dimensions Nx = Ny = Nz = 2, Dx = Dy = Dz = 0.5m and only using hexahedral elements. All the parameters of the simulations are the same.

The only differences are that I use the PamelaMeshGenerator to import the .msh file. And I define the regions where I apply my boundary conditions directly in the .msh file using "Physical names". I also defined a box using Geometry to specify the "all" in setNames. But when I visualize the results in PARAVIEW, I obtain weird results :
- the total displacement along X axis is the same
- the pressure evolution is the same
- but the total displacement along the Y and Z axis is different (see screenshots below where results are performed on a 10x10x10 cube but this behaviour is the same for 2x2x2 cube)

![GitHub_issue](https://user-images.githubusercontent.com/87317386/157002531-8810b08b-a3d0-4c01-9af4-902c741a4a57.png)

I also tried to change the definition of the regions in another test with the Geometry boxes but the results obtained with the imported mesh are the same as above.

I want to understand why I can't obtain the same results when the difference in these simulations is the mesh being created internally or being imported. I performed the same test with the solver SolidMechanicsLagrangianSSLE. With this solver, I didn't have a difference in results.

The files that I used can be downloaded here : 
https://filesender.renater.fr/?s=download&token=1dab0126-5251-4ca3-984a-d2e46dec6212

Thank you for taking time to read this and to help me solve this problem.
Have a good day.

**Comment by jhuang2601** [comment]
@alexandrebtessael For this 1D consolidation case, the displacement in the lateral direction (along Y and Z axis) should be zero. If checking the magnitude of these two displacement fields from GEOSX runs, they are in the range of 10^-14 (infinitesimal small), which is acceptable for your tests with both internal and external mesh. As long as the displacement along X axis is the same, I would conclude the results are identical for your tests with different mesh. So does the pore pressure distribution.

**Comment by alexandrebtessael** [comment]
Thank you for your answer @jhuang2601, I was not sure about it. I'll be more careful about these ranges of values in the future.
Best regards.
