### ISSUE TITLE
`Group::m_wrappers[name]` can be different from `Group::m_wrappers[name]->getName()`

### ISSUE THREAD

**Issue by TotoGaz** [GEOSX/GEOSX#1804]
When registering some `wrappers`, the `name` provided to register the `wrapper` can different from the actual name `wrapper.getName()` of the `wrapper`.

```c++
WrapperBase & Group::registerWrapper( string const & name,
                                      std::unique_ptr< WrapperBase > wrapper )
{
  return *m_wrappers.insert( name, wrapper.release(), true );
}
```

I always thought of `Group::m_wrappers` as an optimized container that was duplicating the `name` to get better performances for some data access. (Quite here and there in the code, it looks like I'm not alone).

To emphasize the issue, this PR https://github.com/GEOSX/GEOSX/pull/1803 kills GEOSX when an inconsistency is introduced (I'm not 100% sure I've intercepted the only path to inconsistent registrations).

Unit tests do not pass: 22 of them fail with errors like.
```
90: ***** Rank 0: Internal error! Key wrapper name "granite_stress" does not match its real name "stress".
91: ***** Rank 0: Internal error! Key wrapper name "model_stress" does not match its real name "stress".
92: ***** Rank 0: Internal error! Key wrapper name "granite_stress" does not match its real name "stress".
... SNIP ...
156: ***** Rank 0: Internal error! Key wrapper name "fluid1_phaseFraction" does not match its real name "phaseFraction".
157: ***** Rank 0: Internal error! Key wrapper name "water_density" does not match its real name "density".
159: ***** Rank 0: Internal error! Key wrapper name "fluid1_phaseFraction" does not match its real name "phaseFraction".
```
I think you guess the pattern.

Do we accept this or do we want to fix it?

**Comment by jhuang2601** [comment]
@TotoGaz Thanks for pinpoint this inconsistence. I think a fix is necessary.
