### ISSUE TITLE
[Bug] Problem during initialization with "large" meshgrid and single process running

### ISSUE THREAD

**Issue by labesse40** [GEOSX/GEOSX#1811]
**Describe the bug**
There is an issue when running `geosx` or `pygeosx` with a "large" meshgrid, with single/not enough? process. The program will either run indefinitely (geosx) or crash (pygeosx). 

**To Reproduce**
1. geosx executable : 
       Run one process any `xml` with any solver with a grid ~ 100x100x100. 
2. pygeosx : 
       Run a python script, one process, with at least a `pygeosx.initialize()` call with any `xml` having the same property as above.

**Expected behavior**
1. geosx executable : 
       Program should run indefinitely during initialization.
2. pygeosx : 
       Program should crash with a `malloc error` pointing to `umpire`.

**Screenshots**
1. geosx : 
![Screenshot from 2022-03-09 10-47-42](https://user-images.githubusercontent.com/77446520/157416291-65575104-1d22-4b0c-82dc-15480ea5bdd0.png)
Program has been left running for ~3h with no changes.

2. pygeosx : 
![Screenshot from 2022-03-08 17-55-11](https://user-images.githubusercontent.com/77446520/157416157-2847bd51-22d1-4741-a225-fa44e2a2445b.png)

This problem occurs on CPU, but also GPU (pangea3) when running with only 1 GPU.

Also we noticed a large increase of the memory allocated for initialization, @acitrain and @sframba  are trying to isolate which commit it's coming from (seems to be end of January). This can be related to this issue.

**Comment by TotoGaz** [comment]
> Also we noticed a large increase of the memory allocated for initialization, @acitrain and @sframba are trying to isolate which commit it's coming from (seems to be end of January). This can be related to this issue.

It's most probably #1418 which was reorganizing code and aiming at making the things generic for corner point grids.
@jeannepellerin already witnessed that. And she's also working on this topic too.

**Comment by labesse40** [comment]
> > Also we noticed a large increase of the memory allocated for initialization, @acitrain and @sframba are trying to isolate which commit it's coming from (seems to be end of January). This can be related to this issue.
> 
> It's most probably #1418 which was reorganizing code and aiming at making the things generic for corner point grids. @jeannepellerin already witnessed that. And she's also working on this topic too.

Yes It's actually related to this one. We've discussed this earlier in the office :). I can close the Issue since reducing the maxFacesPerNodes solves this issue and since @jeannepellerin is working on it.
Thanks

**Comment by TotoGaz** [comment]
@labesse40 Actually, there is an interesting work to be done to make this overallocation optional/customizable/dependent on solver. One interest of #1418 was to centralize this feature to make future evolutions easier. So if you have time and interest, go! (But keep in touch with @jeannepellerin not to duplicate work!)
