### ISSUE TITLE
VTK output doesn't work - Unexpected segmentation fault

### ISSUE THREAD

**Issue by CapucineLegentil** [GEOSX/GEOSX#1816]
**Describe the bug**
I'm unable to use VTK outputs (I tried Tutorial3)

**To Reproduce**
1. Take the third Tutorial (FieldCaseTutorial3_*.xml)
2. Run it 
3. See error 
_"Time: 0s, dt:1e+07s, Cycle: 0
Received signal 11: Segmentation fault"_

**Expected behavior**
It should run

**Simulation log**
I attached the simulation log containing the unexpected segmentation fault.

**Platform (please complete the following information):**
- Machine Ubuntu 20.04 - 8 cores - Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz, 1200 MHz - graphics card nVidia GK106GL [Quadro K4000]
- Compiler: gcc 9.4.0
- GEOSX Version cbd51110e

**Additional context**
[simulation_log.txt](https://github.com/GEOSX/GEOSX/files/8225676/simulation_log.txt)

**Comment by klevzoff** [comment]
@cssherman this loop is the suspect:
https://github.com/GEOSX/GEOSX/blob/cd912f3d64f533bcdaa9969385bb5f3de1fae766/src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp#L119-L122
It needs to be a RAJA host kernel launch (using `serialPolicy`). If using CUDA, `coord` might to point to device data, and this error is to be expected. Other than this, I can't see anything wrong there.

**Comment by cssherman** [comment]
I am working on a pull request that touches vtk, so I will do some testing to see if I can reproduce the error

**Comment by TotoGaz** [comment]
Could not reproduce; the `vtk` outputs are working kind of OK now.
