### ISSUE TITLE
[Feature] Add ReadTheDocs to CI

### ISSUE THREAD

**Issue by bmhan12** [GEOSX/GEOSX#1845]
Make ReadTheDocs build as part of our CI checks.

ReadTheDocs does have a feature so you can trigger RTD builds on pull requests:
https://docs.readthedocs.io/en/stable/pull-requests.html

It's a toggle on/off with the option to make PR builds private or public to everyone.
I think we want public, so the PR author can view the build.

@rrsettgast, I have admin access, should I flip it on?

**Comment by rrsettgast** [comment]
Yes!!!

**Comment by bmhan12** [comment]
RTD builds should be on for PR's now.

![RTD on](https://user-images.githubusercontent.com/53839862/159976842-3a812a68-bd0a-4076-a867-f6be3282f55d.PNG)

**Comment by klevzoff** [comment]
@rrsettgast @bmhan12 I got a failed check in https://github.com/GEOSX/GEOSX/pull/1847, but when I click it I get a 404 page from readthedocs. It would be nice to have the ability to see the error log and re-trigger the build, but I imagine it's impossible without giving everyone RTD admin access?
