### ISSUE TITLE
BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES

### ISSUE THREAD

**Issue by Ron-Wang** [GEOSX/GEOSX#1863]
**BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES**
The bug appears when I use a model of about 4,000,000 nodes. I wonder if I can do sth to avoid it. 
![BAD](https://user-images.githubusercontent.com/18233013/161027936-bc9a2429-266d-4c98-8ace-50c7ac047290.png)
Thanks a lot!

**Comment by klevzoff** [comment]
Hi @Ron-Wang,

Could you please check out the latest version of `develop` branch (don't forget to run `git submodule update` after you do), rebuild and try again? I don't know with full certainty the reason for the above error, but if my suspicion is correct, a fix for it was just merged.

**Comment by Ron-Wang** [comment]
Thanks a lot @klevzoff ,
I think it is the old version which I updated in Feb 2022 causes this problem. I am going to try the latest version of develop branch.

**Comment by Ron-Wang** [comment]
@klevzoff , I feel so sorry to bother you again. I have updated GEOSX to the lasted version, and it still happens this bug. I wonder if my hardware is not fit or the mesh model (about 4,000,000 nodes) has some problem.

**Comment by TotoGaz** [comment]
This issue surely relates to `PAMELA` that we do not support anymore.
Please try again with `vtk` and reopen an issue if needed.
Thank you for your comprehension!
