### ISSUE TITLE
Add a `FieldPath` struc/class to identify the fields

### ISSUE THREAD

**Issue by TotoGaz** [GEOSX/GEOSX#1904]
Related to discussion [here](https://github.com/GEOSX/GEOSX/pull/1878#discussion_r857052469).

Instead of using raw `string` to identify the fields, let's build up some `FieldPath class` that will be easier to manipulate (and more robust).

@rrsettgast @CusiniM

**Comment by wrtobin** [comment]
@rrsettgast #1963 should have resolved this, yeah?
