### ISSUE TITLE
Hard-coded Python3.8 paths in `CMakeLists.txt` for pygeosx

### ISSUE THREAD

**Issue by kcgthb** [GEOSX/GEOSX#1939]
The `CMakeLists.txt` file for `pygeosx` has hard-coded `python3.8` paths, which will generate an error during compilation when another version of Python is used:
https://github.com/GEOSX/GEOSX/blob/11cbe7d403087bd341f0986598269f6bb5d67bb4/src/pygeosx/CMakeLists.txt#L24-L28

For instance, if Python 3.9 is used and detected by CMake:
```
CMakeCache.txt:_Python3_EXECUTABLE:INTERNAL=/share/software/user/open/python/3.9.0/bin/python3.9
CMakeCache.txt:_Python3_INCLUDE_DIR:INTERNAL=/share/software/user/open/python/3.9.0/include/python3.9
```
compilation fails with this message:
```
[100%] Linking CXX shared library ../lib/pygeosx.so
ln: target ‘/tmp/GEOSX/build-sherlock-release/lib/PYGEOSX/lib/python3.8/site-packages/’ is not a directory: No such file or directory
make[2]: *** [lib/pygeosx.so] Error 1
make[2]: *** Deleting file `lib/pygeosx.so'
make[1]: *** [pygeosx/CMakeFiles/pygeosx.dir/all] Error 2
make: *** [all] Error 2
```
because the Python files are generated in `lib/PYGEOSX/lib/python3.9/site-packages`:
```
/tmp/GEOSX/build-sherlock-release/lib/PYGEOSX/lib/python3.9/
└── site-packages
    ├── easy_install.py
    ├── pip
    ├── pip-20.2.3.dist-info
    ├── pkg_resources
    ├── __pycache__
    ├── setuptools
    └── setuptools-49.2.1.dist-info
```

**Comment by klevzoff** [comment]
By a strange coincidence (?), a PR was created earlier today that addresses this: https://github.com/GEOSX/GEOSX/pull/1938/files#r885858130

**Comment by kcgthb** [comment]
Ah, but that's brilliant, and timely! Thanks!

**Comment by TotoGaz** [comment]
Hello @kcgthb Could you tell us if the path patch pointed by @klevzoff indeed solves your issue?
That would help us in the validation process! 😉
