### ISSUE TITLE
[Cleanup] Python code formatting tools

### ISSUE THREAD

**Issue by cssherman** [GEOSX/GEOSX#1941]
**Describe the issue**
We currently are not enforcing formatting for python files within the repository.  Doing some research, [Black](https://black.readthedocs.io/en/stable/getting_started.html) seems to be a popular choice.  It can be applied recursively to a folder to format or check python files:

```
python -m black src
python -m black --check src
```

Any thoughts @TotoGaz ?

**Comment by cssherman** [comment]
Yes, Black is designed to be very 'opinionated', and only has a couple of available configuration options (such as desired line length).  It's devs are also super picky about the stability of the formatted files, so that would be useful for avoiding diffs in our code.

The three biggest format choices include:
1) Preferring double-quotes
2) Preferring tuple arguments (`if (x == 1):` instead of `if x == 1:`)
3) Preferring code is on single lines for short commands, and on multiple lines for long commands:

```python
# Top is preferred
fn(a, b, c)
fn(a,
   b,
   c)

# Top is preferred
fn(
  "some very long argument",
  "some other very long argument"
)
fn('some very long argument', 'some other very long argument')

```

**Comment by TotoGaz** [comment]
Are you satisfied by what's `Black` produces on our code base?
