### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by hari12125** [GEOSX/GEOSX#1945]
Please describe your issue here.  Try to be as specific as possible.
I attempted to configure and build third party libraries by using darwin-clang.cmake  file. But the result is configuration incomplete. I have attached the error file at the end.
[error.txt](https://github.com/GEOSX/GEOSX/files/8840526/error.txt)

**Comment by TotoGaz** [comment]
Hello @hari12125 and welcome to GEOSX.
Looks like `MPI` is not found. Do you have it installed or defined at the location of your `darwin-clang.cmake`?

**Comment by hari12125** [comment]
Hello @TotoGaz
Eventhough MPI is found,  I am getting configuration to be incomplete with darwin-clang.cmake . However, with your-platform.cmake provided in the documentation,I could complete configuration but I got some errors when I entered the make command. I have attached the outputs of all three cases at the end.
[darwinclang.txt](https://github.com/GEOSX/GEOSX/files/8859571/darwinclang.txt)
[yourplatform.txt](https://github.com/GEOSX/GEOSX/files/8859576/yourplatform.txt)
[make.txt](https://github.com/GEOSX/GEOSX/files/8859579/make.txt)

**Comment by hari12125** [comment]
I am building on linux ( Ubuntu 20.04.4 LTS ).   I have attached the log below
[CMakeOutput.log](https://github.com/GEOSX/GEOSX/files/8865147/CMakeOutput.log)

**Comment by TotoGaz** [comment]
Hello, it looks like the log indicates to install `flex`.
You can also have a glance at https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/buildGuide/Prerequisites.html where you'll find some additional information!

**Comment by TotoGaz** [comment]
Why does line `in tpls.cmake GEOSX_TPL_DIR=/home/bharath/Pictures/Loan/SEM2/Dissertation/codes/thirdPartyLibs` appear twice in the log?
Does an `umpire` folder exist in `/home/bharath/Pictures/Loan/SEM2/Dissertation/codes/thirdPartyLibs/install-your-platform-release`?

**Comment by hari12125** [comment]
By following the instructions under Building GEOSX , I added the line (include("/home/bharath/Pictures/Loan/SEM2/Dissertation/codes/GEOSX/host-configs/tpls.cmake") in your-platform.cmake. May be this line gives same result as the following line  include(${CMAKE_CURRENT_LIST_DIR}/tpls.cmake)

 I found few folders like hdf5,conduit and doxygen etc., but there is no folder like umpire in /home/bharath/Pictures/Loan/SEM2/Dissertation/codes/thirdPartyLibs/install-your-platform-release

**Comment by TotoGaz** [comment]
> added the line

You need to include `tpls.cmake` only once.

> I found few folders like hdf5,conduit and doxygen etc., but there is no folder like umpire in /home/bharath/Pictures/Loan/SEM2/Dissertation/codes/thirdPartyLibs/install-your-platform-release

You should get something like

```
adiak    conduit  hdf5        metis     raja         superlu_dist  vtk
caliper  doxygen  hypre       parmetis  silo         trilinos
chai     fmt      mathpresso  pugixml   suitesparse  uncrustify
```
If you don't then maybe the TPL phase did not run OK?

**Comment by hari12125** [comment]
I have also got the same but  the error message during GEOSX configuration asks about umpire directory.
![tpl](https://user-images.githubusercontent.com/106927603/173115960-fc28db3c-0fa6-48bf-91c1-6ef690813126.png)

**Comment by TotoGaz** [comment]
it's there
```
root@def699f6d994:/opt/GEOSX_TPL # find . -name umpire -type d
./chai/include/umpire
./chai/share/umpire
```
and
```
root@def699f6d994:/opt/GEOSX_TPL # ls chai/include/umpire/
Allocator.hpp  ResourceManager.hpp  TypedAllocator.inl  config.hpp  strategy
Allocator.inl  ResourceManager.inl  Umpire.hpp          op          tpl
Replay.hpp     TypedAllocator.hpp   alloc               resource    util
```

**Comment by hari12125** [comment]
Thank you @TotoGaz  for your help. I have successfully completed the compilation and installation. I hope that I would also get an opportunity to solve your problems.
