### ISSUE TITLE
[Bug] Memory allocation error during coupling simulation

### ISSUE THREAD

**Issue by alexandrebtessael** [GEOSX/GEOSX#1964]
**Describe the bug**
I'm trying to run a simulation coupling MultiphasePoromechanics and CompositionalMultiphaseReservoir on an imported cube_5x5x5.msh with Hex elements. When I start the simulation, I hit a memory allocation error (see screenshot below).

**To Reproduce**
1. Download files at https://filesender.renater.fr/?s=download&token=26c4784d-e528-4786-97e0-f9479d904fc2
2. Run cube_poromechanics.xml with geosx
3. See error : 
`geosx: malloc.c:2539: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed`

**Screenshot**
![image](https://user-images.githubusercontent.com/87317386/176396402-978f2774-d252-418d-a6e0-a77db46b39c4.png)

**Comment by francoishamon** [comment]
Hello @alexandrebtessael 

I am sorry, but the combination of `MultiphasePoromechanics` and `CompositionalMultiphaseReservoir` is not available yet (i.e., poromechanics with Peaceman wells is not supported). We are working on it, but we need a little bit more time to make it ready.

In the meantime, you can just combine `MultiphasePoromechanics` with `CompositionalMultiphaseFVM`, and use `SourceFlux` to mimic the behavior of Peaceman wells. It should work well and produce results similar to what you would have with Peaceman wells. Examples are here:
https://github.com/GEOSX/GEOSX/blob/78a5887dff70f1ecdb54d16ed92513524050cc13/inputFiles/poromechanics/PoroElastic_deadoil_3ph_baker_2d.xml#L28
and
https://github.com/GEOSX/GEOSX/blob/78a5887dff70f1ecdb54d16ed92513524050cc13/inputFiles/compositionalMultiphaseFlow/co2_flux_3d.xml#L172 

If you don't mind, I am going to close the issue unless you have other questions

**Comment by alexandrebtessael** [comment]
Hello @francoishamon 

I tried with your solution and it worked as I expected. Thanks a lot for your answer.
