### ISSUE TITLE
ThirdPartyLibs compilation error when compiling Chai library with gcc 11.2

### ISSUE THREAD

**Issue by agel1** [GEOSX/GEOSX#1972]
**Describe the bug**
Compilation error encountered when compiling thirdPartyLibs's Chai library with gcc 11.2 on perlmutter@NERSC system and a temporary fix I tried as shown below:

> cd /global/common/software/m41XX/Codes/GEOS/thirdPartyLibs
> python scripts/config-build.py -hc ../GEOSX/host-configs/perlmutter-gcc.cmake -bt Release

> cd build-perlmutter-gcc-release
Directory: /global/common/software/m41XX/Codes/GEOS/thirdPartyLibs/build-perlmutter-gcc-release

> make | & tee MAKE.LOG
...
…....
Codes/GEOS/thirdPartyLibs/build-perlmutter-gcc-release/chai/src/chai/src/tpl/umpire/src/umpire/util/allocation_statistics.cpp:31:46: error: 'numeric_limits' is not a member of 'std'
   31 |                     (total_free_space + std::numeric_limits<float>::epsilon());
      |                                              ^~~~~~~~~~~~~~
/global/common/software/m4186/Codes/GEOS/thirdPartyLibs/build-perlmutter-gcc-release/chai/src/chai/src/tpl/umpire/src/umpire/util/allocation_statistics.cpp:31:61: error: expected primary-expression before 'float'
   31 |                     (total_free_space + std::numeric_limits<float>::epsilon());
      |                                                             ^~~~~
/global/common/software/m4186/Codes/GEOS/thirdPartyLibs/build-perlmutter-gcc-release/chai/src/chai/src/tpl/umpire/src/umpire/util/allocation_statistics.cpp:31:61: error: expected ')' before 'float'
   31 |                     (total_free_space + std::numeric_limits<float>::epsilon());
      |                     ~                                       ^~~~~
      |                                                             )

I tried a temporary fix by adding #include <limits> in the following source file:
> vi /global/common/software/m41XX/Codes/GEOS/thirdPartyLibs/build-perlmutter-gcc-release/chai/src/chai/src/tpl/umpire/src/umpire/util/allocation_statistics.cpp

...
#include "umpire/util/allocation_statistics.hpp"
**#include \<limits\>**  //AIKE added to address compilation error 
#include \<algorithm\>
...
......

After the above addition thirdPartyLibs seems to compile successfully but I wasn't sure if this was an issue specific to perlmutter@NERSC as I didn't encounter it when compiling on another Ubuntu based Linux box.

I wanted to share this issue in case the above or some other revision might make the compilation more robust towards different platforms including those as new as perlmutter like systems.

**Platform (please complete the following information):**
- Machine perlmutter@NERSC 
- Compiler: 
gcc (GCC) 11.2.0 20210728 (Cray Inc.)
- GEOSX Version 0.2.0

**Additional context**

**Comment by TotoGaz** [comment]
Our `travis-ci` now supports `gcc-11.2`, so the bug should be closed now.
