### ISSUE TITLE
[Other] Compilation error when compiling core GEOSX with gcc 11.2 and error changing depending on make -j value

### ISSUE THREAD

**Issue by agel1** [GEOSX/GEOSX#1973]
Hi,

I have been trying to compile GEOSX suite on one of the NERSC systems ( https://www.nersc.gov/systems/perlmutter/ ).
After managing to compile the thirdPartyLibs successfully and configuring the compilation for GEOSX core, I attempted to start the compilation but it failed with the following messages:

============================================
> make |& tee MAKE.LOG
Scanning dependencies of target generate_version
[  0%] Generating version information
[  0%] Built target generate_version
Scanning dependencies of target mainInterface
[  0%] Building CXX object coreComponents/mainInterface/CMakeFiles/mainInterface.dir/GeosxState.cpp.o
[  0%] Building CXX object coreComponents/mainInterface/CMakeFiles/mainInterface.dir/ProblemManager.cpp.o
/global/common/software/m4186/Codes/GEOS/GEOSX/src/coreComponents/mainInterface/ProblemManager.cpp: In member function 'virtual void geosx::ProblemManager::setSchemaDeviations(geosx::xmlWrapper::xmlNode, geosx::xmlWrapper::xmlNode, geosx::integer)':
/global/common/software/m4186/Codes/GEOS/GEOSX/src/coreComponents/mainInterface/ProblemManager.cpp:336:23: error: loop variable 'machineName' of type 'const string&' {aka 'const std::__cxx11::basic_string<char>&'} binds to a temporary constructed from type 'const char* const' [-Werror=range-loop-construct]
  336 |   for( string const & machineName : {"quartz", "lassen"} )
      |                       ^~~~~~~~~~~
/global/common/software/m4186/Codes/GEOS/GEOSX/src/coreComponents/mainInterface/ProblemManager.cpp:336:23: note: use non-reference type 'const string' {aka 'const std::__cxx11::basic_string<char>'} to make the copy explicit or 'const char* const&' to prevent copying
cc1plus: all warnings being treated as errors
make[2]: *** [coreComponents/mainInterface/CMakeFiles/mainInterface.dir/build.make:93: coreComponents/mainInterface/CMakeFiles/mainInterface.dir/ProblemManager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:7076: coreComponents/mainInterface/CMakeFiles/mainInterface.dir/all] Error 2
make: *** [Makefile:158: all] Error 2
============================================

Another interesting finding was when I use make -j 2 the error is encountered at a different level as shown below:
============================================
> make -j 2 |& tee MAKE2.LOG
.....
.....
Scanning dependencies of target PVTPackage
[  4%] Building CXX object coreComponents/constitutive/PVTPackage/PVTPackage/source/CMakeFiles/PVTPackage.dir/pvt/pvt.cpp.o
[  4%] Building CXX object coreComponents/constitutive/PVTPackage/PVTPackage/source/CMakeFiles/PVTPackage.dir/MultiphaseSystem/BlackOilMultiphaseSystem.cpp.o
In file included from /global/common/software/m4186/Codes/GEOS/GEOSX/src/coreComponents/constitutive/capillaryPressure/JFunctionCapillaryPressure.hpp:25,
                 from /global/common/software/m4186/Codes/GEOS/GEOSX/src/coreComponents/constitutive/capillaryPressure/JFunctionCapillaryPressure.cpp:19:
/global/common/software/m4186/Codes/GEOS/GEOSX/src/coreComponents/functions/TableFunction.hpp: In member function 'geosx::real64 geosx::TableFunction::KernelWrapper::interpolateLinear(const IN_ARRAY&, OUT_ARRAY&&) const [with IN_ARRAY = const double*; OUT_ARRAY = double*&]':
/global/common/software/m4186/Codes/GEOS/GEOSX/src/coreComponents/functions/TableFunction.hpp:590:33: error: 'dCornerValue_dInput' may be used uninitialized [-Werror=maybe-uninitialized]
  590 |         dCornerValue_dInput[kk] *= ( dim == kk ) ? dWeights_dInput[dim][corner] : weights[dim][corner];
/global/common/software/m4186/Codes/GEOS/GEOSX/src/coreComponents/functions/TableFunction.hpp:578:12: note: 'dCornerValue_dInput' declared here
  578 |     real64 dCornerValue_dInput[maxDimensions];
      |            ^~~~~~~~~~~~~~~~~~~

============================================

System: perlmutter@NERSC
Compiler: gcc (GCC) 11.2.0 20210728 (Cray Inc.)
GEOSX version 0.2

Any suggestions to solve the above compilation error will be very helpful.

Thanks for your time and suggestions in advance.

Aytekin

P.S.
Attached below shows the prior step output which shows the python setup for GEOSX:

> python scripts/config-build.py -hc ../GEOSX/host-configs/perlmutter-gcc.cmake -bt Release
[config-build.py]:[INFO]: Using host config file: '/global/common/software/m4186/Codes/GEOS/GEOSX/host-configs/perlmutter-gcc.cmake'.
[config-build.py]:[INFO]: Build path is: build-perlmutter-gcc-release
[config-build.py]:[INFO]: Creating build directory '/global/common/software/m4186/Codes/GEOS/GEOSX/build-perlmutter-gcc-release'...
[config-build.py]:[INFO]: Install directory '/global/common/software/m4186/Codes/GEOS/GEOSX/install-perlmutter-gcc-release' already exists. Deleting...
[config-build.py]:[INFO]: Creating install path '/global/common/software/m4186/Codes/GEOS/GEOSX/install-perlmutter-gcc-release'...
[config-build.py]:[INFO]: Extracting cmake entry from host config file /global/common/software/m4186/Codes/GEOS/GEOSX/host-configs/perlmutter-gcc.cmake
[config-build.py]:[INFO]: Could not find a cmake entry in host config file. Using ${PATH}.
[config-build.py]:[INFO]: Changing to build directory '/global/common/software/m4186/Codes/GEOS/GEOSX/build-perlmutter-gcc-release'
[config-build.py]:[INFO]: Executing cmake line: 'cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/global/common/software/m4186/Codes/GEOS/GEOSX/install-perlmutter-gcc-release -C/global/common/software/m4186/Codes/GEOS/GEOSX/host-configs/perlmutter-gcc.cmake /global/common/software/m4186/Codes/GEOS/GEOSX/src'
loading initial cache file /global/common/software/m4186/Codes/GEOS/GEOSX/host-configs/perlmutter-gcc.cmake
in tpls.cmake GEOSX_TPL_DIR=/global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release
-- HDF5_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/hdf5
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Check for working C compiler: /opt/cray/pe/gcc/11.2.0/bin/gcc
-- Check for working C compiler: /opt/cray/pe/gcc/11.2.0/bin/gcc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/cray/pe/gcc/11.2.0/bin/g++
-- Check for working CXX compiler: /opt/cray/pe/gcc/11.2.0/bin/g++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BLT Version: 0.5.1
-- CMake Version: 3.17.0
-- CMake Build Type: Release
-- CMake Executable: /usr/bin/cmake
-- Setting CMAKE_CXX_EXTENSIONS to OFF
-- Standard C++14 selected
-- Found Git: /global/homes/a/aike/bin/git  
-- Git Support is ON
-- Git Executable: /global/homes/a/aike/bin/git
-- Git Version: 
-- MPI Support is ON
-- FindMPI Enabled  (ENABLE_FIND_MPI == ON)
-- Found MPI_C: /global/common/software/m3169/perlmutter/openmpi/4.1.1-ucx-1.11.1-cuda-11.3.0/gnu/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /global/common/software/m3169/perlmutter/openmpi/4.1.1-ucx-1.11.1-cuda-11.3.0/gnu/lib/libmpi.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- BLT MPI Compile Flags:  -pthread
-- BLT MPI Include Paths:  /global/common/software/m3169/perlmutter/openmpi/4.1.1-ucx-1.11.1-cuda-11.3.0/gnu/include
-- BLT MPI Libraries:      /global/common/software/m3169/perlmutter/openmpi/4.1.1-ucx-1.11.1-cuda-11.3.0/gnu/lib/libmpi.so
-- BLT MPI Link Flags:     SHELL:-Wl,-rpath -Wl,/global/common/software/m3169/perlmutter/openmpi/4.1.1-ucx-1.11.1-cuda-11.3.0/gnu/lib -Wl,--enable-new-dtags -pthread
-- MPI Executable:       /usr/bin/srun
-- MPI Num Proc Flag:    -n
-- MPI Command Append:   
-- OpenMP Support is ON
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- OpenMP Compile Flags: -fopenmp
-- OpenMP Link Flags:    -fopenmp
-- CUDA Support is OFF
-- HIP Support is OFF
-- Sphinx support is ON
-- Found Sphinx: /usr/bin/sphinx-build  
-- Valgrind support is ON
-- Found Valgrind: /usr/bin/valgrind  
-- AStyle support is ON
-- Failed to locate AStyle executable (missing: ASTYLE_EXECUTABLE) 
-- ClangFormat support is ON
-- Failed to locate ClangFormat executable (missing: CLANGFORMAT_EXECUTABLE) 
-- Uncrustify support is OFF
-- Yapf support is ON
-- Failed to locate Yapf executable (missing: YAPF_EXECUTABLE) 
-- CMakeFormat support is ON
-- Failed to locate CMakeFormat executable (missing: CMAKEFORMAT_EXECUTABLE) 
-- Cppcheck support is ON
-- Failed to locate Cppcheck executable (missing: CPPCHECK_EXECUTABLE) 
-- ClangQuery support is ON
-- Failed to locate ClangQuery executable (missing: CLANGQUERY_EXECUTABLE) 
-- ClangTidy support is ON
-- Failed to locate ClangTidy executable (missing: CLANGTIDY_EXECUTABLE) 
-- C Compiler family is GNU
-- Adding optional BLT definitions and compiler flags
-- Enabling all compiler warnings on all targets.
-- Enabling treatment of warnings as errors on all targets.
-- Fortran support disabled.
-- CMAKE_C_FLAGS flags are:   -Wall -Wextra  -Wl,-rpath=/opt/cray/pe/gcc/11.2.0/snos/lib64/  -Werror 
-- CMAKE_CXX_FLAGS flags are:   -Wall -Wextra  -Wl,-rpath=/opt/cray/pe/gcc/11.2.0/snos/lib64/     -Werror 
-- CMAKE_EXE_LINKER_FLAGS flags are:  
-- Google Test Support is ON
-- Google Mock Support is OFF
-- Found PythonInterp: /global/common/software/nersc/pm-2022q2/sw/python/3.9-anaconda-2021.11/bin/python3.9 (found version "3.9.7") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Google Benchmark Support is ON
-- Failed to find LLVM FileCheck
-- git Version: v0.0.0
-- Version: 0.0.0
-- Performing Test HAVE_CXX_FLAG_STD_CXX11
-- Performing Test HAVE_CXX_FLAG_STD_CXX11 - Success
-- Performing Test HAVE_CXX_FLAG_WALL
-- Performing Test HAVE_CXX_FLAG_WALL - Success
-- Performing Test HAVE_CXX_FLAG_WEXTRA
-- Performing Test HAVE_CXX_FLAG_WEXTRA - Success
-- Performing Test HAVE_CXX_FLAG_WSHADOW
-- Performing Test HAVE_CXX_FLAG_WSHADOW - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC
-- Performing Test HAVE_CXX_FLAG_PEDANTIC - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS - Success
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32 - Failed
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED_DECLARATIONS
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED_DECLARATIONS - Success
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED - Success
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WD654
-- Performing Test HAVE_CXX_FLAG_WD654 - Failed
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY - Failed
-- Performing Test HAVE_CXX_FLAG_COVERAGE
-- Performing Test HAVE_CXX_FLAG_COVERAGE - Success
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes

Processing GeosxOptions.cmake
CMAKE_HOST_SYSTEM_NAME = Linux
CMAKE_SYSTEM_NAME = Linux
CMAKE_HOST_APPLE = 
-- GEOSX_LA_INTERFACE = Hypre
CMAKE_CXX_COMPILER_ID = GNU
localIndex is an alias for int
globalIndex is an alias for long long int
GEOSX_LOCALINDEX_TYPE_FLAG = 0
GEOSX_GLOBALINDEX_TYPE_FLAG = 2
CMAKE_CXX_FLAGS =  -Wall -Wextra  -Wl,-rpath=/opt/cray/pe/gcc/11.2.0/snos/lib64/     -Werror  -fopenmp  -Wall -Wextra -Wpedantic -pedantic-errors -Wshadow -Wfloat-equal -Wcast-align -Wcast-qual 
GEOSX_LINK_PREPEND_FLAG=-Wl,--whole-archive
GEOSX_LINK_POSTPEND_FLAG=-Wl,--no-whole-archive
Leaving GeosxOptions.cmake

-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /usr/lib64/libopenblas.so  
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- BLAS_LIBRARIES = /usr/lib64/libopenblas.so
-- LAPACK_LIBRARIES = /usr/lib64/libopenblas.so;-pthread;-lm;-ldl
-- HDF5_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/hdf5
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/hdf5/lib/libhdf5.a;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so (found version "1.12.1")  
-- CONDUIT_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/conduit
-- Conduit was built with HDF5 Support
-- Looking for HDF5 at: /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/hdf5
-- HDF5_DIR_REAL=/global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/hdf5
-- Checking that found HDF5_INCLUDE_DIRS are in HDF5_DIR
-- HDF5_INCLUDE_DIRS=/global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/hdf5/include
--  /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/hdf5/include includes HDF5_DIR (/global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/hdf5)
--  /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/hdf5/include includes HDF5_REAL_DIR ()
-- HDF5 is parallel:  TRUE
-- Found Conduit: /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/conduit (found version 0.8.2)
-- CONDUIT_VERSION             = 0.8.2
-- CONDUIT_INSTALL_PREFIX      = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/conduit
-- CONDUIT_IMPORT_ROOT         = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/conduit
-- CONDUIT_USE_CXX11           = TRUE
-- CONDUIT_USE_FMT             = TRUE
-- CONDUIT_INCLUDE_DIRS        = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/conduit/include/conduit
-- CONDUIT_FORTRAN_ENABLED     = FALSE
-- CONDUIT_PYTHON_ENABLED      = 
-- CONDUIT_PYTHON_EXECUTABLE   = 
-- CONDUIT_PYTHON_MODULE_DIR   = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/conduit/python-modules/
-- Conduit Relay features:
--  CONDUIT_RELAY_WEBSERVER_ENABLED = TRUE
--  CONDUIT_RELAY_HDF5_ENABLED      = TRUE
--  CONDUIT_HDF5_DIR                = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/hdf5
--  CONDUIT_RELAY_ADIOS_ENABLED     = FALSE
--  CONDUIT_ADIOS_DIR               = 
--  CONDUIT_RELAY_SILO_ENABLED      = FALSE
--  CONDUIT_SILO_DIR                = 
--  CONDUIT_RELAY_MPI_ENABLED       = TRUE
-- Conduit imported targets: conduit::conduit conduit::conduit_mpi
-- SILO_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/silo
-- PUGIXML_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/pugixml
-- RAJA_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/raja
-- UMPIRE_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/chai
-- CHAI_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/chai
-- ADIAK_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/adiak
-- CALIPER_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/caliper
-- MATHPRESSO_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/mathpresso
-- METIS_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/metis
-- PARMETIS_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/parmetis
-- SUPERLU_DIST_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/superlu_dist
-- SUITESPARSE_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/suitesparse
-- HYPRE_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/hypre
-- TRILINOS_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/trilinos
-- Not using PETSc
-- VTK_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/vtk
-- Found MPI: TRUE (found version "3.1") found components: C 
-- FMT_DIR = /global/common/software/m4186/Codes/GEOS/thirdPartyLibs/install-perlmutter-gcc-release/fmt
-- Not using uncrustify.
-- Not using doxygen.
-- Not building pygeosx.
-- thirdPartyLibs = blas;lapack;hdf5;conduit::conduit;silo;pugixml;RAJA;umpire;chai;adiak;caliper;mathpresso;metis;parmetis;superlu_dist;suitesparse;hypre;trilinos;vtk;fmt::fmt
adding optionparser library
-- LvArray bounds checking disabled.
adding PVTPackage library
-- Adding PAMELAMeshGenerator sources and headers
-- PAMELA is configured with GEOSX !
-- Configuring PAMELA with metis of GEOSX tpls
-- Configuring PAMELA with MPI
-- adding PAMELA_Library
-- PAMELA with following definitions : -DWITH_MPI;-DWITH_METIS;-DWITH_METIS;-DWITH_MPI
-- Adding VTKMeshGenerator sources and headers
Using cmake  Object Libraries
-- Found directory at src/externalComponents/newComponentTemplate
-- Configuring GEOSX version 0.2.0
-- Configuring done
-- Generating done
-- Build files have been written to: /global/common/software/m4186/Codes/GEOS/GEOSX/build-perlmutter-gcc-release

**Comment by wrtobin** [comment]
At the very least the first compilation issue (without `-j`) seems to have been resolved in the past few months via #1929

The other issue (with `TableFunction.hpp`) might still require changes for gcc, though it may also have also been resolved (regardless the code there now doesn't have the issue the compiler is erroring-out on -- though the compiler may not know that). This isn't specific to using `-j`, though.

I'm going to close this issue, if you're still having any issues with your gcc build feel free to open a new issue for the specific failure you're encountering.
