### ISSUE TITLE
Updating section Using an External Mesh

### ISSUE THREAD

**Issue by castelletto1** [GEOSX/GEOSX#2015]
With PR #1992 we switched to using VTK external meshes for all input file examples provided in the repo. Ultimately, VTK meshes will become the default and we would ditch PAMELA (including stop linking to it). When the transition is completed, actions needed will be:
- updating section [Using an External Mesh](https://geosx-geosx.readthedocs-hosted.com/en/latest/coreComponents/mesh/docs/Mesh.html#using-an-external-mesh) in the User Guide
- updating [tutorial 2](https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/tutorials/step02/Tutorial.html)
- removing PAMELA tests located [here](https://github.com/GEOSX/GEOSX/tree/develop/inputFiles/singlePhaseFlow/pamela_test)

**Comment by TotoGaz** [comment]
@castelletto1 Isn't this issue done?
