### ISSUE TITLE
[Other] Example run failing: 'GEOSX/examples/compositionalFlow/kernelTest/kernelTest.xml'

### ISSUE THREAD

**Issue by ajikmr** [GEOSX/GEOSX#2040]
Example 'kernelTest.xml' is not running. Throws error with 'Release' build:

********************
Rank 0: Total number of nodes:3442951
  Region1/cb1/fluid1 is allocated with 1 quadrature points.
  Region1/cb1/rock is allocated with 1 quadrature points.
  Region1/cb1/relperm is allocated with 1 quadrature points.
***** ERROR
***** LOCATION: /home/**********/GEOSX/src/coreComponents/constitutive/ConstitutiveManager.cpp:72
***** Controlling expression (should be false): constitutiveGroup->hasGroup( constitutiveRelationInstanceName )
***** Rank 0: Error! The constitutive relation rockPerm has already been registered on the subRegion cb1. Make sure that the same constitutive model is not listed as a material on a region both as a stand-alone one and as part of a compound constitutive model.

** StackTrace of 7 frames **
Frame 0: geosx 
Frame 1: geosx::ProblemManager::setRegionQuadrature(geosx::dataRepository::Group&, geosx::constitutive::ConstitutiveManager const&, geosx::mapBase<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, int, std::integral_constant<bool, true> > const&) 
Frame 2: geosx::ProblemManager::applyNumericalMethods() 
Frame 3: geosx::ProblemManager::problemSetup() 
Frame 4: geosx::GeosxState::initializeDataRepository() 
Frame 5: main 
Frame 6: __libc_start_main 
Frame 7: _start
************************************

Debug build of 'geosx' gets stuck in mesh generation part for a long time.

System-build details: Ubuntu 20.04, gcc

**Comment by CusiniM** [comment]
The input file seems to be old and in need for an update? Is there a particular reason why you are trying to run this one? 
The error does suggest what the issue is though. The Region block should be.

```xml
<CellElementRegion
      name="Region1"
      cellBlocks="{ cb1 }"
      materialList="{ fluid1, rock, relperm }"/>


In general though, I suggest to use `xml` files contained in the `inputFiles` folder rather than in `examples` one.

**Comment by ajikmr** [comment]
Thanks a lot. It is working with the suggested changes.
