### ISSUE TITLE
[Other] Import mesh from ECLIPSE GRDECl/EGRID or .vtu file

### ISSUE THREAD

**Issue by ajikmr** [GEOSX/GEOSX#2047]
I am trying to import SMEAHEIA mesh (https://co2datashare.org/dataset/smeaheia-dataset)  into geosx. I have Eclipse output files (.EGRID and .GRDECL) as well as .vtu for the grid. I have tried importing from each of three formats. (.vtu file using VTKMesh, and .EGRID/.GRDECL using PAMELAMesh). All give same error. Also, I am able to make runs using OPM simulator with ECLIPSE input files. 

Though online manual briefly mentions this issue, could you let me know how to import information from ECLIPSE files and handle zero/negative volume? Preferable import all mesh, perm(x,y,z), and poro values. Can we also import well details from EGRID file.

I am showing error using '.EGRID' file below. Importing using other file formats give similar error.

*****
PAMELAMesh 'mesh1': reading mesh from /home/***********************************/SMEAHEIA.EGRID
0 >>> **********************************************************************
0 >>>                          PAMELA Library Import tool                   
0 >>> **********************************************************************
0 >>> ECLIPSE GRDECL FORMAT IDENTIFIED
0 >>> *** Importing Eclipse mesh format file SMEAHEIA
0 >>> *** Parsing EGRID file
0 >>> ---- Parsing /home/*******************************************/SMEAHEIA.EGRID
0 >>> Keyword FILEHEAD found.
0 >>>      o FILEHEAD processed. Dimension is 100
0 >>> Keyword GRIDUNIT found.
0 >>>      o GRIDUNIT processed. Dimension is 2
0 >>> Keyword GRIDHEAD found.
0 >>>      o GRIDHEAD Found
0 >>> 1844400 numbers of cells
0 >>> Keyword COORD    found.
0 >>>      o COORD processed
0 >>> Keyword ZCORN    found.
0 >>>      o ZCORN processed
0 >>> Keyword ACTNUM   found.
0 >>>      o ACTNUM processed
0 >>> 1510500 numbers of active cells
0 >>> Keyword ENDGRID  found.
0 >>>      o ENDGRID processed. Dimension is 0
0 >>> *** Parsing INIT file
0 >>> ---- Parsing /home/***************************/SMEAHEIA.INIT
0 >>> Keyword INTEHEAD found.
0 >>>      o INTEHEAD processed. Dimension is 411
0 >>> Keyword LOGIHEAD found.
0 >>>      o Skipping LOGIHEAD
0 >>> Keyword DOUBHEAD found.
0 >>>      o DOUBHEAD processed. Dimension is 229
0 >>> Keyword PORV     found.
0 >>>      o PORV processed. Dimension is 1844400
0 >>> Keyword DEPTH    found.
0 >>>      o DEPTH processed. Dimension is 1510500
0 >>> Keyword DX       found.
0 >>>      o DX processed. Dimension is 1510500
0 >>> Keyword DY       found.
0 >>>      o DY processed. Dimension is 1510500
0 >>> Keyword DZ       found.
0 >>>      o DZ processed. Dimension is 1510500
0 >>> Keyword PORO     found.
0 >>>      o PORO processed. Dimension is 1510500
0 >>> Keyword PERMX    found.
0 >>>      o PERMX processed. Dimension is 1510500
0 >>> Keyword PERMY    found.
0 >>>      o PERMY processed. Dimension is 1510500
0 >>> Keyword PERMZ    found.
0 >>>      o PERMZ processed. Dimension is 1510500
0 >>> Keyword NTG      found.
0 >>>      o NTG processed. Dimension is 1510500
0 >>> Keyword TRANX    found.
0 >>>      o TRANX processed. Dimension is 1510500
0 >>> Keyword TRANY    found.
0 >>>      o TRANY processed. Dimension is 1510500
0 >>> Keyword TRANZ    found.
0 >>>      o TRANZ processed. Dimension is 1510500
0 >>> Keyword TABDIMS  found.
0 >>>      o TABDIMS processed. Dimension is 100
0 >>> Keyword TAB      found.
0 >>>      o TAB processed. Dimension is 3413
0 >>> Keyword EQLNUM   found.
0 >>>      o EQLNUM processed. Dimension is 1510500
0 >>> Keyword PVTNUM   found.
0 >>>      o PVTNUM processed. Dimension is 1510500
0 >>> Keyword SATNUM   found.
0 >>>      o SATNUM processed. Dimension is 1510500
0 >>> Keyword FIPNUM   found.
0 >>>      o FIPNUM processed. Dimension is 1510500
0 >>> *** RESTART file not found
0 >>> *** Converting content into internal mesh format
0 >>> 1844400  total GRDECL hexas
0 >>> 1510500  initially set as active hexas
0 >>> 0  active but flat hexas (->deactivated)
0 >>> 0  active but ill-shaped hexas (->deactivated)
0 >>> 0  duplicated hexas
0 >>> 1510500  will actually be used in the GEOSX mesh
0 >>> *** Generating TPFA data structure from imported content
0 >>> *** Filling mesh with imported properties
0 >>> *** Generating TPFA adjacency graph
0 >>> *** Generating NNCs adjacency graph
0 >>> *** Generating Well & Completion data
0 >>> *** Creating Polygons from Polyhedra...
0 >>> 4576105 polygons have been created
0 >>> *** Done
0 >>> *** Perform partitioning...
0 >>> TRIVIAL partioning...
0 >>> Ghost elements...
0 >>> Clean mesh...
0 >>> *** Done...
0 >>> Clean Adjacency...
0 >>> *** Done...
PAMELAMesh 'mesh1': generating GEOSX mesh data structure
Importing cell block DEFAULT_HEX
***** ERROR
***** LOCATION: /home/**************/GEOSX/src/coreComponents/mesh/CellElementSubRegion.cpp:347
***** Controlling expression (should be false): m_elementVolume[k] <= 0.0
***** Rank 0: Negative volume for element 0 type 8 in subregion DEFAULT_HEX

StackTrace of 6 frames 
Frame 0: geosx::CellElementSubRegion::calculateElementGeometricQuantities(geosx::NodeManager const&, geosx::FaceManager const&) 
Frame 1: geosx::ProblemManager::generateMesh() 
Frame 2: geosx::ProblemManager::problemSetup() 
Frame 3: geosx::GeosxState::initializeDataRepository() 
Frame 4: main 
Frame 5: __libc_start_main 
Frame 6: _start 
=====

******************
Error using '.GRDECL' file
*****************
PAMELAMesh 'mesh1': reading mesh from /home/**************************/SMEAHEIA.GRDECL
0 >>> **********************************************************************
0 >>>                          PAMELA Library Import tool                   
0 >>> **********************************************************************
0 >>> ECLIPSE GRDECL FORMAT IDENTIFIED
0 >>> *** Importing Eclipse mesh format file SMEAHEIA
0 >>> ---- Parsing /home/*************************/SMEAHEIA.GRDECL
0 >>>      o SPECGRID or DIMENS Found
0 >>>      o COORD Found
0 >>>      o ZCORN Found
0 >>>      o ACTNUM Found
0 >>> *** Converting into internal mesh format
0 >>> 1844400  total GRDECL hexas
0 >>> 1510500  initially set as active hexas
0 >>> 0  active but flat hexas (->deactivated)
0 >>> 0  active but ill-shaped hexas (->deactivated)
0 >>> 0  duplicated hexas
0 >>> 1510500  will actually be used in the GEOSX mesh
0 >>> *** Filling mesh with imported properties
0 >>> *** Creating Polygons from Polyhedra...
0 >>> 4576105 polygons have been created
0 >>> *** Done
0 >>> *** Perform partitioning...
0 >>> TRIVIAL partioning...
0 >>> Ghost elements...
0 >>> Clean mesh...
0 >>> *** Done...
0 >>> Clean Adjacency...
0 >>> *** Done...
PAMELAMesh 'mesh1': generating GEOSX mesh data structure
Importing cell block DEFAULT_HEX
***** ERROR
***** LOCATION: /home/***********************/GEOSX/src/coreComponents/mesh/CellElementSubRegion.cpp:347
***** Controlling expression (should be false): m_elementVolume[k] <= 0.0
***** Rank 0: Negative volume for element 0 type 8 in subregion DEFAULT_HEX

 StackTrace of 6 frames 
Frame 0: geosx::CellElementSubRegion::calculateElementGeometricQuantities(geosx::NodeManager const&, geosx::FaceManager const&) 
Frame 1: geosx::ProblemManager::generateMesh() 
Frame 2: geosx::ProblemManager::problemSetup() 
Frame 3: geosx::GeosxState::initializeDataRepository() 
Frame 4: main 
Frame 5: __libc_start_main 
Frame 6: _start 
=====

System-build: Ubuntu20.04 - gcc9.4

**Comment by ajikmr** [comment]
Along the same lines, in the sample input problem 'inputFiles/compositionalMultiphaseWell/staircase_co2_wells_hybrid_3d.xml' even though globalCompFraction is imported from .vtu mesh, the values need to be re-entered in FieldSpecification (0.005, 0.995). This is the same value as in .vtu mesh, then why do we need to enter it again.

Also, if we change values in FieldSpecification  to (0.004, 0.996) then the values in .vtu file (i.e. 0.005, 0.995) are basically never used.

**Comment by klevzoff** [comment]
Hi @ajikmr ,

"Negative volume " typically means cell-node connectivity is not specified in correct order in the mesh file (such as nodes being listed in clockwise order when counter-clockwise is expected, etc.). Paraview may still be able to display the mesh correctly in some cases, but we expect the node order to be correct according to VTK specifications, such as in the attached image.

![image](https://user-images.githubusercontent.com/1550292/189084334-6e1a27ae-b49e-4a24-ad6c-eb1f4a1af9cc.png)

A simple way to check if that is the case is to load the vtk mesh in Paraview and add a "Python calculator" filter with expression `volume(inputs[0])`. If the produced volume field displays negative values, the input file must be fixed. One way to do it is to save the VTK file in an ASCII-based format, load the cell-node connectivity as a 2D array in some processing tool (I've used MATLAB for this), swap the columns as necessary and write it back. I can't comment on how to fix this in the GRDECL file as I'm not well familiar with the file format.


> Along the same lines, in the sample input problem 'inputFiles/compositionalMultiphaseWell/staircase_co2_wells_hybrid_3d.xml' even though globalCompFraction is imported from .vtu mesh, the values need to be re-entered in FieldSpecification (0.005, 0.995). This is the same value as in .vtu mesh, then why do we need to enter it again.
> 
> Also, if we change values in FieldSpecification to (0.004, 0.996) then the values in .vtu file (i.e. 0.005, 0.995) are basically never used.

The input file has redundancy for readability purposes, so that it is not necessary to visualize the mesh to find out what initial conditions are in the test problem. Initial conditions specified in `FieldSpecications` block take priority over anything imported from the mesh file. You should be to remove or comment out some of those initial conditions if your intent is to load initial conditions with the mesh. 

> Preferable import all mesh, perm(x,y,z), and poro values. Can we also import well details from EGRID file.

Permeability/porosity import is definitely supported with `VTKMesh`, and probably with PAMELA, but note that PAMELA import will eventually be phased out. Wells currently cannot be imported and must be fully specified in the XML input.

**Comment by ajikmr** [comment]
Hello @klevzoff ,
Thanks for detailed response. It makes things clear. I will try to fix relevant files.

As key focus of GEOSX is CO2 sequestration related studies, it will be good to have some 'ready' benchmark cases such as Sleipner, Smeaheia etc. It will help other researchers to quickly try and compare different options.
Thanks!
