### ISSUE TITLE
Error during the compilation of caliper:  Undefined reference to 'dl_sym'

### ISSUE THREAD

**Issue by MedAdh42** [GEOSX/GEOSX#2065]
The compilation of the thirdPartyLibs fails when trying to dynamically link caliper producing the following error: 
```
usr/bin/ld: undefined reference to 'dl_sym'
```
linker command failed with exit code 1 (use -v see invocation)   

**To Reproduce**
I'm using an Ubuntu22.04LTS virtual machine (on Windows11 using Hyper-V) and I've used the following host-config.cmake:

```
**detect host and name the configuration file**
site_name(HOST_NAME)
set(CONFIG_NAME "linux-gnu-x86_64" CACHE PATH "")
message("CONFIG_NAME = ${CONFIG_NAME}")

**set paths to C, C++, and Fortran compilers. Note that while GEOSX does not contain any Fortran code**
**some of the third-party libraries do contain Fortran code. Thus a Fortran compiler must be specified.**
set(CMAKE_C_COMPILER "/bin/gcc" CACHE PATH "")
set(CMAKE_CXX_COMPILER "/bin/g++" CACHE PATH "")
set(CMAKE_Fortran_COMPILER "/bin/gfortran" CACHE PATH "")
set(ENABLE_FORTRAN OFF CACHE BOOL "" FORCE)

**enable MPI and set paths to compilers and executable.**
**Note that the MPI compilers are wrappers around standard serial compilers.**
**Therefore, the MPI compilers must wrap the appropriate serial compilers specified**
**in CMAKE_C_COMPILER, CMAKE_CXX_COMPILER, and CMAKE_Fortran_COMPILER.**
set(ENABLE_MPI ON CACHE BOOL "")
set(MPI_C_COMPILER "/usr/bin/mpicc" CACHE PATH "")
set(MPI_CXX_COMPILER "/usr/bin/mpic++" CACHE PATH "")
set(MPI_Fortran_COMPILER "/usr/bin/mpifort" CACHE PATH "")
set(MPIEXEC "/usr/bin/mpirun" CACHE PATH "")

**disable CUDA and OpenMP**
set(CUDA_ENABLED OFF CACHE BOOL "" FORCE)
set(ENABLE_OPENMP OFF CACHE BOOL "" FORCE)

**enable PAMELA and PVTPackage**
set(ENABLE_PAMELA ON CACHE BOOL "" FORCE)
set(ENABLE_PVTPackage ON CACHE BOOL "" FORCE)

**enable tests**
set(ENABLE_GTEST_DEATH_TESTS ON CACHE BOOL "" FORCE )

**define the path to your compiled installation directory**
set(GEOSX_TPL_DIR "/home/ubuntu22/GeosX" CACHE PATH "")
**let GEOSX define some third party libraries information for you**
include(${CMAKE_CURRENT_LIST_DIR}/tpls.cmake)
```

**Dependencies**
I've installed the following packages using sudo apt : 
```
sudo apt-get install git cmake build-essential libgl1-mesa-dev libxt-dev libopenmpi-dev libtbb-dev ninja-build
```
in addition to flex and bison (seem to be required for doxygen) using :
```
sudo apt-get install flex bison 
 ```

**Expected behavior**
the compilation of caliper builds all targets but fails to link them, my research on the issue lead me to this answer [dl_sym](https://stackoverflow.com/questions/20369672/undefined-reference-to-dlsym) where it said and  i quote " Apparently it has something to do with recent versions of gcc/ld linking with --as-needed by default"

**Platform:**
- Machine : Ubuntu22.04LTS (virtual machine on windows 11)
- Compiler:  gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
- GEOSX Version:  0.2.0

**Comment by TotoGaz** [comment]
Can you try to update `caliper`? @karimifard told me that he succeeded in compiling on ubuntu 22.04 with a more recent version of caliper.

#1889 should be done at some moment 🤷

**Comment by Mohamed-AIDAHI** [comment]
@TotoGaz thanks for the response, I've tried with latest version and the issue solved.

**Comment by Mohamed-AIDAHI** [comment]
Indeed using the latest version solves this issue but a similar one arises for trilinos, so i used a newer version (13.0.0) and it worked.
