### ISSUE TITLE
Pack/unpack overloads

### ISSUE THREAD

**Issue by herve-gross** [GEOSX/GEOSX#2072]
**What needs to be documented?**
The pack/unpack functions come in several overloaded flavors. More documentation could be helpful for debugging these.

**What sort of documentation would help?**
A DevGuide page specifically on pack/unpack methods.

**What are the deficiencies of the existing documentation?**
We currently assume that the interface is self-explanatory.

**Additional notes or context**
Doc Day tasks. From feedback with @jiemeng-total

**Comment by wrtobin** [comment]
We have a longstanding issue to completely rework the packing hierarchy, and presumably documentation should be included in that process. #1098 

When that is likely to happen is indeterminate at the moment.
