### ISSUE TITLE
[Other] Failure 6% of unit test on ubuntu22.04

### ISSUE THREAD

**Issue by Mohamed-AIDAHI** [GEOSX/GEOSX#2089]
I have succesfully compiled GEOSX, but after running the unit tests some of them failed

The following tests FAILED:
	  2 - blt_mpi_smoke (Failed)
	110 - testLinearAlgebra_Matrices (Failed)
	111 - testLinearAlgebra_Vectors (Failed)
	112 - testLinearAlgebra_ExternalSolvers (Failed)
	113 - testLinearAlgebra_KrylovSolvers (Failed)
	128 - testDofManager (Failed)
	129 - testLAIHelperFunctions (Failed)
	161 - testNeighborCommunicator_mpi (Failed)
	162 - testVTKImport_mpi (Failed)
	165 - testHDFParallelFile (Failed)
	178 - testDoxygenCheck (Failed)

I've built it on an Ubuntu22.04 virtual machine (running it on windows 11 using Hyper-V), the used compiler GCC (Ubuntu 11.2.0-19ubuntu1) 11.2.0. I should mention that due to some compilation errors I've had to use newer versions of some of the TPLs (see this [issue](https://github.com/GEOSX/GEOSX/issues/2065#issue-1375016116))

**Comment by Mohamed-AIDAHI** [comment]
[LastTest.log](https://github.com/GEOSX/GEOSX/files/9690922/LastTest.log)

Here it is.

**Comment by TotoGaz** [comment]
Looks like it's most often the error message is
```
128/178 Testing: testDofManager
128/178 Test: testDofManager
Command: "/bin/mpirun" "-n" "2" "/home/ubuntu22/GeosX/GEOSX/build-ubuntu22-release/tests/testDofManager" "-x" "2"
Directory: /home/ubuntu22/GeosX/GEOSX/build-ubuntu22-release/coreComponents/unitTests/linearAlgebraTests
"testDofManager" start time: Oct 01 20:09 CEST
Output:
----------------------------------------------------------
--------------------------------------------------------------------------
A prefix was supplied to mpirun that only contained slashes.

This is a fatal error; mpirun will now abort.  No processes were launched.
--------------------------------------------------------------------------
<end of output>
Test time =   0.01 sec
----------------------------------------------------------
Test Failed.
"testDofManager" end time: Oct 01 20:09 CEST
"testDofManager" time elapsed: 00:00:00
----------------------------------------------------------
```
Looks like there is a path issue in `mpirun`? I don't know, but it looks like your installation is at stake?

w.r.t. `testDoxygenCheck` ther message is
```
----------------------------------------------------------
error: Problems running latex. Check your installation or look for typos in _formulas.tex and check _formulas.log!
dvips: DVI file can't be opened: _formulas.dvi: No such file or directory
error: Problems running dvips. Check your installation!
<end of output>
Test time =  76.58 sec
----------------------------------------------------------
```
which indicates some of the program you may need to install.

**Comment by Mohamed-AIDAHI** [comment]
Regarding the last failed test (testDoxygencheck) all i needed is to install Latex using : sudo apt install texlive-latex-extra.
As for the the other tests there seems to be an issue parsing the MPI command according to this [issue](https://github.com/open-mpi/ompi/issues/5613) when the path to mpirun is /bin/mpirun

**Comment by Mohamed-AIDAHI** [comment]
Just as discussed in this [issue](https://github.com/open-mpi/ompi/issues/5613), when the provided pth to the mpirun executable is '/bin/mpirun' the 'A prefix was supplied to mpirun that only contained slashes.' error arises causing mpirun to abort.

I recompiled the code using 'usr/bin/local' as the MPIEXEC path and the problem was solved.

**Comment by TotoGaz** [comment]
Good news!
