### ISSUE TITLE
Rebuild LC TPLs

### ISSUE THREAD

**Issue by bmhan12** [GEOSX/GEOSX#2103]
third-party libraries need to be rebuilt with new updates.

- PR GEOSX/thirdPartyLibs#200 updated chai and trilinos.
- As part of this PR (GEOSX/LvArray#271), flags were added to host-config quartz-clang@10.0.0 to have GEOSX build with the new library updates.
  - These flags cause current develop to fail on LC with the specific host-config, as the LC third-party library installations have not yet been updated.
  - (Removing the flags will fix the failure)

**Comment by Chaojie-Di** [comment]
When I build the TPL, the terminal crashes (shutdown without error print) when it builds the trilinos. Do you know what's wrong with this?
