### ISSUE TITLE
Error appear when run the 3D_10x10x10_compressible_smoke.xml case

### ISSUE THREAD

**Issue by Chaojie-Di** [GEOSX/GEOSX#2115]
There is the print log:

./build-your-platform-release/bin/geosx -i inputFiles/singlePhaseFlow/3D_10x10x10_compressible_smoke.xml
GEOSX version 0.2.0 (develop, sha1: c3d046a7b)
Adding Mesh: InternalMesh, mesh
Adding Event: PeriodicEvent, solverApplications
Adding Event: PeriodicEvent, outputs
Adding Solver of type SinglePhaseFVM, named SinglePhaseFlow
Adding Geometric Object: Box, source
Adding Geometric Object: Box, sink
Adding Output: Silo, siloOutput
Adding Object CellElementRegion named mainRegion from ObjectManager::Catalog.
mesh: total number of nodes = 1331
mesh: total number of elems = 1000
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh, Level0, mainRegion, cellBlock
mesh/Level0/mainRegion/cellBlock/water allocated 1 quadrature points
mesh/Level0/mainRegion/cellBlock/rock allocated 1 quadrature points
***** ERROR
***** LOCATION: /home/chaojie/code/GEOSX/src/coreComponents/mesh/MeshObjectPath.cpp:215
***** Controlling expression (should be false): !foundMatch
***** Rank 0: Specified name (elementSubRegions) did not find a match with a object in group (elementSubRegions). Objects that are present in (elementSubRegions) are: cellBlock

**Comment by francoishamon** [comment]
This issue has been fixed, the example should run with the latest `develop` commit.

**Comment by Chaojie-Di** [comment]
Ok, thank you
