### ISSUE TITLE
[Bug] GEOSX execution fails for the acoustic solver on VTK files unless the VTKMesh is called "mesh"

### ISSUE THREAD

**Issue by sframba** [GEOSX/GEOSX#2122]
**Describe the bug**
Run GEOSX with a vtk file. GEOSX fails with the following error:
```
***** LOCATION: /(insert path here)/Group.hpp:337
***** Controlling expression (should be false): child == nullptr
***** Rank 0: Group m/domain/MeshBodies doesn't have a child mesh
```
**To Reproduce**
1. run GEOSX with the attached file `test_fail.xml` , which contains a `VTKMesh` object named `mymodel`. Put the the simple mesh `test.vtu` in the same directory.
2. The run fails. if the test is repeated with `test_pass.xml`, which renames the `VTKMesh` object as `mesh`, the test passes

**Expected behavior**
Any `VTKMesh` object name should be allowed.

**Platform (please complete the following information):**
- Any machine 
- Compiler: [e.g. gcc 8.4.1]
- GEOSX develop version
[test.zip](https://github.com/GEOSX/GEOSX/files/9783258/test.zip)

**Comment by klevzoff** [comment]
This is specific to Acoustic solver due to some hard coding going on here: https://github.com/GEOSX/GEOSX/blob/d3d351883195c08686ffff438957fe59a6d916e8/src/coreComponents/physicsSolvers/wavePropagation/AcousticWaveEquationSEM.cpp#L471

**Comment by sframba** [comment]
Good catch Sergey, thanks. I'll change the title. Also, this gives a hint to where the problem might come from 😉
