### ISSUE TITLE
Merging the parallel vtk results remove cells at the rank interfaces

### ISSUE THREAD

**Issue by TotoGaz** [GEOSX/GEOSX#2144]
When a parallel simulation is done, the `vtk` files are written rank by rank.
Sometimes, the user wants to merge those files back into a unique file.

When merging using `paraview` (using `Merge blocks`, selecting option `merge points `), because the ghost cells are explicitly there, `paraview` sometimes removes the cells.
Having those ghost cells can also be an issue when computing statistics over the mesh (ghost cell information is there twice).

A simple 10 x 10 x 10 `Laplace` simulation on 2 ranks end up with something like this:

<img width="459" src="https://user-images.githubusercontent.com/49004943/198751434-054d46cf-ce45-48a0-ac0d-f1cb6241297e.png">

Surely having the ability to selectively write (or not) the ghost cells would help.

@jeannepellerin @AntoineMazuyer

**Comment by klevzoff** [comment]
Just to repeat my sentiment from the Slack thread, I think the default behavior should be **not** writing ghost cells in the output (with an option to enable writing). Literally the first thing I do in any Paraview pipeline is to threshold the dataset on condition `ghostRank < 0` (unless I'm debugging a ghosting issue).

**Comment by TotoGaz** [comment]
As mentioned by @klevzoff and during the meeting, it could make sense no to write the ghost cells during the simulation.

Meanwhile, by generating the `vtk global ids` in `paraview` (`Generate global ids` filter and saving the data), using this script, for the `Laplace` simulation of the ticket, I could merge the data appropriately (proper number of cells and nodes, good volume)... I don't know how the script scales or behaves with large meshes.

<details>
  <summary>A quick and dirty python script</summary>

```python
from vtk.util.numpy_support import (
    vtk_to_numpy,
)
from vtkmodules.numpy_interface import (
    dataset_adapter,
)
from vtkmodules.vtkFiltersGeneral import (
    vtkMergeCells,
)
from vtkmodules.vtkCommonDataModel import (
    vtkUnstructuredGrid,
)
from vtkmodules.vtkIOXML import (
    vtkXMLMultiBlockDataReader,
    vtkXMLUnstructuredGridWriter,
)

reader = vtkXMLMultiBlockDataReader()
reader.SetFileName("results_with_global_ids.vtm")
reader.Update()
mbds = reader.GetOutput()

assert mbds.GetNumberOfBlocks() == 1
b0 = mbds.GetBlock(0)

ugs = []
for ug in dataset_adapter.CompositeDataIterator(b0):
    ugs.append(ug.VTKObject)

max_cells, max_points = [], []
for ug in ugs:
    max_cells.append(vtk_to_numpy(ug.GetCellData().GetGlobalIds()).max())
    max_points.append(vtk_to_numpy(ug.GetPointData().GetGlobalIds()).max())

merged = vtkUnstructuredGrid()

merger = vtkMergeCells()
merger.UseGlobalIdsOn()
merger.UseGlobalCellIdsOn()
merger.SetUnstructuredGrid(merged)

merger.SetTotalNumberOfCells(max(max_cells) + 1)
merger.SetTotalNumberOfPoints(max(max_points) + 1)
merger.SetTotalNumberOfDataSets(len(ugs))

for ug in ugs:
    merger.MergeDataSet(ug)

writer = vtkXMLUnstructuredGridWriter()
writer.SetFileName("merged_results.vtu")
writer.SetInputData(merged)
writer.Write()
```
</details>

If you do not want to generate the global ids using `paraview`, there's something in `mesh_doctor` (that must be adapted).
We could also write the global ids during the simulation instead of removing the ghost cells (we can have both options).

Here are a list of actions; tell me if some of them are already done.
- [ ] Make ghost cells writing in `vtk` conditional
- [ ] Make global cell ids writing in `vtk` possible and conditional
- [ ] Add the proper global ids generation policy in `mesh_doctor`
- [ ] Improve the merging script and put it in `mesh_doctor`

**Comment by TotoGaz** [comment]
@jeannepellerin @AntoineMazuyer The solution proposed by @klevzoff  is even simpler: filter out negative ghost ranks.
Then you can merge them with no problems. The volume is correct, etc.
This can be scripted if we want to of course.

**Comment by TotoGaz** [comment]
If it's working, I think that directly using [vtkThreshold](https://vtk.org/doc/nightly/html/classvtkThreshold.html) can lead to a small implementation on our side. Everything would rely on `vtk` doing it's job.
