### ISSUE TITLE
Face B.C. for temperature

### ISSUE THREAD

**Issue by sytuannguyen** [GEOSX/GEOSX#2163]
**What is the requested feature?**
Face B.C. for temperature

**Is your request related to a specific problem?**
Thermal diffusion and Thermo-poro-mechanical coupling for wellbore problems 

**Describe the solution you'd like**
The face B.C. for pressure should be cloned for temperature, i.e. using faceManager for objectPath.

**Describe alternatives you've considered**

**Additional context**

**Comment by francoishamon** [comment]
Hi @sytuannguyen,

The face boundary condition for temperature is already implemented for the compositional solver, in this [kernel](https://github.com/GEOSX/GEOSX/blob/a485d8e646d9f04cac4f46623a8d778353278550/src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp#L709-L722).
An example in which temperature face boundary condition is used is [here.](https://github.com/GEOSX/GEOSX/blob/a485d8e646d9f04cac4f46623a8d778353278550/inputFiles/thermalMultiphaseFlow/co2_thermal_2d.xml#L203)

For the single-phase flow solver, it is not implemented yet, but the implementation would not be difficult, and would follow exactly the template of the compositional case. Let us know if you need help. I assign the two of us to this issue, it will not be difficult to address.

**Comment by francoishamon** [comment]
@sytuannguyen 
As we just discussed, a simple plan to implement this thermal BC for single-phase flow would be:

- [ ] PR1: updating the style of the current single-phase face BC kernel [here](https://github.com/GEOSX/GEOSX/blob/e645176d47e33055c67342031142351b57ea1eca/src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVMKernels.hpp#L850-L982) in the style of the compositional face BC kernel [here](https://github.com/GEOSX/GEOSX/blob/e645176d47e33055c67342031142351b57ea1eca/src/coreComponents/physicsSolvers/fluidFlow/IsothermalCompositionalMultiphaseFVMKernels.hpp#L982). We will add a kernel class that derives from this [existing class](https://github.com/GEOSX/GEOSX/blob/e645176d47e33055c67342031142351b57ea1eca/src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVMKernels.hpp#L182). This will be a simple, self-contained PR where we only refactor one kernel.
- [ ] PR2: once the single-phase face BC kernel is in the new style, we will add the thermal part. We will follow the recipe used here for the thermal compositional face BC kernel [here](https://github.com/GEOSX/GEOSX/blob/e645176d47e33055c67342031142351b57ea1eca/src/coreComponents/physicsSolvers/fluidFlow/ThermalCompositionalMultiphaseFVMKernels.hpp#L675).
