### ISSUE TITLE
Remove virtual SolverStep and allow for sequential coupling in CoupleSolvers.

### ISSUE THREAD

**Issue by CusiniM** [GEOSX/GEOSX#2176]
**Describe the issue**
The function `solverStep` is defined in each physics solver but it has the exact same implementation for all solvers except:
 - `SolidMechanicsLagrangianFEM`
 - `PhaseFieldFracture`
 - `PhaseFieldDamageFEM`
 - `HydroFractureSolver`
 - the 2 surface generators.

Also, even though we had planned not to have sequentially coupled solvers we do have a few (i.e., the phase field ones and now a thermoporomechanics solver) and it looks like we will have a few more. It would be nice if an API could be defined for sequential coupling as well. 

**Proposed cleanup**
I think we could centralize the implementation of `solverStep` which would not need to be virtual anymore. could be something of the form:

````c++
real64 solverStep( real64 const & time_n, real64 const & dt, const int cycleNumber, DomainPartition & domain );
virtual real64 implicitStep( real64 const & time_n, real64 const & dt, const int cycleNumber, DomainPartition & domain );
virtual real64 explicitStep( real64 const & time_n, real64 const & dt, const int cycleNumber, DomainPartition & domain );
````

````c++
real64 SolverBase::solverStep( real64 const & time_n,
                               real64 const & dt,
                               const int cycleNumber,
                               DomainPartition & domain )
{
  GEOSX_MARK_FUNCTION;
  
  switch( m_params.scheme )
  {
    case solutionStrategy::implicit:
    {
      dt_return = implicitStep(  );
      break;
    }
     case solutionStrategy::explicit:
    { 
       dt_return = explicitStep(   );
       break;
    }

  return dt_return;
}

real64 SolverBase::implicitStep( real64 const & time_n,
                                                       real64 const & dt,
                                                       const int cycleNumber,
                                                       DomainPartition & domain )
{

  
  real64 dt_return = dt;

  // setup monolithic coupled system
  setupSystem( domain, m_dofManager, m_localMatrix, m_rhs, m_solution );
  
  implicitStepSetup( time_n, dt, domain );

  dt_return = nonlinearImplicitStep( time_n, dt, cycleNumber, domain );

  implicitStepComplete( time_n, dt_return, domain );
}

```` 

And then add to `CoupledSolverBase` a function  like:

````c++
virtual real64 implicitStep( real64 const & time_n, real64 const & dt,const int cycleNumber, DomainPartition & domain ) override final;

real64 CoupledSolverBase::implicitStep( real64 const & time_n,
                                                                     real64 const & dt,
                                                                     const int cycleNumber,
                                                                    DomainPartition & domain )
{
   switch( m_params.couplingType )
  {
    case solutionStrategy::FIM:
    {
      dt_return =  SolverBase::implicitStep(  );
      break;
    }
     case solutionStrategy::Sequential:
    { 
       dt_return = sequentialStep(   ); // this could be used by all sequential solvers like PhaseFieldFracture, HydroFractureSolver (not exactly sequential but kind of poromechanics -> propagation solver), etc... 
       break;
    }
}
````

**Additional context**
This would require a solution for the surface generators and for the only `linearImplicit` solve we have.

**Comment by rrsettgast** [comment]
I agree with the intent. The only problem I see is the variation of what `implicit` vs `explicit`means. For instance, solid mechanics have multiple implicit methods:
1. quasi-static
2. implicit Newmark
3. alpha methods
4. etc...

and various explicit schemes:
1. explicit Newark
2. leapfrog
3. explicit predictor-corrector methods
4. etc...

This is why things are kicked down to the derived classes of `SolverBase` to define their own set available options. Most of the methods are probably not physics specific, but rather based on the characteristics of the governing equations, but I am not sure that this is always the case.

**Comment by CusiniM** [comment]
> I agree with the intent. The only problem I see is the variation of what `implicit` vs `explicit`means. For instance, solid mechanics have multiple implicit methods:
> 
>     1. quasi-static
> 
>     2. implicit Newmark
> 
>     3. alpha methods
> 
>     4. etc...
> 
> 
> and various explicit schemes:
> 
>     1. explicit Newark
> 
>     2. leapfrog
> 
>     3. explicit predictor-corrector methods
> 
>     4. etc...
> 
> 
> This is why things are kicked down to the derived classes of `SolverBase` to define their own set available options. Most of the methods are probably not physics specific, but rather based on the characteristics of the governing equations, but I am not sure that this is always the case.

Yeah, I noticed that and it does make things a little more complex. I feel we can still group them into `explicitStep()` and `implicitStep()` and have a base implementation in `SolverBase` used by all solvers but keep these functions virtuals so that, for example the`SolidMechanicsSolver` can overload them as needed. In general though I think that these methods are not really physics specific. I can see how a generic implementation is non trivial though.
