### ISSUE TITLE
[Bug] the specified MeshBody name  was not found

### ISSUE THREAD

**Issue by geovivo** [GEOSX/GEOSX#2182]
GEOSX passed the tests by running "ctest -V". 
But I tried to run the case: inputFiles/compositionalMultiphaseWell/benchmarks/Egg/deadOilEgg_base_iterative.xml
I got the following error:
dudu@dudu-love:~/codes/GEOSX/build-ubuntu-release$ ./bin/geosx -i /home/dudu/codes/GEOSX/inputFiles/compositionalMultiphaseWell/benchmarks/Egg/deadOilEgg_base_iterative.xml 
Max threads: 8
GEOSX version: 0.2.0 (develop, sha1: 00dd40335)
  - c++ compiler: gcc 9.4.0
  - openmp version: 201511
  - MPI version: Open MPI v4.0.3, package: Debian OpenMPI, ident: 4.0.3, repo rev: v4.0.3, Mar 03, 2020
  - HDF5 version: 1.12.1
  - Conduit version: 0.8.2
  - VTK version: 9.1.0
  - RAJA version: 2022.3.0
  - umpire version: 2022.3.0
  -  adiak version: ..
  - caliper version: 2.8.0
  - METIS version: 5.1.0
  - PARAMETIS version: 4.0.3
  - scotch version: 6.0.9
  - superlu_dist version: 6.3.0
  - suitesparse version: 5.7.9
  - hypre release version: 2.26.0
Adding Solver of type CompositionalMultiphaseReservoir, named coupledFlowAndWells
Adding Solver of type CompositionalMultiphaseFVM, named compositionalMultiphaseFlow
Adding Solver of type CompositionalMultiphaseWell, named compositionalMultiphaseWell
Adding Event: PeriodicEvent, vtk
Adding Event: PeriodicEvent, timeHistoryOutput1
Adding Event: PeriodicEvent, timeHistoryOutput2
Adding Event: PeriodicEvent, timeHistoryOutput3
Adding Event: PeriodicEvent, timeHistoryOutput4
Adding Event: PeriodicEvent, solverApplications
Adding Event: PeriodicEvent, timeHistoryCollection1
Adding Event: PeriodicEvent, timeHistoryCollection2
Adding Event: PeriodicEvent, timeHistoryCollection3
Adding Event: PeriodicEvent, timeHistoryCollection4
Adding Event: PeriodicEvent, restarts
Adding Output: VTK, vtkOutput
Adding Output: TimeHistory, timeHistoryOutput1
Adding Output: TimeHistory, timeHistoryOutput2
Adding Output: TimeHistory, timeHistoryOutput3
Adding Output: TimeHistory, timeHistoryOutput4
Adding Output: Restart, restartOutput
***** ERROR
***** LOCATION: /home/dudu/codes/GEOSX/src/coreComponents/mesh/ElementRegionBase.cpp:81
***** Controlling expression (should be false): !meshBodyFound
***** Rank 0: There are multiple MeshBodies in this problem, but the specified MeshBody name  was not found

** StackTrace of 5 frames **
Frame 0: geosx::ProblemManager::parseXMLDocument(pugi::xml_document const&) 
Frame 1: geosx::ProblemManager::parseInputFile() 
Frame 2: geosx::GeosxState::initializeDataRepository() 
Frame 3: main 
Frame 4: __libc_start_main 
Frame 5: _start 
=====
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

**Comment by TotoGaz** [comment]
You should not be running `deadOilEgg_base_iterative` which is a `base` file which is meant to be included in another more complete file.
You most likely want to run the `smoke` or `benchmark` version, in the same folder.

**Comment by geovivo** [comment]
It worked, thanks!
