### ISSUE TITLE
[Bug] Error when producer and injector assigned the same rate table

### ISSUE THREAD

**Issue by dkachuma** [GEOSX/GEOSX#2189]
**Description**

When two wells, one a producer and the other an injector are assigned the same table function as a rate function, GEOSX issues an error about a negative rate.

[voidage.txt](https://github.com/GEOSX/GEOSX/files/10127087/voidage.txt)

Attached is a simple reproducer `voidage.xml` (renamed to `voidage.txt`). This is a single phase flow only model in which there are two wells. The use case is to do "voidage replacement" - in this case, having the injector inject at the same rate as the producer. The two wells are therefore assigned the same `targetTotalRateTableName` in their `WellControls` elements.

**To Reproduce**

1. Run attached reproducer `voidage.xml`. 
2. GEOSX will issue the error
```
***** LOCATION: /tmp/GEOSX/src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWell.cpp:141
***** Controlling expression (should be false): ( ( wellControls.isInjector() && targetTotalRate < 0.0 ) || ( wellControls.isProducer() && targetTotalRate > 0.0) )
***** Rank 0: WellControls named INJE: Target total rate cannot be negative

** StackTrace of 8 frames **
Frame 0: geosx::SinglePhaseWell::initializePostSubGroups()
[voidage.txt](https://github.com/GEOSX/GEOSX/files/10127078/voidage.txt)

Frame 1: geosx::dataRepository::Group::initialize()
Frame 2: geosx::dataRepository::Group::initialize()
Frame 3: geosx::dataRepository::Group::initialize()
Frame 4: geosx::ProblemManager::problemSetup()
Frame 5: geosx::GeosxState::initializeDataRepository()
Frame 6: main
Frame 7: __libc_start_main
Frame 8: /xxx/GEOSX-42f7895/bin/geosx
=====
```
This is despite the function being positive.

**Expected behavior**

Should run (?)

**Platform:**
- Machine: RHEL 7.6
- Compiler: gcc 8.3.0
- GEOSX Version 0.2.0 (HEAD, sha1: 42f7895)

**Additional context**

The workaround is trivial - redifine the function with a different name and use the different functions for producers and injectors. This makes the issue trivial but it would be nice to make it work either way.

**Comment by francoishamon** [comment]
Thanks @dkachuma, yes, let's fix this. GEOSX internally multiplies the rate by -1 for producers, which is why the code does not work if the same table is used for both producers and injectors. We can come up with an easy fix / cleanup, I assign the two of us to the issue. In passing we can also cleanup a few other things in the well controls.
