### ISSUE TITLE
PVT File Reading Error

### ISSUE THREAD

**Issue by philippechehade** [GEOSX/GEOSX#2214]
**Describe the bug**
Simulating CO2 Injection in Aquifer using Ezrokhi's Correlations for Brine.
The below error is obtained : 
***** LOCATION: /tmp/GEOSX/src/coreComponents/constitutive/fluid/CO2BrineFluid.cpp:223
***** Controlling expression (should be false): true
'**** Rank 0: CO2BrineEzrokhiFluid fluid: invalid PVT function type '

The input files of the simulation are attached to this message 
The pvt data used for the liquid is the same as : inputFiles/compositionalMultiphaseWell/benchmarks/Class09Pb3/tables/pvtliquid_ez.txt
Version : 9d7cd0d
@jeannepellerin 
[Debug.zip](https://github.com/GEOSX/GEOSX/files/10226431/Debug.zip)

**Comment by francoishamon** [comment]
Hello @philippechehade 
Thanks for reporting this.

To make your test work, just remove the blank lines at the end of the `pvtgas.txt`. The piece of code that reads this file is not very robust and does not work if there is a blank line at the end of the file.

That being said, this way of specifying the PVT functions using external files in the CO2-brine model is very old-fashioned (actually comes from another code) and we have discussed many times the fact that we should change it. The information should come from the xml file using proper tags and not from an external file. So now is the time to do it! I will fix this.

**Comment by philippechehade** [comment]
Thank you @francoishamon 
The issue is solved !

**Comment by MelReyCG** [comment]
@herve-gross I'm fixing this issue by adding verifications to ignore empty lines. I'm also slightly changing the way to acquire space separated parameters (from stringutilities::tokenize( str, " " ) to a new stringutilities::tokenizeBySpaces( str ), which ignore correctly all types of whitespace, including the one surrounding the input string).
The commit I pushed only affect the CO2BrineFluid object but I'm going to change ReactiveBrineFluid and testCO2BrineModels too.

**Comment by MelReyCG** [comment]
PVT files reading robustness should be improved. The problems identified are :
1.	Empty lines in a PVT file results in a crash,
2.	The only whitespaces taken into account is the space (' '),
3.	Empty entries processing is inconsistent: 
- tokenize("1|2|3" , "|")  returns 3 parameters,
- tokenize("|1|2|3|" , "|") returns 4 parameters (with the first one being empty)
 
The solution proposed is to fix CO2BrineFluid::createPVTModels() and ReactiveBrineFluid::createPVTModels() by :
1.	Making them ignore empty lines,
2.	Basing them on an alternative stringutilities::tokenizeBySpaces() function which never create empty entries.
