### ISSUE TITLE
[Bug] Testing CO2 Fluid Models

### ISSUE THREAD

**Issue by philippechehade** [GEOSX/GEOSX#2216]
Hello,

While testing the different CO2 Injection models, I was able to successfully test the CO2BrinePhillipsFluid, CO2BrinePhillipsThermalFluid, CO2BrineEzrokhiFluid

However, when testing the CO2BrineEzrokhi**Thermal**Fluid, the simulation crashed and the below error was obtained:
***** ERROR
***** LOCATION: /tmp/GEOSX/src/coreComponents/constitutive/ConstitutivePassThruHandler.hpp:48
***** Controlling expression (should be false): true
***** Rank 0: The constitutive model fluid was not dispatched.The model type does not match the list of supported types.

 

** StackTrace of 10 frames **
Frame 0: geosx::CompositionalMultiphaseBase::validateConstitutiveModels(geosx::DomainPartition const&) const 
Frame 1: geosx::CompositionalMultiphaseBase::initializePreSubGroups() 
Frame 2: geosx::CompositionalMultiphaseFVM::initializePreSubGroups() 
Frame 3: geosx::dataRepository::Group::initialize() 
Frame 4: geosx::dataRepository::Group::initialize() 
Frame 5: geosx::dataRepository::Group::initialize() 
Frame 6: geosx::ProblemManager::problemSetup() 
Frame 7: geosx::GeosxState::initializeDataRepository() 
Frame 8: main 
Frame 9: __libc_start_main 
Frame 10: /workrd/SCR/GEOSX/install/gcc8/GEOSX-9d7cd0d/bin/geosx 
=====

The Data deck used is attached to this comment.
@jeannepellerin 
[DATA_EZROKHI.zip](https://github.com/GEOSX/GEOSX/files/10236234/DATA_EZROKHI.zip)

**Comment by jeannepellerin** [comment]
We tracked the error to the coreComponents\constitutive\fluid\multiFluidSelector.hpp file where CO2BrineEzrokhiThermalFluid is commented on line 49 and 66

**Comment by francoishamon** [comment]
Hello @philippechehade and @jeannepellerin 
Yes, we have commented out this model because we are not able to compile GEOSX with the two thermal fluid models activated (compilation requires too much memory).

We are working on a solution for this problem, but we still have to polish it a little bit before deploying it the compositional model/solver. So it may take us a few weeks before we can solve this problem.

**Comment by francoishamon** [comment]
Yes, you are right, we can do that in the meantime. I will push some code that outputs a temporary error message.
