### ISSUE TITLE
Speedup OSX CI build process

### ISSUE THREAD

**Issue by rrsettgast** [GEOSX/GEOSX#2235]
**Describe the issue**
The OSX CI build takes a long time to build. It is frequently timing out.

**Proposed cleanup**
Stop building openmpi as part of the CI execution.

**Additional context**
I know we are building openmpi so that we don't get hit with the version updates for home-brew, but the openmpi build is taking almost an hour which we no longer have the have to spare.

**Comment by TotoGaz** [comment]
void-fixed by https://github.com/GEOSX/GEOSX/pull/2241
