### ISSUE TITLE
Wrong results in wave propagation when source/receiver falls on the boundary of a cell

### ISSUE THREAD

**Issue by sframba** [GEOSX/GEOSX#2256]
**Describe the bug**
When simulating seismic acquisitions, if a source or a receiver falls exactly on the boundary of a mesh element, it can be counted multiple times, or not a all. 

**To Reproduce**
Run an acoustic seismic wave propagation with a simple test case, and put a source and a set of receivers on faces, edges or nodes between elements. Set output `outputSeismoTrace` to `1` to output traces in `txt` format, or use the `python` interface to to retrieve the variable `pressureNp1AtReceivers`. Some receivers will have wrong amplitudes, or be zero.

**Expected behavior**
GEOSX shoud be robust and give a coherent result whatever the position of the receiver or source points.

**Platform (please complete the following information):**
- Machine: all
- Compiler: tested with gcc
- GEOSX Version: develop

**Additional context**
The routine that checks whether a point is inside or outside a cell is not robust to degenerate cases.

**Comment by rrsettgast** [comment]
duplicate issue #2227 2227
