### ISSUE TITLE
Wave propagation tests need new baselines after lifo PR merge.

### ISSUE THREAD

**Issue by CusiniM** [GEOSX/GEOSX#2257]
Wave propagation tests should have been rebaselined after merging https://github.com/GEOSX/GEOSX/commit/29be27d758e6f7b3db955d96002e460d63a9a5b8 

They are now failing.

**Comment by sframba** [comment]
The issue is due to the change in some `xml` options. @XL64 and I are working on it

**Comment by sframba** [comment]
perfect, thanks @francoishamon
