### ISSUE TITLE
thirdPartyLibs compilation issue

### ISSUE THREAD

**Issue by ver2king** [GEOSX/GEOSX#2273]
I encountered an issue while following the start-up tutorial. After I ran the command:

cd thirdPartyLibs
python scripts/config-build.py -hc ../GEOSX/host-configs/your-platform.cmake -bt Release
cd build-your-platform-release
make

The error is as follows:

![image](https://user-images.githubusercontent.com/31938494/216661428-a4903862-88c5-4f30-bc60-433dcd9ab718.png)

The corresponding config log I could trace back is attached. 
[config.log](https://github.com/GEOSX/GEOSX/files/10580977/config.log)

**Comment by ver2king** [comment]
The config file, as named _
[demo.txt](https://github.com/GEOSX/GEOSX/files/10581006/demo.txt)
_ is attached here.

**Comment by klevzoff** [comment]
The log indicates that your MPI C compiler wrapper `/home/temoor/anaconda3/bin/mpicc` is not working properly:
```
/home/temoor/anaconda3/bin/mpicc: line 285: x86_64-conda_cos6-linux-gnu-cc: command not found
```
Could you:
  * try to compile a simple C program (`int main(){ return 0; }`) with it?
  * re-install the conda package
  * use a different MPI installation if the above doesn't help?

**Comment by ver2king** [comment]
Thanks for your swift comment. I figured out the correct MPI compilers to use, however a new error was raised. Please find the screenshot attached. The config file remains the same as my original comment. 

![image](https://user-images.githubusercontent.com/31938494/216682666-906a5bf0-bf7d-4443-8d5f-84614f9470f5.png)

**Comment by TotoGaz** [comment]
I think [this page](https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/buildGuide/Prerequisites.html) should help you.

**Comment by ver2king** [comment]
After a bit of effort, now I already progressed to the compilation of GEOSX itself. And now I encountered this issue (figure as attached):

![image](https://user-images.githubusercontent.com/31938494/216740098-b5ae494b-2a72-4355-b81a-1fb2657c28a4.png)

I looked into the file ParMETISInterface.cpp and also its folder directory, and it was true that the parmetis.h file and also, the metis.h file, are not found. However, I have no idea why those files do not exist in the directory.

**Comment by klevzoff** [comment]
`parmetis.h` and `metis.h` should actually be located under `thirdPartyLibs` install tree, e.g.
```
/home/temoor/Desktop/codes/thirdPartyLibs/install-demo-release/parmetis/include/parmetis.h
```
If it's not there, the build of `thirdPartyLibs` likely didn't complete for some reason. Could you rerun it (just `cmake .. && make` in the build directory would be enough) and post the output?

**Comment by pradhyumna85** [comment]
@ver2king,
For the above simple build config may by you can start from a docker container with precompiled TPLs and then directly proceed with building GEOSX in the container, check out my repo [here](https://github.com/pradhyumna85/build-geosx-image).
Base image with everything there to build GEOSX from source: [here](https://hub.docker.com/layers/pradhyumna85/geosx/base-build-image-geosx-0.2.0/images/sha256-15dfa74fa041ac989f94404da9225d219b61dd0bb74fe58a02fd03b75dbb5da6?context=repo)

Or you can directly use a docker image with GEOSX already compiled and directly use it. I have hosted the image: [here](https://hub.docker.com/layers/pradhyumna85/geosx/0.2.0-hp-zbook-17-G6-xeon-x86/images/sha256-9ad6f1b1ac2e56addfafba0a75ae741f5397f2ba517ca87d39682150265a0c4a?context=repo).

Inside this image (container), you can test the binary:
> `/app/GEOSX/install-docker-release/bin/geosx --help`

```
root@a90781d6a263:/# su mpiuser
mpiuser@a90781d6a263:/$ /app/GEOSX/install-docker-release/bin/geosx --help
GEOSX version: 0.2.0
  - c++ compiler: clang 8.0.1
  - MPI version: Open MPI v4.0.3, package: Debian OpenMPI, ident: 4.0.3, repo rev: v4.0.3, Mar 03, 2020
  - HDF5 version: 1.12.1
  - Conduit version: 0.8.2
  - VTK version: 9.1.0
  - RAJA version: 2022.3.0
  - umpire version: 2022.3.0
  -  adiak version: ..
  - caliper version: 2.8.0
  - METIS version: 5.1.0
  - PARAMETIS version: 4.0.3
  - scotch version: 6.0.9
  - superlu_dist version: 6.3.0
  - suitesparse version: 5.7.9
  - hypre release version: 2.27.0
USAGE: geosx -i input.xml [options]

Options:
-?, --help
-i, --input,             Input xml filename (required)
-r, --restart,           Target restart filename
-x, --x-partitions,      Number of partitions in the x-direction
-y, --y-partitions,      Number of partitions in the y-direction
-z, --z-partitions,      Number of partitions in the z-direction
-s, --schema,            Name of the output schema
-b, --use-nonblocking,   Use non-blocking MPI communication
-n, --name,              Name of the problem, used for output
-s, --suppress-pinned,   Suppress usage of pinned memory for MPI communication buffers
-o, --output,            Directory to put the output files
-t, --timers,            String specifying the type of timer output
--trace-data-migration,  Trace host-device data migration
--pause-for,             Pause geosx for a given number of seconds before starting execution
mpiuser@a90781d6a263:/$ 
```

I tested running [Single Phase Flow](https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/tutorials/step01/Tutorial.html) and [Multi Phase Flow Wells](https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/basicExamples/multiphaseFlowWithWells/Example.html) examples and they ran fine with correct output produced.

**Comment by herve-gross** [comment]
@ver2king have you been able to make it work? Thanks @pradhyumna85 for your advice. If the documentation is unclear, let us know how to improve it.

**Comment by ver2king** [comment]
I readily figured out the hassle and completed the installation. I appreciate all your support and I shall close this issue.
