### ISSUE TITLE
Build error related to HYPRE_MGRSetLevelFRelaxType

### ISSUE THREAD

**Issue by sytuannguyen** [GEOSX/GEOSX#2286]
**Describe the bug**
Recently, the build in TotalEnergies XRAI machine (using gcc version 10.2.0) is blocked by an error message as shown below:

![image](https://user-images.githubusercontent.com/45685596/217411068-bb3a0b43-302a-45ea-9fb0-732013802ede.png)

It is verified that this bug is purely related to the code below:

`GEOSX_LAI_CHECK_ERROR( HYPRE_MGRSetLevelFRelaxType( precond.ptr, toUnderlyingPtr( m_levelFRelaxType ) ));`

because the build was success by comment out this line of code. 

**To Reproduce**
Build actual version of GEOSX in TotalEnergies XRAI machine with default gcc version 10.2.0. This bug might be related to the complilator version? 

**Expected behavior**
Success build.

**Screenshots**

**Platform (please complete the following information):**
- Machine [e.g. TotalEnergies/XRAI] 
- Compiler: [e.g. gcc 10.2.0]
- GEOSX Version [#e5b513c]

**Additional context**
@francoishamon mentioned that the related line of code is required, cannot be commented out.

**Comment by victorapm** [comment]
The error message suggests using `HYPRE_MGRSetFLevelRelaxType`, which was replaced with the correct form `HYPRE_MGRSetLevelFRelaxType` in this hypre commit: https://github.com/hypre-space/hypre/commit/ebc634a4e86d4b1aba97f61a8ba0aae701c9799b. The hypre version used in the TPLs is newer than this commit. Thus, updating your local hypre copy with the version distributed in the TPL repository will probably solve this issue and no change is necessary to GEOSX's code.

**Comment by sytuannguyen** [comment]
@TotoGaz @victorapm Thank you very much, you are right about updating of the hypre library for solving this issue. I will close this.
