### ISSUE TITLE
SuiteSparse: umfpack_dl_numeric failed

### ISSUE THREAD

**Issue by FishYNY** [GEOSX/GEOSX#2315]
I don't kown where is going wrong?

GEOSX version: 0.2.0 (develop, sha1: bbd1948c0)
  - c++ compiler: gcc 9.4.0
  - MPI version: Open MPI v4.0.3, package: Debian OpenMPI, ident: 4.0.3, repo rev: v4.0.3, Mar 03, 2020
  - HDF5 version: 1.12.1
  - Conduit version: 0.8.2
  - VTK version: 9.1.0
  - RAJA version: 2022.3.0
  - umpire version: 2022.3.0
  -  adiak version: ..
  - caliper version: 2.8.0
  - METIS version: 5.1.0
  - PARAMETIS version: 4.0.3
  - scotch version: 6.0.9
  - superlu_dist version: 6.3.0
  - suitesparse version: 5.7.9
  - hypre development version: v2.27.0-9-g52802b646 (master)
Adding Mesh: InternalMesh, mesh
Adding Mesh: InternalWell, wellinjector
Adding Event: PeriodicEvent, solverApplications
Adding Event: PeriodicEvent, outputs
Adding Solver of type MultiphasePoromechanicsReservoir, named reservoirSystem
Adding Solver of type MultiphasePoromechanics, named multiphasePoroelasticity
Adding Solver of type SolidMechanicsLagrangianSSLE, named linearElasticity
Adding Solver of type CompositionalMultiphaseFVM, named twoPhaseFlow
Adding Solver of type CompositionalMultiphaseWell, named compositionalMultiphaseWell
   TableFunction: initCO2CompFracTable
   TableFunction: initWaterCompFracTable
   TableFunction: initTempTable
   TableFunction: waterRelativePermeabilityTable
   TableFunction: gasRelativePermeabilityTable
   TableFunction: jFunctionTable
Adding Output: VTK, reservoir_with_properties
Adding Object CellElementRegion named reservoir from ObjectManager::Catalog.
Adding Object CellElementRegion named top from ObjectManager::Catalog.
Adding Object CellElementRegion named bottom from ObjectManager::Catalog.
Adding Object WellElementRegion named well from ObjectManager::Catalog.
   TableFunction: fluid_phaseModel1_PhillipsBrineDensity_table
   TableFunction: fluid_phaseModel1_PhillipsBrineViscosity_table
   TableFunction: fluid_phaseModel2_SpanWagnerCO2Density_table
   TableFunction: fluid_phaseModel2_FenghourCO2Viscosity_table
   TableFunction: fluid_CO2Solubility_table
   TableFunction: wellControls_ConstantBHP_table
   TableFunction: wellControls_ConstantTotalRate_table
   TableFunction: wellControls_ConstantPhaseRate_table
   TableFunction: WellControls_OpenStatus_table
mesh: total number of nodes = 67626
mesh: total number of elems = 62500
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh, Level0, bottom, bottom
mesh/Level0/bottom/bottom/fluid allocated 8 quadrature points
mesh/Level0/bottom/bottom/rockBurden allocated 8 quadrature points
mesh/Level0/bottom/bottom/relperm allocated 8 quadrature points
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh, Level0, reservoir, reservoir
mesh/Level0/reservoir/reservoir/fluid allocated 8 quadrature points
mesh/Level0/reservoir/reservoir/rock allocated 8 quadrature points
mesh/Level0/reservoir/reservoir/relperm allocated 8 quadrature points
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh, Level0, top, top
mesh/Level0/top/top/fluid allocated 8 quadrature points
mesh/Level0/top/top/rockBurden allocated 8 quadrature points
mesh/Level0/top/top/relperm allocated 8 quadrature points
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh, Level0, well, wellUniqueSubRegion
mesh/Level0/well/wellUniqueSubRegion/fluid allocated 1 quadrature points
mesh/Level0/well/wellUniqueSubRegion/relperm allocated 1 quadrature points
mesh: importing field data from mesh dataset
   TableFunction: equil_bottom_water_table
   TableFunction: equil_reservoir_water_table
   TableFunction: equil_top_water_table
Time: 0s, dt:1e+06s, Cycle: 0
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  0
    ( Rsolid ) = ( 1.98e+02 ) ;     ( Rflow ) = ( 1.44e+01 ) ;     ( Rwell ) = ( 1.35e+02 ) ;     ( R ) = ( 2.40e+02 ) ; 

UMFPACK V5.7.9 (Oct 20, 2019): ERROR: out of memory

***** ERROR
***** LOCATION: /home/pku/codes/codes02232023/GEOSX/src/coreComponents/linearAlgebra/interfaces/direct/SuiteSparse.cpp:158
***** Controlling expression (should be false): true
***** Rank 0: SuiteSparse: umfpack_dl_numeric failed.

** StackTrace of 12 frames **
Frame 0: geosx::SuiteSparse<geosx::HypreInterface>::setup(geosx::HypreMatrix const&) 
Frame 1: geosx::SolverBase::solveLinearSystem(geosx::DofManager const&, geosx::HypreMatrix&, geosx::HypreVector&, geosx::HypreVector&) 
Frame 2: geosx::SolverBase::solveNonlinearSystem(double const&, double const&, int, geosx::DomainPartition&) 
Frame 3: geosx::SolverBase::nonlinearImplicitStep(double const&, double const&, int, geosx::DomainPartition&) 
Frame 4: geosx::SolverBase::solverStep(double const&, double const&, int, geosx::DomainPartition&) 
Frame 5: geosx::CoupledSolver<geosx::MultiphasePoromechanicsSolver, geosx::CompositionalMultiphaseWell>::solverStep(double const&, double const&, int, geosx::DomainPartition&) 
Frame 6: geosx::SolverBase::execute(double, double, int, int, double, geosx::DomainPartition&) 
Frame 7: geosx::EventBase::execute(double, double, int, int, double, geosx::DomainPartition&) 
Frame 8: geosx::EventManager::run(geosx::DomainPartition&) 
Frame 9: geosx::GeosxState::run() 
Frame 10: main 
Frame 11: __libc_start_main 
Frame 12: _start 
=====

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

[basemodel_smoke.zip](https://github.com/GEOSX/GEOSX/files/10835774/basemodel_smoke.zip)

**Comment by francoishamon** [comment]
Hello @FishYNY ,
Most likely, the error message:
```
UMFPACK V5.7.9 (Oct 20, 2019): ERROR: out of memory
```
indicates that your multiphase poromechanics problem is just too large for the direct solver.

I suggest trying with:
```
      <NonlinearSolverParameters
        newtonTol="1.0e-5"
        lineSearchAction="None"
        newtonMaxIter="40"/>
      <LinearSolverParameters
        solverType="gmres"
        preconditionerType="mgr"/>
```
(looser nonlinear tolerance + use of the iterative solver)

**Comment by FishYNY** [comment]
Hello @francoishamon 
Thank you for your advice. It does work, but convergence is still not achieved. Maybe my problem is definitely large, is there something else I should try?

**Comment by francoishamon** [comment]
I would suggest the following:

1. Try initializing the effective stress as done here: https://github.com/GEOSX/GEOSX/blob/5841bf7f79a90368e19e399199891d73fe20ad78/inputFiles/poromechanics/PoroElastic_hybridHexPrism_co2_3d.xml#L192

For you, given your `datumPressure`, it is going to be something like:
```
    <FieldSpecification
      name="initialSigmaReservoir_x"
      initialCondition="1"
      setNames="{ all }"
      objectPath="ElementRegions/reservoir"
      fieldName="skeleton_stress"
      component="0"
      scale="1e7"/>
    <FieldSpecification
      name="initialSigmaReservoir_y"
      initialCondition="1"
      setNames="{ all }"
      objectPath="ElementRegions/reservoir"
      fieldName="skeleton_stress"
      component="1"
      scale="1e7"/>
    <FieldSpecification
      name="initialSigmaReservoir_z"
      initialCondition="1"
      setNames="{ all }"
      objectPath="ElementRegions/reservoir"
      fieldName="skeleton_stress"
      component="2"
      scale="1e7"/>

    <FieldSpecification
      name="initialSigmaTop_x"
      initialCondition="1"
      setNames="{ all }"
      objectPath="ElementRegions/top"
      fieldName="skeletonBurden_stress"
      component="0"
      scale="1e7"/>
    <FieldSpecification
      name="initialSigmaTop_y"
      initialCondition="1"
      setNames="{ all }"
      objectPath="ElementRegions/top"
      fieldName="skeletonBurden_stress"
      component="1"
      scale="1e7"/>
    <FieldSpecification
      name="initialSigmaTop_z"
      initialCondition="1"
      setNames="{ all }"
      objectPath="ElementRegions/top"
      fieldName="skeletonBurden_stress"
      component="2"
      scale="1e7"/>

   <FieldSpecification
      name="initialSigmaBottom_x"
      initialCondition="1"
      setNames="{ all }"
      objectPath="ElementRegions/bottom"
      fieldName="skeletonBurden_stress"
      component="0"
      scale="1e7"/>
    <FieldSpecification
      name="initialSigmaBottom_y"
      initialCondition="1"
      setNames="{ all }"
      objectPath="ElementRegions/bottom"
      fieldName="skeletonBurden_stress"
      component="1"
      scale="1e7"/>
    <FieldSpecification
      name="initialSigmaTop_z"
      initialCondition="1"
      setNames="{ all }"
      objectPath="ElementRegions/bottom"
      fieldName="skeletonBurden_stress"
      component="2"
      scale="1e7"/>
```

then look at the first vtk output before the first time step to make sure that the initial stress is taken into account (alternatively, use the [latest commit to develop](https://github.com/GEOSX/GEOSX/commit/5841bf7f79a90368e19e399199891d73fe20ad78) that will throw an error if the initial stress is not applied because of a naming problem, etc).

2. Make sure that the first mechanics residual (R_solid) is zero before the first linear iteration of the first time step

3. If the linear solver does not converge, post the simulation log on the issue

**Comment by FishYNY** [comment]
yes！It works. Thank you!
