### ISSUE TITLE
Face 0 is not connected to an element

### ISSUE THREAD

**Issue by FishYNY** [GEOSX/GEOSX#2336]
Is there something wrong in my MESH?
```
GEOSX version: 0.2.0 (develop, sha1: bbd1948c0)
  - c++ compiler: gcc 9.4.0
  - MPI version: Open MPI v4.0.3, package: Debian OpenMPI, ident: 4.0.3, repo rev: v4.0.3, Mar 03, 2020
  - HDF5 version: 1.12.1
  - Conduit version: 0.8.2
  - VTK version: 9.1.0
  - RAJA version: 2022.3.0
  - umpire version: 2022.3.0
  -  adiak version: ..
  - caliper version: 2.8.0
  - METIS version: 5.1.0
  - PARAMETIS version: 4.0.3
  - scotch version: 6.0.9
  - superlu_dist version: 6.3.0
  - suitesparse version: 5.7.9
  - hypre development version: v2.27.0-9-g52802b646 (master)
Adding Mesh: VTKMesh, mesh
Adding Mesh: InternalWell, wellInjector1
Adding Output: VTK, simpleReservoirViz
Adding Output: Restart, restartOutput
Adding Event: PeriodicEvent, outputs
Adding Event: PeriodicEvent, restarts
Adding Event: PeriodicEvent, statistics
Adding Event: PeriodicEvent, solverApplications1
Adding Event: PeriodicEvent, solverApplications2
Adding Event: PeriodicEvent, solverApplications3
Adding Solver of type CompositionalMultiphaseReservoir, named coupledFlowAndWells
Adding Solver of type CompositionalMultiphaseFVM, named compositionalMultiphaseFlow
Adding Solver of type CompositionalMultiphaseWell, named compositionalMultiphaseWell
   TableFunction: initCO2CompFracTable
   TableFunction: initWaterCompFracTable
   TableFunction: initTempTable
   TableFunction: waterRelativePermeabilityTable
   TableFunction: gasRelativePermeabilityTable
   TableFunction: waterCapillaryPressureTable
   TableFunction: totalRateTable
Adding Object CellElementRegion named reservoir from ObjectManager::Catalog.
Adding Object WellElementRegion named wellRegion from ObjectManager::Catalog.
   TableFunction: fluid_phaseModel1_EzrokhiBrineDensity_sat_density_table
   TableFunction: fluid_phaseModel1_EzrokhiBrineDensity_sat_pressure_table
   TableFunction: fluid_phaseModel1_EzrokhiBrineViscosity_table
   TableFunction: fluid_phaseModel2_SpanWagnerCO2Density_table
   TableFunction: fluid_phaseModel2_FenghourCO2Viscosity_table
   TableFunction: fluid_CO2Solubility_table
   TableFunction: wellControls_ConstantBHP_table
   TableFunction: wellControls_ConstantPhaseRate_table
   TableFunction: WellControls_OpenStatus_table
VTKMesh 'mesh': reading mesh from /home/pku/codes/codes02232023/runfiles/mycase/Case4-v2/Case4_Mesh.vtk
Generating global Ids from VTK mesh
VTKMesh 'mesh': generating GEOSX mesh data structure
Number of nodes: 48672
  Number of elems: 44217
             C3D8: 44217
Load balancing:   min   avg   max
(element/rank): 44217 44217 44217

++++++++++++++++++++++++++
InternalWellGenerator = wellInjector1
MPI rank = 0

Number of well elements = 3
Well element #0
Coordinates of the element center: { 100, 100, 1236.67 }
No next well element
Previous well element #1
First well node: #0
Second well node: #1
Well element #1
Coordinates of the element center: { 100, 100, 1230 }
Next well element # = 0
Previous well element #2
First well node: #1
Second well node: #2
Well element #2
Coordinates of the element center: { 100, 100, 1223.33 }
Next well element # = 1
No previous well element
First well node: #2
Second well node: #3

Number of perforations = 3
Perforation #0
Coordinates of the perforation: { 100, 100, 1225 }
Is connected to well element #2
Perforation #1
Coordinates of the perforation: { 100, 100, 1230 }
Is connected to well element #1
Perforation #2
Coordinates of the perforation: { 100, 100, 1235 }
Is connected to well element #0

***** ERROR
***** LOCATION: /home/pku/codes/codes02232023/GEOSX/src/coreComponents/mesh/FaceManager.cpp:199
***** Controlling expression (should be false): true
***** Rank 0: Face 0 is not connected to an element.

** StackTrace of 6 frames **
Frame 0: geosx::DomainPartition::setupCommunications(bool) 
Frame 1: geosx::ProblemManager::generateMesh() 
Frame 2: geosx::ProblemManager::problemSetup() 
Frame 3: geosx::GeosxState::initializeDataRepository() 
Frame 4: main 
Frame 5: __libc_start_main 
Frame 6: _start 
=====
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
```
[Case4_Mesh.zip](https://github.com/GEOSX/GEOSX/files/10952969/Case4_Mesh.zip)

**Comment by francoishamon** [comment]
Hello @FishYNY 

Most likely, there is nothing wrong with your mesh, but the problem is in the definition of the `ElementRegions`. This error message is very confusing but typically occurs when a region defined in the vtk file and imported by GEOSX is not included in the `ElementRegions`.

I advise you to do the following:
1) Add `logLevel="5"` in the block called `VTKMesh`
2) Relaunch the simulation as is
3) In the log, GEOSX is going to list all the imported regions with their names. Look for something like:
```
  writing cells...
Importing cell block 3_tetrahedra
Importing cell block 2_tetrahedra
Importing cell block 1_tetrahedra
Importing cell block 5_tetrahedra
Importing cell block 4_tetrahedra
Importing cell block 3_pyramids
Importing cell block 2_pyramids
Importing cell block 1_pyramids
Importing cell block 5_pyramids
Importing cell block 4_pyramids
Importing cell block 2_hexahedra
Importing cell block 1_hexahedra
Importing cell block 5_hexahedra
Importing cell block 3_hexahedra
Importing cell block 4_hexahedra
```
4) Using that log, make sure that all the cell blocks listed by GEOSX are included in a `CellElementRegion` of the `ElementRegion` block. Something like:
```
  <ElementRegions>
    <CellElementRegion
      name="reservoir"
      cellBlocks="{ 2_hexahedra, 2_tetrahedra, 2_pyramids,
                    3_hexahedra, 3_tetrahedra, 3_pyramids,
                    4_hexahedra, 4_tetrahedra, 4_pyramids }"
      materialList="{ porousRockReservoir, fluid, relperm }"/> 
    <CellElementRegion 
      name="overburden"
      cellBlocks="{ 1_hexahedra, 1_tetrahedra, 1_pyramids }"
      materialList="{ porousRockOverburden, fluid, relperm }"/>
    <CellElementRegion 
      name="underburden"
      cellBlocks="{ 5_hexahedra, 5_tetrahedra, 5_pyramids }"
      materialList="{ porousRockUnderburden, fluid, relperm }"/>
  </ElementRegions>
```
If a cell block is missing, GEOSX will crash.

If this does not solve your problem, could you please post your xml as well?

**Comment by FishYNY** [comment]
Now I can import the vtk mesh. But, I failed to import the field data (porosity) from mesh dataset.  The dataset definetely includes the PORO field data. Is the format wrong?  Besides, I want to import the permeability, POISSONR, YOUNGMOD, BIOTC, fluid pressure, and effective stress. Is there some details that I should care? 

By the way, if I delete "fieldsToImport="{ PORO }"/n fieldNamesInGEOSX="{ rockPorosity_referencePorosity }"", geosx is able to calcuate the case. But the outcomes presented by paraview is changeless.  I doubt there are some parameters I set inappropriately.  

regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh, Level0, reservoir, 92_hexahedra
mesh/Level0/reservoir/92_hexahedra/fluid allocated 1 quadrature points
mesh/Level0/reservoir/92_hexahedra/rock allocated 1 quadrature points
mesh/Level0/reservoir/92_hexahedra/relperm allocated 1 quadrature points
mesh/Level0/reservoir/92_hexahedra/cappres allocated 1 quadrature points
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh, Level0, wellRegion, wellRegionUniqueSubRegion
mesh/Level0/wellRegion/wellRegionUniqueSubRegion/fluid allocated 1 quadrature points
mesh/Level0/wellRegion/wellRegionUniqueSubRegion/relperm allocated 1 quadrature points
mesh/Level0/wellRegion/wellRegionUniqueSubRegion/cappres allocated 1 quadrature points
mesh: importing field data from mesh dataset
Importing field PORO -> rockPorosity_referencePorosity on reservoir/92_hexahedra

***** LOCATION: /home/pku/codes/codes02232023/GEOSX/src/coreComponents/mesh/generators/VTKUtilities.cpp:1673
***** Controlling expression (should be false): curArray == nullptr
***** Rank 0: Source field 'PORO' not found in dataset

** StackTrace of 7 frames **
Frame 0: geosx::VTKMeshGenerator::importFieldsOnArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, geosx::dataRepository::WrapperBase&) const 
Frame 1: /home/pku/codes/codes02232023/GEOSX/build-your-platform-release/lib/libgeosx_core.so 
Frame 2: /home/pku/codes/codes02232023/GEOSX/build-your-platform-release/lib/libgeosx_core.so 
Frame 3: geosx::MeshManager::importFields(geosx::DomainPartition&) 
Frame 4: geosx::GeosxState::initializeDataRepository() 
Frame 5: main 
Frame 6: __libc_start_main 
Frame 7: _start 
=====

[post.zip](https://github.com/GEOSX/GEOSX/files/10958483/post.zip)

**Comment by francoishamon** [comment]
Hello @FishYNY 

This looks like an error in your vtk file. My advice for this one is just to save your ascii vtk file into a binary vtu file (you can do that easily in Paraview). This will solve the problem, or at least, on my side it immediately solved the problem.

Then, if you are using a recent version of GEOSX, you will get this error:
```
bcCompositionCO2: there is/are no set(s) named `3` under the objectPath `faceManager`, check your xml input
```
because here:
```
    <FieldSpecification
      name="bcCompositionCO2"
      objectPath="faceManager"
      setNames="{3}"
      fieldName="globalCompFraction"
      component="0"
      scale="0.000001"/>
    <FieldSpecification
      name="bcCompositionWater"
      objectPath="faceManager"
      setNames="{3}"
      fieldName="globalCompFraction"
      component="1"
      scale="0.999999"/>
```
the region attribute "3" is not defined in your mesh (you just have attributes from 92 to 95, I think). So either 1) use `Box` to capture the faces or 2) include attributes for the boundary faces (2D vtk cells) of your mesh.

The second issue with this block of the xml is that you are not enforcing a pressure, and GEOSX will need the triplet (p, z_1, z_2) to apply the boundary condition. So you will need something like:
```
  <FieldSpecification
      name="bcPressure"
      objectPath="faceManager"
      setNames="{ X }"
      fieldName="pressure"
      scale="1e7"/>
  <FieldSpecification
      name="bcCompositionCO2"
      objectPath="faceManager"
      setNames="{ X }"
      fieldName="globalCompFraction"
      component="0"
      scale="0.000001"/>
    <FieldSpecification
      name="bcCompositionWater"
      objectPath="faceManager"
      setNames="{ X }"
      fieldName="globalCompFraction"
      component="1"
      scale="0.999999"/>
```
where `X` is the name that you will have given to the `Box`, or the region attribute if you define an attribute for the boundary faces in your vtu.

Note that to makes things work first, it is ok to entirely remove this block of BCs from the xml.

Then you can post the log and we will be able to see why nothing happens in your simulation.

Last advice is to increase the porosity in the burden even if it is not very realistic, because 0.00001 is going to seriously deteriorate the performance of the linear solver. We are working on overcoming this issue now. In the meantime, I would increase the value of porosity to 0.1 in the burdens to have a simulation that runs in a reasonable amount of time.

**Comment by FishYNY** [comment]
Hello， @francoishamon. Thanks a lot for your advice, it does work.
