### ISSUE TITLE
Incorrect behavior of MpiWrapper::iRecv

### ISSUE THREAD

**Issue by rrsettgast** [GEOSX/GEOSX#593]
We should document that based on the current implementation we need to post all iSend-s prior to all iRecv-s (when GEOSX_USE_MPI is undefined) since MPI doesn't inherently have this restriction.

_Originally posted by @wrtobin in https://github.com/GEOSX/GEOSX/pull/581_

**Comment by wrtobin** [comment]
Since we don't officially support the non-MPI build, and this seems to only effect that case, I think we can just close this now.
