### ISSUE TITLE
Running the integrated tests in LSF env

### ISSUE THREAD

**Issue by TotoGaz** [GEOSX/GEOSX#627]
We were able to run/submit the integrated tests of GEOSX on a slurm environment (using the srun executable that both somehow submits and runs in parallel).

We try to run them in a LSF environment, that makes use of a bsub to submit the jobs.
I could find nothing about bsub in the code.

Is this platform supported?
Have you ever run the integrated tests on LSF?

Thank you for your help,

**Comment by rrsettgast** [comment]
@TotoGaz Is there a plan for resolution for this issue?

**Comment by corbett5** [comment]
It works with LSF on Summit and there's a specific issue for Pangea 3.
https://github.com/GEOSX/GEOSX/issues/1384
