### ISSUE TITLE
Remove TypeIDs

### ISSUE THREAD

**Issue by corbett5** [GEOSX/GEOSX#756]
We should just use std::type_index directly instead of our wrapper-ish TypeID enum.

**Comment by klevzoff** [comment]
FWIW, I don't think you can switch on `std::type_index`: https://godbolt.org/z/srKeYdzP4
So the type dispatch would have to be rewritten using if/else statements that are less efficient.

**Comment by corbett5** [comment]
I'm fine with if/else, the use cases shouldn't be tight anyways.
