### ISSUE TITLE
Output an Ascii file with Solver statistics

### ISSUE THREAD

**Issue by CusiniM** [GEOSX/GEOSX#760]
**Is your feature request related to a problem?**
Currently the information relative to the number of iterations, time-step cuts, etc is only outputted to screen. This makes it a bit hard to compare different runs in terms of performance of the nonlinear and linear solvers.  

**Describe the solution you'd like**
I suggest to output one (or more) ascii file(s) containing:

- summary of the number of Newton's  iterations, time-step cuts, linear solver iterations. 
- historical of the number of iterations (nonlinear and linear as a functions of the time-step number).

I think this kind of info will also be useful to produce plots for presentations and papers.

It seems that the most natural thing to do is to make the `NonLinearSolverParameters` responsible for outputting such a file.

**Comment by francoishamon** [comment]
Resolved by #1979
