### ISSUE TITLE
Develop a check mesh routine

### ISSUE THREAD

**Issue by AntoineMazuyer** [GEOSX/GEOSX#804]
Hello :wave: 

@herve-gross @TotoGaz @jafranc and I were discussing the following questions: 

 * Shall we accept every grids into GEOSX ?
 * Shall we take actions internally to "repair" the grids in GEOSX ?

Indeed, we already faced a lot problem due to badly designed grids:
 * Negative volume (when the ordering of nodes is inverted for instance)
 * Badly shaped hex from eclipse leading to bad transmissibility computation in our routines
 * Duplicated nodes
 * flat elements.

We agree that it is very hard to develop a "mesh repair" function because:
 * It means we are doing a choice for instance to not import flat cells, but maybe the user want to do it ?
 * It's difficult and not the purpose of a simulator.

The idea is to have a routine à la OpenFoam `CheckMesh` routine that will run some loops over the elements and the vertices to ensure the mesh is valid for the simulation. It can warn the user like : 

```
WARNING : cell 4568 has inverted node numbering. Consider changing it.
```

This `CheckMesh` can be launched every time and be deactivated with a flag in the XML

```xml
<PAMELAMeshGenerator name="mesh" file="mesh.msh" checkMesh="0"/>
```

Thoughts ?

**Comment by rrsettgast** [comment]
@AntoineMazuyer @castelletto1 What is the status of this issue?

**Comment by TotoGaz** [comment]
A `meshDoctor` tool has been merged in https://github.com/GEOSX/GEOSX/pull/2091 and could be used to welcome more and more checks.
Closing this issue in favor of more precise check needs.
