### ISSUE TITLE
Error in simplePDE/Laplace.cpp

### ISSUE THREAD

**Issue by rrsettgast** [GEOSX/GEOSX#810]
**Describe the bug**
The problem is that the dirichlet boundary condition is applied as if it is a nonlinear solve, but the solution is applied as if it is a linear solve. In the case of a linear system, the solution is the value of the primary field, while in the nonlinear solve the solution is the change in the primary field. Hence when you get the solution, and the primary field was already the correct value, the solution gives 0, but then the value of primary field is set to solution...which is 0.  

As a result, the solution jumps between the correct solution and 0.

**To Reproduce**
Change the runtime to have more than a single step.

**Expected behavior**
Constant solution.

**Screenshots**
Correct solution at first cycle:
![Screen Shot 2020-03-06 at 1 28 42 PM](https://user-images.githubusercontent.com/5116892/76123931-85164980-5fae-11ea-9e72-7f6b4706bac8.png)

incorrect solution at next cycle.
![Screen Shot 2020-03-06 at 1 28 51 PM](https://user-images.githubusercontent.com/5116892/76123945-8a739400-5fae-11ea-9acf-32313f3a0a5f.png)

This brings up an interesting issue in that the application of Dirichlet boundary conditions are different when the system is linear vs nonlinear....and the `ApplySystemSolution()` must be consistent with this. So either we have a consistent pair of `ApplyBC_Linear()/ApplySystemSolution()` and `ApplyBC_NonLinear()/ApplySystemSolutionNL()`...or we just ditch the linear treatment all together. I think we had already agreed on this....but I wanted to confirm before I made posted a work plan to achieve this.

**Comment by klevzoff** [comment]
Fixed
