### ISSUE TITLE
Reimplement PoreVolumeCompressibleSolid to fit in solid model hierarchy

### ISSUE THREAD

**Issue by rrsettgast** [GEOSX/GEOSX#816]
The `PoreVolumeCompressibleSolid` is a solid model, but does not conform the the solid model interface. The  `PoreVolumeCompressibleSolid` should be integrated with the other solid models s.t. it may be interchanged with full solid models seamlessly. 

I suggest that we modify the solid model hierarchy to allow for a stateless model like `PoreVolumeCompressibleSolid`...i.e. no stress will be stored. We can move the `m_stress` out of `SolidBase`, or create a `SolidBaseInterface` above `SolidBase` in the hierarchy. Then `PoreVolumeCompressibleSolid` can derive from `SolidBaseInterface`.

@klevzoff @francoishamon Thoughts? 

Is this the best place for this?  The base class is otherwise quite generic.  Ditto below for all the poreVolumeString stuff.

_Originally posted by @joshua-white in https://github.com/GEOSX/GEOSX/pull/754#discussion_r386744442

**Comment by joshua-white** [comment]
I think this will all be addressed by @CusiniM in #1311
