### ISSUE TITLE
Conglomorate mesh maps generation

### ISSUE THREAD

**Issue by corbett5** [GEOSX/GEOSX#904]
The code to generate the mesh topology maps (ie. face-to-nodes) is spread out and full of duplication. It should be moved out of the managers and into a separate file where it can be condensed.

**Comment by corbett5** [comment]
@TotoGaz I think your PR will close this right?

**Comment by TotoGaz** [comment]
To a large extent.

**Comment by TotoGaz** [comment]
Reopen to link to https://github.com/GEOSX/GEOSX/pull/1418 instead
