### ISSUE TITLE
Undefined behavior in forSubGroups()

### ISSUE THREAD

**Issue by rrsettgast** [GEOSX/GEOSX#924]
https://github.com/GEOSX/GEOSX/blob/8e440c86b47d972173fa368366ab563673c9733d/src/coreComponents/dataRepository/Group.hpp#L623

If the group isn't found, there is an attempt to dereference `nullptr`. This is undefined. Proper guards are required for dereferencing pointers.

**Comment by klevzoff** [comment]
No longer relevant, `forSubGroups` is using the reference version of the getter with proper checks and error messages.
