### ISSUE TITLE
XML trimming / re-org

### ISSUE THREAD

**Issue by joshua-white** [GEOSX/GEOSX#933]
We now have a large number of XMLs, and I think a few issues could be addressed during a doc-day sprint:

- [x] Many XMLs are *extremely* repetitive.  We should more frequently define base XMLs and just include them when creating problem variations.

- [x] Many XMLs contain tags that are not actually used and could be removed (e.g. a coupled solver has linear solver options that overload solver options in the sub-solver blocks).   It seems we have a habit of copying-and-adding to create new xmls, but never deleting. We should also explore a way to indicate to users which XML tags will be ignored, so novice users don't spend their time adjusting parameters that have no effect.

- [x] We should consider uncrustifying XMLs so they have consistent indentation style.

- [x] We should enforce a consistent directory organization and symbolic link policy.  Right now integrated tests, examples, and benchmarks are handle differently in different components (though there has been a lot of progress recently improving this)

- [ ] We should ensure all XMLs are actually used in an integratedTest, etc. so we don't have any "passive" xmls.

I propose we handle this during a doc-day.  If everyone takes on 5 to 10 xmls, we can get through this really quickly.  It is busy work, but I think it is worth the hassle.

**Comment by rrsettgast** [comment]
Develop a strategy for xml block reuse in integrated tests.

**Comment by rrsettgast** [comment]
add ability to write out xml file that embeds all the included xml files...etc.

**Comment by cssherman** [comment]
I wrote a quick script to check whether a xml files are linked in integratedTests (or include the 'base' or 'benchmark' keywords, or are in an 'old' directory).  I didn't parse the ats files directly, so there may be some things that I missed.  Here are the orphan files:

- [ ] examples/AdaptiveTimeStepping/deadoil_3ph_baker_1d.xml
- [ ] examples/GPU/beamBending.xml
- [ ] examples/advanced_xml_features/included/included_a.xml
- [ ] examples/advanced_xml_features/included/included_b.xml
- [ ] examples/advanced_xml_features/included/included_c.xml
- [ ] examples/advanced_xml_features/included_files_example.xml
- [ ] examples/advanced_xml_features/parameters_example.xml
- [ ] examples/advanced_xml_features/symbolic_math_example.xml
- [ ] examples/compositionalFlow/deadoilStaircase.xml
- [ ] examples/compositionalFlow/kernelTest/kernelTest.xml
- [ ] examples/event_examples.xml
- [ ] examples/functions/function_examples/function_examples.xml
- [ ] examples/pygeosxExamples/hydraulicFractureWithMonitor/hydraulicFracture.xml
- [ ] examples/pygeosxExamples/modifyBoundaryCondition/pkn_example.xml
- [ ] examples/pygeosxExamples/parametricSurfaceMapping/parametricMesh.xml
- [ ] examples/pygeosxExamples/sedovWithStressFunction/modified_sedov.xml
- [ ] examples/sedovKernelTest.xml
- [ ] examples/singlePhaseFlow/kernelTestFVM/kernelTestFVM.xml
- [ ] inputFiles/compositionalMultiphaseFlow/4comp_2ph_1d.xml
- [ ] inputFiles/compositionalMultiphaseFlow/4comp_2ph_cap_1d.xml
- [ ] inputFiles/compositionalMultiphaseFlow/co2_flux_3d.xml
- [ ] inputFiles/compositionalMultiphaseFlow/co2_hybrid_1d.xml
- [ ] inputFiles/compositionalMultiphaseFlow/deadoil_2ph_staircase_gravity_segregation_3d.xml
- [ ] inputFiles/compositionalMultiphaseFlow/deadoil_3ph_baker_1d.xml
- [ ] inputFiles/compositionalMultiphaseFlow/deadoil_3ph_corey_1d.xml
- [ ] inputFiles/compositionalMultiphaseFlow/deadoil_3ph_corey_1d_fractured.xml
- [ ] inputFiles/compositionalMultiphaseFlow/deadoil_3ph_corey_2d_edfm.xml
- [ ] inputFiles/compositionalMultiphaseFlow/deadoil_3ph_corey_2d_impermeableFault.xml
- [ ] inputFiles/compositionalMultiphaseFlow/deadoil_3ph_staircase_3d.xml
- [ ] inputFiles/compositionalMultiphaseFlow/deadoil_3ph_staircase_hybrid_3d.xml
- [ ] inputFiles/compositionalMultiphaseWell/black_oil_wells_saturated_3d.xml
- [ ] inputFiles/compositionalMultiphaseWell/black_oil_wells_unsaturated_3d.xml
- [ ] inputFiles/compositionalMultiphaseWell/compositional_multiphase_wells_1d.xml
- [ ] inputFiles/compositionalMultiphaseWell/compositional_multiphase_wells_2d.xml
- [ ] inputFiles/compositionalMultiphaseWell/dead_oil_wells_2d.xml
- [ ] inputFiles/compositionalMultiphaseWell/dead_oil_wells_hybrid_2d.xml
- [ ] inputFiles/compositionalMultiphaseWell/simpleCo2InjTutorial_smoke.xml
- [ ] inputFiles/compositionalMultiphaseWell/staircase_co2_wells_3d.xml
- [ ] inputFiles/compositionalMultiphaseWell/staircase_co2_wells_hybrid_3d.xml
- [ ] inputFiles/efemFractureMechanics/SneddonRotated_smoke.xml
- [ ] inputFiles/efemFractureMechanics/Sneddon_embeddedFrac_smoke.xml
- [ ] inputFiles/efemFractureMechanics/Sneddon_staticCondensation_smoke.xml
- [ ] inputFiles/hydraulicFracturing/Sneddon_hydroFrac_smoke.xml
- [ ] inputFiles/hydraulicFracturing/heterogeneousInSitu_smoke.xml
- [ ] inputFiles/hydraulicFracturing/hydrofractureSinglePhase2d.xml
- [ ] inputFiles/hydraulicFracturing/kgdEdgeBased_C3D6_smoke.xml
- [ ] inputFiles/hydraulicFracturing/kgdNodeBased_C3D6_smoke.xml
- [ ] inputFiles/hydraulicFracturing/kgdSmokeBase_C3D6.xml
- [ ] inputFiles/hydraulicFracturing/kgdToughnessDominated_smoke.xml
- [ ] inputFiles/hydraulicFracturing/kgdValidation_smoke.xml
- [ ] inputFiles/hydraulicFracturing/kgdViscosityDominated_smoke.xml
- [ ] inputFiles/hydraulicFracturing/pennyShapedToughnessDominated_smoke.xml
- [ ] inputFiles/hydraulicFracturing/pennyShapedViscosityDominated_smoke.xml
- [ ] inputFiles/hydraulicFracturing/pknViscosityDominated_smoke.xml
- [ ] inputFiles/hydraulicFracturing/walshQuarterNoChombo_smoke.xml
- [ ] inputFiles/lagrangianContactMechanics/ContactMechanics_PassingCrack_smoke.xml
- [ ] inputFiles/lagrangianContactMechanics/ContactMechanics_SimpleCubes_smoke.xml
- [ ] inputFiles/lagrangianContactMechanics/ContactMechanics_SingleFracCompression_smoke.xml
- [ ] inputFiles/lagrangianContactMechanics/ContactMechanics_TFrac_smoke.xml
- [ ] inputFiles/lagrangianContactMechanics/ContactMechanics_UnstructuredCrack_smoke.xml
- [ ] inputFiles/lagrangianContactMechanics/Sneddon_contactMechanics_smoke.xml
- [ ] inputFiles/meshGeneration/multiBodyMeshGen_smoke.xml
- [ ] inputFiles/multiphysics/kgdViscosityDominated_Base.xml
- [ ] inputFiles/phaseField/PhaseFieldFracture_CohesiveModel.xml
- [ ] inputFiles/phaseField/PhaseFieldFracture_DamageAndLoad.xml
- [ ] inputFiles/phaseField/PhaseFieldFracture_DamageOnly.xml
- [ ] inputFiles/phaseField/PhaseFieldFracture_SpectralSplit.xml
- [ ] inputFiles/phaseField/PhaseFieldFracture_VolDevSplit.xml
- [ ] inputFiles/poromechanics/PoroDruckerPragerWellbore_smoke.xml
- [ ] inputFiles/poromechanics/PoroElasticWellbore_smoke.xml
- [ ] inputFiles/poromechanics/PoroElastic_Mandel_smoke.xml
- [ ] inputFiles/poromechanics/PoroElastic_Terzaghi_smoke.xml
- [ ] inputFiles/poromechanics/PoroElastic_deadoil_3ph_baker_2d.xml
- [ ] inputFiles/poromechanics/PoroElastic_embFractures.xml
- [ ] inputFiles/poromechanics/SlipPermeability_embeddedFrac.xml
- [ ] inputFiles/poromechanics/SlipPermeability_pEDFM_smoke.xml
- [ ] inputFiles/proppant/FlowProppantBedTransport2d_smoke.xml
- [ ] inputFiles/proppant/FlowProppantTransport2d_smoke.xml
- [ ] inputFiles/proppant/ProppantGelTransport_smoke.xml
- [ ] inputFiles/proppant/ProppantSlotTest_smoke.xml
- [ ] inputFiles/simplePDE/10x10x10Hex_LaplaceFEM_smoke.xml
- [ ] inputFiles/simplePDE/10x10x10Hex_LaplaceVEM_smoke.xml
- [ ] inputFiles/simplePDE/10x5x15Wedges_LaplaceVEM_smoke.xml
- [ ] inputFiles/simplePDE/15x5x10Tets_LaplaceVEM_smoke.xml
- [ ] inputFiles/simplePDE/50x10x5Hex_LaplaceFEM_smoke.xml
- [ ] inputFiles/singlePhaseFlow/3D_10x10x10_compressible_smoke.xml
- [ ] inputFiles/singlePhaseFlow/FieldCaseTutorial3_smoke.xml
- [ ] inputFiles/singlePhaseFlow/compressible_1d.xml
- [ ] inputFiles/singlePhaseFlow/compressible_1d_2solids.xml
- [ ] inputFiles/singlePhaseFlow/compressible_2d_2fluids.xml
- [ ] inputFiles/singlePhaseFlow/compressible_2d_2fluids_hybrid.xml
- [ ] inputFiles/singlePhaseFlow/fractureFlow_2d.xml
- [ ] inputFiles/singlePhaseFlow/fractureJunctionFlow_2d.xml
- [ ] inputFiles/singlePhaseFlow/fractureMatrixFlow_2d.xml
- [ ] inputFiles/singlePhaseFlow/fractureMatrixFlow_Embedded2d.xml
- [ ] inputFiles/singlePhaseFlow/fractureMatrixFlow_impermeableEmbFrac.xml
- [ ] inputFiles/singlePhaseFlow/incompressible_1d.xml
- [ ] inputFiles/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_hex_gravity_smoke.xml
- [ ] inputFiles/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_pyramid_gravity_smoke.xml
- [ ] inputFiles/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_tetra_2_regions_half_flow_smoke.xml
- [ ] inputFiles/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_tetra_2_regions_smoke.xml
- [ ] inputFiles/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_tetra_gravity_smoke.xml
- [ ] inputFiles/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_wedge_gravity_smoke.xml
- [ ] inputFiles/singlePhaseFlow/sourceFlux_1d.xml
- [ ] inputFiles/singlePhaseFlow/sourceFlux_2d.xml
- [ ] inputFiles/singlePhaseFlow/staircase_3d.xml
- [ ] inputFiles/singlePhaseWell/compressible_single_phase_wells_1d.xml
- [ ] inputFiles/singlePhaseWell/compressible_single_phase_wells_hybrid_1d.xml
- [ ] inputFiles/singlePhaseWell/incompressible_single_phase_wells_2d.xml
- [ ] inputFiles/singlePhaseWell/incompressible_single_phase_wells_hybrid_2d.xml
- [ ] inputFiles/singlePhaseWell/staircase_single_phase_wells_3d.xml
- [ ] inputFiles/singlePhaseWell/staircase_single_phase_wells_hybrid_3d.xml
- [ ] inputFiles/solidMechanics/ExtendedDruckerPragerWellbore_smoke.xml
- [ ] inputFiles/solidMechanics/KirschProblem_smoke.xml
- [ ] inputFiles/solidMechanics/ModifiedCamClayWellbore_smoke.xml
- [ ] inputFiles/solidMechanics/OpenWellbore.xml
- [ ] inputFiles/solidMechanics/beamBending_smoke.xml
- [ ] inputFiles/solidMechanics/casedWellbore.xml
- [ ] inputFiles/solidMechanics/elasticHollowCylinder.xml
- [ ] inputFiles/solidMechanics/gravity.xml
- [ ] inputFiles/solidMechanics/mechanicsWithHeterogeneousMaterials.xml
- [ ] inputFiles/solidMechanics/sedov_finiteStrain_smoke.xml
- [ ] inputFiles/solidMechanics/sedov_ssle_smoke.xml
- [ ] inputFiles/solidMechanics/sedov_with_bias.xml
- [ ] inputFiles/solidMechanics/solidMechBlock.xml
- [ ] inputFiles/surfaceGeneration/DryFrac_StaticPenny_PrismElem.xml
- [ ] inputFiles/surfaceGeneration/DryFrac_ThreeNodesPinched_HorizontalFrac.xml
- [ ] inputFiles/surfaceGeneration/DryFrac_ThreeNodesPinched_SlantFrac.xml
- [ ] inputFiles/surfaceGeneration/SurfaceGenerator.xml
- [ ] inputFiles/wavePropagation/acous3D_abc.xml
- [ ] inputFiles/wavePropagation/acous3D_abcAndFreeSurface.xml
- [ ] inputFiles/wellbore/CasedElasticWellbore_smoke.xml
- [ ] inputFiles/wellbore/DeviatedElasticWellbore_smoke.xml
- [ ] inputFiles/wellbore/DeviatedPoroElasticWellbore_Drilling_smoke.xml
- [ ] inputFiles/wellbore/DeviatedPoroElasticWellbore_Injection_smoke.xml

**Comment by cssherman** [comment]
I threw together a quick script to check whether xml files are linked somewhere in the integrated tests repo, or contains one of the following keywords: base, benchmark, old.  I'm not attempting to parse the ats files, so there is chance that additional files are missing.  The current orphan files include: 

- [ ] examples/AdaptiveTimeStepping/deadoil_3ph_baker_1d.xml
- [ ] examples/GPU/beamBending.xml
- [ ] examples/advanced_xml_features/included/included_a.xml
- [ ] examples/advanced_xml_features/included/included_b.xml
- [ ] examples/advanced_xml_features/included/included_c.xml
- [ ] examples/advanced_xml_features/included_files_example.xml
- [ ] examples/advanced_xml_features/parameters_example.xml
- [ ] examples/advanced_xml_features/symbolic_math_example.xml
- [ ] examples/compositionalFlow/kernelTest/kernelTest.xml
- [ ] examples/event_examples.xml
- [ ] examples/functions/function_examples/function_examples.xml
- [ ] examples/pygeosxExamples/hydraulicFractureWithMonitor/hydraulicFracture.xml
- [ ] examples/pygeosxExamples/modifyBoundaryCondition/pkn_example.xml
- [ ] examples/pygeosxExamples/parametricSurfaceMapping/parametricMesh.xml
- [ ] examples/pygeosxExamples/sedovWithStressFunction/modified_sedov.xml
- [ ] examples/sedovKernelTest.xml
- [ ] examples/singlePhaseFlow/kernelTestFVM/kernelTestFVM.xml
- [ ] inputFiles/compositionalMultiphaseFlow/deadoil_3ph_corey_1d_fractured.xml
- [ ] inputFiles/compositionalMultiphaseWell/simpleCo2InjTutorial_smoke.xml
- [ ] inputFiles/hydraulicFracturing/hydrofractureSinglePhase2d.xml
- [ ] inputFiles/hydraulicFracturing/kgdSmokeBase_C3D6.xml
- [ ] inputFiles/hydraulicFracturing/pknViscosityDominated_smoke.xml
- [ ] inputFiles/meshGeneration/multiBodyMeshGen_smoke.xml
- [ ] inputFiles/multiphysics/kgdViscosityDominated_Base.xml
- [ ] inputFiles/poromechanics/SlipPermeability_embeddedFrac.xml
- [ ] inputFiles/proppant/ProppantGelTransport_smoke.xml
- [ ] inputFiles/singlePhaseFlow/3D_10x10x10_compressible_smoke.xml
- [ ] inputFiles/singlePhaseFlow/FieldCaseTutorial3_smoke.xml
- [ ] inputFiles/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_hex_gravity_smoke.xml
- [ ] inputFiles/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_pyramid_gravity_smoke.xml
- [ ] inputFiles/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_tetra_2_regions_half_flow_smoke.xml
- [ ] inputFiles/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_tetra_2_regions_smoke.xml
- [ ] inputFiles/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_tetra_gravity_smoke.xml
- [ ] inputFiles/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_wedge_gravity_smoke.xml
- [ ] inputFiles/solidMechanics/OpenWellbore.xml
- [ ] inputFiles/solidMechanics/casedWellbore.xml
- [ ] inputFiles/solidMechanics/elasticHollowCylinder.xml
- [ ] inputFiles/solidMechanics/mechanicsWithHeterogeneousMaterials.xml
- [ ] inputFiles/solidMechanics/sedov_with_bias.xml
- [ ] inputFiles/solidMechanics/solidMechBlock.xml

@rrsettgast - any thoughts on our strategy here?

**Comment by cssherman** [comment]
A good chunk of these are due to me, and illustrate either pygeosx or advanced xml features.  I'm not sure if we are able to use these with the tests yet, but it would be great if we could
