### ISSUE TITLE
meshBody(0) and meshLevel(0) are hardcoded everywhere.

### ISSUE THREAD

**Issue by joshua-white** [GEOSX/GEOSX#951]
We started with ambitions of supporting multiBody and multiLevel grids.  If you type:
```sh
grep -r "getMeshLevel( 0 )" src/
```
you will see that `meshBody(0)` and `meshLevel(0)` are now hardcoded literally everywhere.  Do we continue to support this feature if no one is using it?  Or perhaps provide a shortcut accessor for 99% of the code that could care less about more complex grids, and leave this as an advanced feature for specialized solvers?  The latter may be easiest.

**Comment by TotoGaz** [comment]
@rrsettgast We may want to close https://github.com/GEOSX/GEOSX/pull/1682 when is merged, don't we?
